### ISSUE TITLE
[storage] a pdo storage

### ISSUE THREAD

**Issue by makasim** [Payum/Payum#205]
The storage takes a PDO connection, columns and can save\fetch a model to sql databases.

**Comment by alexandernst** [comment]
@makasim I'm considering working on this issue or #206. Which one should I do? A PDO could be used by all framework extensions (and saving everything to the file system is not recommended in prod servers). Yii extension would greatly benefit from this one. On the other hand, #206 seems quite useful too.

**Comment by makasim** [comment]
It depends on what you personally need more. I'd say this one is harder than #206 but at the same time more useful.

**Comment by alexandernst** [comment]
This one is it then :)
Let me check how the FS storage works, that should be a good starting point, right?
The PDO storage extension should, basically, work the same way as the FS storage, right?

**Comment by makasim** [comment]
its better to look at doctrine\propel\eloquent storages, as they deal with databases too. The hard part of the PR is a schema

**Comment by alexandernst** [comment]
@makasim Hi! Sorry for disappearing, I got (again) re-assigned. Anyways, I think I'm back now, shall we resume? :)

I think I need a more global vision. Can you explain:

* in which situations (and from where) is the storage called (both queried and triggered a save)
* what exactly  does a storage need to implement (a part from a method to search by an ID)

**Comment by makasim** [comment]
The store is used manually in prepare method like $storage->create(); $storage->update($model);
and implicitly in storage extension.

**Comment by makasim** [comment]
storage must implement storage interface.

**Comment by makasim** [comment]
Some of the storages,

* [EloquentStorage](https://github.com/Payum/PayumLaravelPackage/blob/master/src/Payum/LaravelPackage/Storage/EloquentStorage.php).
* [Doctrine ORM\ODM](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Doctrine/Storage/DoctrineStorage.php)
* [Propel2](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Propel2/Storage/Propel2Storage.php)

maybe it would be better to implement active record storage for Yii,

**Comment by alexandernst** [comment]
@makasim I'm fine with a "native" (read as "built-in") PDO storage in Payum.
Anyways, as far as I can tell, the projects I'm/will be working on will probably require a NoSQL (MongoDB) storage, so I'll try to implement both a generic PDO storage and a MongoDB storage.

Let's go ahead with the PDO  for now. Let me see if I can push an initial skeleton...

**Comment by makasim** [comment]
closer as there is PR for this issue
