### ISSUE TITLE
[Order] Allow set credit card to order.

### ISSUE THREAD

**Issue by makasim** [Payum/Payum#206]
addition to https://github.com/Payum/Payum/pull/204

**Comment by alexandernst** [comment]
What about this one @makasim ? Any PR for it?

**Comment by makasim** [comment]
nobody worked on that

**Comment by alexandernst** [comment]
But... isn't possible to pay with a VISA/MasterCard now? (using PayPal)
I'm not really sure if I understand this issue.

**Comment by makasim** [comment]
The issue is pretty simple: The order interface https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/OrderInterface.php must have a setter getter method for a credit card: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/CreditCardInterface.php


And later in a place like https://github.com/Payum/Payum/blob/master/src/Payum/AuthorizeNet/Aim/Action/FillOrderDetailsAction.php#L22 this would allow to set credit card details. It is needed to avoid a credit card form on capture action when you have it already

**Comment by makasim** [comment]
> But... isn't possible to pay with a VISA/MasterCard now? (using PayPal)

yes it is possible if you use paypal specific format, but it is partly possible with the unified interface (order interface).
