### ISSUE TITLE
paypal SSL problem

### ISSUE THREAD

**Issue by greg606** [Payum/Payum#233]
I'm getting the error:

```
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

Issue is explained here: 
http://stackoverflow.com/questions/26763737/update-php-curl-request-from-sslv3-to-tls/26764845#26764845
and here
https://stackoverflow.com/questions/26452755/php-curl-is-probably-using-sslv3-insted-of-tls-when-connecting-to-https/26765281#26765281

Can curl request be configured?

**Comment by 33sKamal** [comment]
i got same error but in 2018 lol
Please help me if you do know the answer 
see this picture 
![firstcapture](https://user-images.githubusercontent.com/19997864/35862943-4fe52142-0b45-11e8-8712-c979bb0f95c7.JPG)
