### ISSUE TITLE
Handling notification/callback url's

### ISSUE THREAD

**Issue by mkurzeja** [Payum/Payum#253]
Hi!

I'm currently working on a PayU integration for Payum.
It's almost working but I've encountered one problem: handling a callback request.

When I start a transaction I'm redirecting the user to the PayU website. After the payment he is redirected back to the done action. Unfortunately in PayU the payment is usually pending at this time.
PayU is using a callback URL to notify merchant about every transaction change:
http://developers.payu.com/en/restapi.html#update_notification_for_order_status
https://github.com/PayU/openpayu_php#handling-notifications-from-payu

Do you have any example how this could be done in Payum? I've tried to use the payum_notify_do route in Symfony and a NotificationAction but the address does not match the target url.
The easiest solution is to add a new route/file to handle all callbacks but it would be great to fully integrate it with Payum.

Thanks for your help.

**Comment by petarvasilev91** [comment]
Does anyone know how to change the notify url for PayPal express checkout. I have this code:

```
$notifyToken = $this->getPayum()->getTokenFactory()->createNotifyToken($paymentName, $details);
$details['PAYMENTREQUEST_0_NOTIFYURL'] = $notifyToken->getTargetUrl();
```

which automatically generates a URL, any ideas?
