### ISSUE TITLE
clarify TokenVerifier

### ISSUE THREAD

**Issue by backbone87** [Payum/Payum#258]
Proposed changes:
- rename HttpRequestTokenVerifierInterface to TokenVerifierInterface, and change the verify param signature to ($hash)
- in concrete implementations of TokenVerifierInterface the $hash param might be a Request instance or an array, how to obtain the hash from this argument is impl specific

TokenVerifier (base impl of TokenVerifierInterface)
```php
public function verify($hash) {
  if(!is_scalar($hash)) throw ...;
  // obtain token by hash
}
```

ArrayRequestTokenVerifier (extends TokenVerifier)
```php
public function verify($hash) {
  if(is_array($hash) || $hash instanceof \ArrayAccess) {
    $hash = $hash[$this->hashField];
  }
  return parent::verify($hash);
}
```

(Symfony)HttpRequestTokenVerifier (extends Token Verifier)
```php
public function verify($hash) {
  if($hash instanceof Request) {
    $hash = $hash->get($this->hashField);
  }
  return parent::verify($hash);
}
```

**Comment by makasim** [comment]
The implementation is not that simple, for example symfony token verifier throw symfony's http exceptions and that's hard to re-implement that with composition.
