### ISSUE TITLE
naming of PaymentInterface and OrderInterface is confusing

### ISSUE THREAD

**Issue by backbone87** [Payum/Payum#263]
PaymentInterface is actually a PaymentProcessorInterface
OrderInterface is actually a PaymentInterface

The first one should be obvious. PaymentInterface DOES something and usually communicates with the "outside". It is the payment PROCESS.

The second one represents actually a specific payment. An actual order could have multiple payments (failed payments, partial payments etc) and should be left completely application specific.

**Comment by makasim** [comment]
It will be addressed here https://github.com/Payum/Payum/issues/335
