### ISSUE TITLE
Quick Question: Where is the DB Schema located?

### ISSUE THREAD

**Issue by jasonherndon** [Payum/Payum#299]
We're looking integrating Payum and would like to know what changes it will make to our database before we do so. I've searched but can't find any info in the docs/source with info on what tables/columns Payum will add to our database. Is there a file with the Schema somewhere or does it not change any database values?

**Comment by makasim** [comment]
Well, it depends on what way of integration you choose.

* In most cases a use an order model with details column. which is array
(json_array doctrine type). The order implements DetailsAwareInterface and
DetailsAggregateInterface. Like this one:
https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/Order.php
basic schema for it here:
https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Doctrine/Resources/mapping/Order.orm.xml

* You can choose this variant if you do not want to extend Payums
interfaces, like Sylius does. So you have to add an action like this
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Payum/Action/ExecuteSameRequestWithPaymentDetailsAction.php
to a payment and the model looks like this
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Payment/Model/Payment.php#L82

* The simplest way is to implement ArrayAccess interface on your model and
pass it to Payum. I have such a model
https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/ArrayObject.php
with basic schema
https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Doctrine/Resources/mapping/ArrayObject.orm.xml

These is not all the possible case there are other more advanced stuff like
tracking history of payment changes. Everything is possible.

On Tue, Jan 6, 2015 at 10:40 PM, Jason Herndon <notifications@github.com>
wrote:

> We're looking integrating Payum and would like to know what changes it
> will make to our database before we do so. I've searched but can't find any
> info in the docs/source with info on what tables/columns Payum will add to
> our database. Is there a file with the Schema somewhere or does it not
> change any database values?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Payum/Payum/issues/299>.
>



-- 
Kotlyar Maksim,
Payum founder, Sylius core team member, symfony developer
Visit http://payum.forma-dev.com and follow us
<https://twitter.com/payumphp> on Twitter.

**Comment by kayue** [comment]
@jasonherndon yes!

**Comment by jasonherndon** [comment]
Awesome - thanks!
