### ISSUE TITLE
Propel Integration

### ISSUE THREAD

**Issue by liamsorsby** [Payum/Payum#305]
Hi There,

I can see that a PR has already been made for propel integration. Is there an estimated time of release for this as of yet?

Thank you in advance.

**Comment by makasim** [comment]
nope, it is not a priority for me, but you can pick it up and finish, the code has to be reviewed and polished (if needed). I cannot merge that without tests and the doc too

**Comment by makasim** [comment]
If you want to continue discussion lets do that in the PR https://github.com/Payum/Payum/pull/144
