### ISSUE TITLE
Webpage is not accesible

### ISSUE THREAD

**Issue by alexandernst** [Payum/Payum#316]
I'm not really sure where to put this, so here it goes:

The webpage `www.payum.org` is not accesible (it's asking for a login/password), while `payum.org` works fine.

**Comment by makasim** [comment]
www.payum.org - is not mapped to payum.org. there is another projected hosted on the same machine and it is http://fansfeed.com/. I'll try to set a redirect for www version to payum.org.

**Comment by makasim** [comment]
fixed
