### ISSUE TITLE
I'm missing isSuccess()

### ISSUE THREAD

**Issue by alexandernst** [Payum/Payum#318]
Last time I used this project I could run `isSuccess()` on a `status`, and that would tell me if the payment was actually done (if I received the money). Now I see `isCaptured` and `isAuthorized` (among others), but I'm not sure those let me know if the payment was actually succeded.

What should I use?

**Comment by makasim** [comment]
it was renamed to `isCaptured`. It is noted in UPGRADE.md file

**Comment by makasim** [comment]
if you do $payment->execute(new Capture($model))

you have to use isCaptured true. same goes for authorize.

most of the time I do something like ($status->isAuthorized() && $status->isCaptured())

**Comment by alexandernst** [comment]
I see, this is what you refer: https://github.com/Payum/Payum/blob/master/UPGRADE.md#011-to-012
But I'm not really sure `isCaptured` and `isAuthorized` are good names. Maybe I'm missing the logic behind that name, if so, I bed a pardon.

EDIT:

Ok, after thinking about is again I think I see your point. `isCaptured` tells you if the call was actually saved, while `isAuthorized` tells you if the payment was done, so `ìsSuccess` now is a combination of those two methods. Am I right?

**Comment by makasim** [comment]
I if you want to perform a capture (capture request) then  a success status will be isCaptured -> true.

**Comment by alexandernst** [comment]
Ok, something here is buggy and I'm not sure if it's my code or not.

I have a project that was working fine with an older version of Payum. I decided to upgrade to 0.14 and for that I made all the required changes (or I think I did).

But now my payments "aren't" working. All payments are captured but none of them is authorized, and yet I see how my sandbox account's amount of money is decreasing after each test.

That is how I make the prepare:

    $paymentName = 'paypal_ec';
    $payum = $this->getPayum();

    $product = //Code to get the product user is buying

    $storage = $payum->getRegistry()->getStorage('PaymentDetails', $paymentName);
    $details = $storage->create();

    $details['PAYMENTREQUEST_0_AMT'] = $product->price;
    $details['L_PAYMENTREQUEST_0_AMT0'] = $product->price;

    $details['NOSHIPPING'] = 1;
    $details['PAGESTYLE'] = 'GeoAPI';
    $details['PAYMENTREQUEST_0_CURRENCYCODE'] = 'EUR';
    $details['L_PAYMENTREQUEST_0_NAME0'] = $product->getPaypalName();

    $details['ITEM_NUMBER'] = $product->idkey;

    $details['L_PAYMENTREQUEST_0_DESC0'] = $product->getPaypalDesc();
    $details['L_PAYMENTREQUEST_0_QTY0'] = 1;

    $storage->update($details);
    $captureToken = $payum->getTokenFactory()->createCaptureToken($paymentName, $details, "paypal/done");

    $this->redirect($captureToken->getTargetUrl());


And this is my "done" code:

    $payum = $this->getPayum();

    $token = $payum->getHttpRequestVerifier()->verify($_REQUEST);
    $payment = $payum->getRegistry()->getPayment($token->getPaymentName());

    $status = new GetHumanStatus($token);
    $payment->execute($status);

    if($status->isCaptured() && $status->isAuthorized()){

        //Code that shows the user that his payment is done

    }else{

        //Code that renders an error page with $status->getValue()
        //At this point $status->getValue() says "Payment status is captured"
        //But my sandbox paypal account's money has decreased
    }

Am I doing something wrong?

**Comment by makasim** [comment]
just check for `if($status->isCaptured()){`

**Comment by makasim** [comment]
This is where status is set: https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Action/PaymentDetailsStatusAction.php#L17

**Comment by alexandernst** [comment]
Now I'm really confused. Can you explain what is the difference between a captured and an authorized state? I mean, from what I see in the code, a captured state is just a representation of "user payed successfully", but what is an authorized state? When does it happen?

**Comment by makasim** [comment]
https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECRelatedAPIOps/

look for "Authorization Payment Action for Express Checkout" there. BTW Payum does not support paypal authorize right now.

**Comment by alexandernst** [comment]
I have forgotten quite some things about PayPal since last time I sent you patches :)
Anyways, now I recovered those lost bits and I upgraded successfully my project.

Would you accept a PR with a doc about a little bit more complex example of Payum with Yii?

**Comment by makasim** [comment]
> Would you accept a PR with a doc about a little bit more complex example of Payum with Yii?

yes sure, contributions are very welcome/
