### ISSUE TITLE
Cancel recurring payments

### ISSUE THREAD

**Issue by alexandernst** [Payum/Payum#320]
I'm wondering if a recurring payment can be canceled from Payum, or that is something that can be done only from PayPal's profile panel. Can it be done?

**Comment by makasim** [comment]
not yet, It could be done this way now https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaypalExpressCheckoutBundle/Controller/RecurringPaymentExamplesController.php#L177

but would be good to wrap to cancel action so it looks like: $payment->execute(new Cancel($model));

**Comment by alexandernst** [comment]
Let's continue this in the PR :)
