### ISSUE TITLE
The use of GetHumanStatus and Sync when using with PayPal ExpressCheckout NVP

### ISSUE THREAD

**Issue by kminh** [Payum/Payum#332]
Payum has been working quite well for me so far, but I just don't understand the proper use of `GetHumanStatus` and `Sync` especially when used with PayPal Express Checkout NVP. My configuration for PayPal is:

```yaml
payum:
    ...
    contexts:
        subscription_offline:
            offline: ~
        subscription_paypal:
            paypal_express_checkout_nvp:
            ...
```

For example, I'm cancelling a recurring profile. The codes is:

```php
$paymentGateway = $this->get('payum')->getPayment('subscription_paypal');
$paymentGateway->execute(new Payum\Core\Request\Cancel($payment)); // this one throws error
// or
$payment['ACTION'] = 'Cancel';
$paymentGateway->execute(new Payum\Paypal\ExpressCheckout\Nvp\Request\Api\ManageRecurringPaymentsProfileStatus($payment));
```

I found an example here: https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaypalExpressCheckoutBundle/Controller/RecurringPaymentExamplesController.php#L177 and it uses `Payum\Core\Request\Cancel`. For me using that throws an error:

```php
Request Cancel{model: RecurringPaymentDetails} is not supported. 
```

What confuses the most is after I do this:

```php
$paymentGateway->execute(new ManageRecurringPaymentsProfileStatus($payment));
```

What would be the purpose of:
```php
$paymentGateway->execute(new Sync($payment)); // is it to save the payment details back to db?
```

and what should I do if I want to check the status of request, for e.g. I want to know if the recurring profile has been cancelled successfully? Will the `execute` method updates the payment details in database whenever I call it?

Thanks for any insight.

**Comment by makasim** [comment]
> I found an example here: https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaypalExpressCheckoutBundle/Controller/RecurringPaymentExamplesController.php#L177 and it uses Payum\Core\Request\Cancel. For me using that throws an error:

try to upgrade payum, to use cancel request you have to have the latest version from master branch.

**Comment by makasim** [comment]
> What would be the purpose of:

The basic idea behind Sync request is: fetch payment details from the gateway side (they may be updated) and store them back to the model.

**Comment by makasim** [comment]
> and what should I do if I want to check the status of request, for e.g. I want to know if the recurring profile has been cancelled successfully?

```php
<?php
$paymentGateway->execute($status = new GetHumanStatus($payment));

$status->isCanceled();
```
