### ISSUE TITLE
[RFC] Rename payment to gateway. 

### ISSUE THREAD

**Issue by makasim** [Payum/Payum#335]
This way:

* PaymentInterface -> GatewayInerface
* PaymentFactoryInterface -> GatewayFactoryInerface
* PaymentRegistryInterface -> GatewayRegistryInterface
* PaymentRegistryInterface::getPayment -> GatewayRegistryInterface::getGateway

and so. 

It is a huge change, so I want to get a feedback whether we really need it before I start changing it.

**Comment by pjedrzejewski** [comment]
I'd vote yes. It is really confusing at first...

**Comment by stloyd** [comment]
:+1: for rename, gateway is not payment and avoiding confusion even in BC break way good idea, you can always add "layer" to hold BC for one or two versions for easier migration...

**Comment by makasim** [comment]
merged
