### ISSUE TITLE
Error 500 Internal Server Error on PayPal

### ISSUE THREAD

**Issue by SSMark** [Payum/Payum#341]
Good afternoon, i followed the get it started tutorial on payum, i installed the library fine, i'm using it under zend, i have an https ssl domain using NSS i commented the line:

$client->setOption(CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

into Buzz\ClientFactory.php to avoid the tlsv1 error

"capture.php" redirects to paypal using for example the following address:
https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-1F289429KC888705D

but once redirect into paypal the following error appears:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@paypal.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

what's the problem? i checked my username, password and signature of my sandbox account and are ok.
I really need this working as soon as possible,
Thanks in advance.

**Comment by makasim** [comment]
>  The server encountered an internal error or misconfiguration and was unable to complete your request.

do you use the symfony app in debug mode? I dont think so. If you turn the debug mode on you will see an exception, its message stacktrace and so on. Or if you are not able to do that you can find out about exception in app/logs/xxx.log file.

**Comment by SSMark** [comment]
Thanks for the reply, two things
1) if i change the path of the paypal express checkout removing sandbox:
from
https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-1F289429KC888705D
to
https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-1F289429KC888705D
displays:
Your session has ended
We're sorry, but your session has ended. Your account hasn't been charged. Please go back to the merchant's site and check out again with PayPal.
(the token is from yesterday so i think it's normal that is not valid anymore)
So maybe the problem is only using sandbox, i need to try with my paypal real data.

2) following http://payum.org/doc/0.14/Core/debugging i don't understand where i need to add the code

thanks in advance

**Comment by SSMark** [comment]
I tried with real data, with real data appears the correct order page with the paypal login, but no order info (no order description displayed, no order total displayed):

Your order summary

Descriptions
Current purchase
You'll be able to see your order details before you pay.

**Comment by makasim** [comment]
IF you want to see that info you have to configure it, here's an example: https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaypalExpressCheckoutBundle/Controller/PurchaseExamplesController.php#L171

**Comment by SSMark** [comment]
if i procede with the payment, it ends fine, i can see the payment completed on merchant side, soo seems working but not data displayed for the order customer side

**Comment by SSMark** [comment]
@makasim  understood thanks, so it's a sanbox problem

**Comment by SSMark** [comment]
@makasim without installing the bundle, without Symfony Acme\PaymentBundle\Entity\PaymentDetails is missing, i'm under zend 1, i made it manually following the get it started, i have the following packages:
{
    "require": {
        "payum/paypal-express-checkout-nvp": "0.14.1",
        "payum/paypal-ipn": "0.14.0"
    }
}
in my case how i can specify the express checkout order details and the recurring payment details? using the default Payum\Core\Model\Order i can't.

Thanks in advance

**Comment by SSMark** [comment]
@makasim  if i make manually the model:
<?php
namespace Payum\Core\Model;

class PaymentDetails extends ArrayObject
{
    protected $id;
    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
}
inside payum/core/Payum/Core/Model doesn't work

**Comment by makasim** [comment]
Look for `put here any fields in a payment format.` here http://payum.org/doc/0.15/Core/get-it-started 

It's an example how to define payment specific details
