### ISSUE TITLE
Error while submiting paymentConfigType

### ISSUE THREAD

**Issue by jblanchon** [Payum/Payum#352]
Hi,
I've got an issue with the form when I submit the paymentConfigType.

The sandbox (checkbox input) cannot be unchecked. It give me this error
![screenshot-admin yprox dev 2015-04-14 14-30-45](https://cloud.githubusercontent.com/assets/5680711/7136664/6d7dc3a2-e2b3-11e4-8cbc-67bd56b19327.png)

**Comment by tristanbes** [comment]
We're using v0.14

**Comment by makasim** [comment]
should be fixed https://github.com/Payum/Payum/commit/95366580851b909ec078fbde7052689c5baaa84a

I'll tag it once tests pass on travis.

**Comment by tristanbes** [comment]
Great, thank you

**Comment by makasim** [comment]
https://github.com/Payum/Payum/releases/tag/0.14.5

**Comment by jblanchon** [comment]
This works fine ! :+1: 
thanks @makasim

**Comment by makasim** [comment]
Thanks for reporting the issue.
