### ISSUE TITLE
Typo in service name (form.xml)

### ISSUE THREAD

**Issue by jblanchon** [Payum/Payum#353]
In /home/jaybe/www/yProx/vendor/payum/payum-bundle/Resources/config/form.xml

your service name should be 
"payum.form.type.payment_config"
instead of
"payum.form.type.payment_conifg"

**Comment by makasim** [comment]
fixed https://github.com/Payum/Payum/commit/b1709865010c43b3d5628f508811baf28b0359b8

Thanks,

**Comment by jblanchon** [comment]
Thank you @makasim
