### ISSUE TITLE
How to is the relation of agreement and recurring payment on Paypal Recurrency?

### ISSUE THREAD

**Issue by silasrm** [Payum/Payum#370]
Hi,

My problem is understanding of relationship of agreement and recurring payment classes on Paypal recurrency.

I have a Order entity and I desire to make relationship with the agreement and recurring payment of the recurrency payment profile. But I'm confusing.

Each recurring payment profile have one agreement and many recurring payment, correct? Then, the relation is:

`Agreement <-> 1.1 <-> Recurrency Payment Profile <-> 1.N <-> Recurring Payment`

Other question:
When the Paypal take each debit of the Recurring Payment Profile, following the configurations, Payum receive the notification where? Because, I desire to register each billing cycle.

Thank's!

**Comment by makasim** [comment]
Not sure but should like you wrote:

```
Agreement <-> 1.1 <-> Recurrency Payment Profile <-> 1.N <-> Recurring Payment
```
