### ISSUE TITLE
Typo in composer.json for omnipay-bridge in branch 0.15 prevents installing it

### ISSUE THREAD

**Issue by dczech** [Payum/Payum#372]
payum/omnipay-bridge 0.15.0 requires payum/core 0.15. -> no matching package found.

**Comment by makasim** [comment]
Where is the typo?

**Comment by dczech** [comment]
`"payum/core": "0.15.",` in require section -> I think it should be `"payum/core": "0.15.*",`

**Comment by makasim** [comment]
It must be fixed in omnipay-bridge 0.15.1
