### ISSUE TITLE
Do a partial refund

### ISSUE THREAD

**Issue by mpoiriert** [Payum/Payum#373]
I was wondering if it's possible and how to do a partial refund ?

If it's not currently possible I might implement this. Is it possible to pin point how I should proceed ?

**Comment by makasim** [comment]
What payment do you want to use?

**Comment by mpoiriert** [comment]
Currently we are planing to use paypal express checkout and paypal pro

**Comment by makasim** [comment]
Right now Payum supports refund only for [Paypal PRO](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ProCheckout/Nvp/Action/RefundAction.php).

> If it's not currently possible I might implement this. Is it possible to pin point how I should proceed ?

1. Maybe add `PartialRefund`  request
2. Add a gateway specific PartialRefundAction for Paypal Pro and Paypal Express.
3. Add those action to gateway factory,

That's all.

If you want to use it in combination with  Payment model you have to create an PartialRefundAction as thin layer over previously created actions.

**Comment by makasim** [comment]
Here you can test paypal pro refund: http://sandbox.payum.forma-dev.com/payment/simple_purchase/paypal_pro_checkout/prepare

**Comment by mehmetsen80** [comment]
Makasim or Mpoiriert,
Do you have any example for Partial Refund?
I can refund normally for paypal pro but also need to run partial refund. Has anybody yet implemented this?
