### ISSUE TITLE
How to upgrade recurring payments profile?

### ISSUE THREAD

**Issue by silasrm** [Payum/Payum#378]
I desire updating recurring payments profile, on Paypal ExpressCheckout, but payum don't have action of UpdateRecurringPaymentsProfile.

Any idea?

**Comment by makasim** [comment]
Implement it

**Comment by silasrm** [comment]
I will try.
You have any tutorial about implementing actions on Payum, to help me?

**Comment by makasim** [comment]
http://payum.org/doc/0.15/Core/the-architecture
http://payum.org/doc/0.15/PayumBundle/custom_action_usage

**Comment by makasim** [comment]
http://payum.org/doc/0.15/Core/the-architecture
http://payum.org/doc/0.15/PayumBundle/custom_action_usage

**Comment by silasrm** [comment]
Thank's!

**Comment by silasrm** [comment]
@makasim help me.

I need to create a method like that  [```Payum\Paypal\ExpressCheckout\Nvp\Api::createRecurringPaymentsProfile(array $fields)```](https://github.com/Payum/Payum/blob/0.14/src/Payum/Paypal/ExpressCheckout/Nvp/Api.php#L424-L440), to set protected fields to my UpdateRecurringPaymentsProfile action/request.

How to I create this without edit this class on Payum package? Because the $api is injected, but I don't know where, to extends the $api object class and set the new, with my method.

**Comment by makasim** [comment]
do you use  a framework or plain php?

**Comment by silasrm** [comment]
Symfony 2.3.27

**Comment by makasim** [comment]
Good question I must admit. For now I can propose only a workaround: Extend this factory https://github.com/Payum/PayumBundle/blob/master/DependencyInjection/Factory/Gateway/PaypalExpressCheckoutNvpGatewayFactory.php and change the class returned by `getPayumGatewayFactoryClass` to your own in that class you can create an api instance with your custom method.

**Comment by silasrm** [comment]
I'll try.

Thk's

**Comment by silasrm** [comment]
I\m using Payum 0.14.0 and this factory don't exists: https://github.com/Payum/PayumBundle/blob/0.14/DependencyInjection/Factory/Gateway/PaypalExpressCheckoutNvpGatewayFactory.php

**Comment by makasim** [comment]
It is called payment, this is the right link: https://github.com/Payum/PayumBundle/blob/0.14/DependencyInjection/Factory/Payment/PaypalExpressCheckoutNvpPaymentFactory.php


FYI payments were renamed to gateways

**Comment by silasrm** [comment]
Something wrong.

I create my ```SON\BillingBundle\Payum\Factory\Payment\PaypalExpressCheckoutNvpPaymentFactory extends \Payum\Bundle\PayumBundle\DependencyInjection\Factory\Payment\PaypalExpressCheckoutNvpPaymentFactory``` with method:

```
    /**
     * {@inheritDoc}
     */
    protected function getPayumPaymentFactoryClass()
    {
        return 'SON\BillingBundle\Payum\Factory\PaymentFactory';
    }
```

And I created ```SON\BillingBundle\Payum\Factory\PaymentFactory extends Payum\Paypal\ExpressCheckout\Nvp\PaymentFactory``` with my method ```public function updateRecurringPaymentsProfile(array $fields)```. But I don't access the Api object, with this I don't make calling three methods to set required fields and make the request, because they are protected:

$this->addVersionField($request);
$this->addAuthorizeFields($request);
$this->doRequest($request);

-----

I very confusing now :(

**Comment by makasim** [comment]
@silasrm maybe it would be easier to contribute the method to Payum itself. I created an issue where I address the problems with api extension.

**Comment by silasrm** [comment]
I'm fork the repo and try to create the action on Payum. But I using the 0.14 on my project and I can't upgrade this.

**Comment by makasim** [comment]
Do the PR for 0.14, it is not a problem

**Comment by silasrm** [comment]
Ok

**Comment by silasrm** [comment]
Check my PR https://github.com/Payum/Payum/pull/382

Any errors?

**Comment by silasrm** [comment]
To update recurring payments profile, use UpdateRecurringPaymentsProfile, added in the versions 0.14.6/0.15.2 (PR #382)

@makasim thk's to help-me!

Closing.

**Comment by silasrm** [comment]
@makasim see PR #385 
Sorry with this error.
