### ISSUE TITLE
How to implement IPN with paypal

### ISSUE THREAD

**Issue by jackpf** [Payum/Payum#379]
Hi,

Quick question, I can't find any documentation on how to implement IPN with the paypal gateway. Currently all my orders are "pending", as no notification of payment is being received.

Are there docs for this? I can't figure it out.

Cheers

**Comment by makasim** [comment]
http://payum.org/doc/1.0/Core/instant-payment-notification

**Comment by petarvasilev91** [comment]
@makasim that link doesn't work
