### ISSUE TITLE
[RFC] Require PHP 5.5 and symfony 2.7 as lowest version.

### ISSUE THREAD

**Issue by makasim** [Payum/Payum#387]
Since the upcoming release of Payum will be 1.0, it means no BC breaks after it. So it would be good to set right php and symfony (for the bundle ) version.

@pjedrzejewski your opinion is the most important since this change impacts on Sylius a lot

**Comment by makasim** [comment]
@pjedrzejewski ping

**Comment by crevillo** [comment]
this is interesting to me. i'm trying to do a integration between eZ Publish and Sylius and got conflicts because sension/distribution-bundle requirements from sylius (or one of its deps)

**Comment by makasim** [comment]
It appeared that guzzlehttp/guzzle requires php5.5. I wanted to use because of psr7

**Comment by makasim** [comment]
One more point to get rid of old php versions.

**Comment by liamsorsby** [comment]
This would limit which server this can be installed (without modification).
http://www.sasaprolic.com/2013/02/list-of-current-php-version-in-major.html
Obviously this list is a little old now. However, Centos 7 supports 5.4 and Debian 7.5 wheezy is PHP 5.4.4. The only one that natively supports php 5.5 or above without any change is Ubuntu 14.04 LTS.

**Comment by aRn0D** [comment]
The end of life of PHP 5.4 will be in 2 months, so I am for PHP5.5  and symfony2.7. @pjedrzejewski I hope we do the same thing with Sylius ASAP.

**Comment by Flyingmana** [comment]
regarding PHP version maybe important:  
* http://php.net/supported-versions.php 
* http://www.zend.com/en/support-center/support/php-long-term-support

**Comment by pjedrzejewski** [comment]
Sylius will soon be bumped to 5.5 and 2.7, so you can safely bump Payum as well! :)

**Comment by makasim** [comment]
@pjedrzejewski Great!
