### ISSUE TITLE
Paypal Direct Payment

### ISSUE THREAD

**Issue by liamsorsby** [Payum/Payum#388]
Would we need to make a new pull request for Paypal Direct Payments? Or is it possible to just use one of the already implemented Paypal Bundles?

**Comment by makasim** [comment]
Isn't it same sa Paypal Pro Checkout

**Comment by makasim** [comment]
I dont real get the description of direct payment  at their site.

**Comment by liamsorsby** [comment]
Direct Payment allows you to have the card fields on your site. No card details saved but passed over to paypal.
https://developer.paypal.com/webapps/developer/docs/classic/paypal-payments-pro/integration-guide/WPDirectPayment/

**Comment by liamsorsby** [comment]
Might actually be the same, I'll have another check

**Comment by liamsorsby** [comment]
@makasim you can close this. It is the same just a different way of doing it different configuration options.
