### ISSUE TITLE
Is there some kind of issue with the Zend implementation?

### ISSUE THREAD

**Issue by Webvida** [Payum/Payum#396]
```php
<?php

use Buzz\Client\Curl;
use Payum\Core\Extension\StorageExtension;
use Payum\Core\Storage\FilesystemStorage;
use Payum\Paypal\ExpressCheckout\Nvp\Api;
use Payum\Paypal\ExpressCheckout\Nvp\PaymentFactory;

$detailsClass = 'Application\Model\PaymentDetails';

return array(
    'zf-mvc-auth' => array(
        'authentication' => array(
            'map' => array(
                'Status\\V1' => 'status',
            ),
        ),
    ),
    'payum' => array(
        'token_storage' => new FilesystemStorage(
            __DIR__.'/../../data',
            'Application\Model\PaymentSecurityToken',
            'hash'
        ),
        'payments' => array(
            'paypal_es' => PaymentFactory::create(new Api(new Curl(), array(
                'username' => 'REPLACE WITH YOURS',
                'password' => 'REPLACE WITH YOURS',
                'signature' => 'REPLACE WITH YOURS',
                'sandbox' => true
            )))
        ),
        'storages' => array(
            $detailsClass => new FilesystemStorage(__DIR__.'/../../data', $detailsClass, 'id'),
        )
    ),
);

```

So this is the standard "Configure payum module" as per instructions in your docs... http://payum.org/doc/0.11/PayumModule/get-it-started

and it is completely wrong...

<br />
<b>Fatal error</b>:  Class 'Payum\Paypal\ExpressCheckout\Nvp\PaymentFactory' not found in 
<b>/var/www/apigility/config/autoload/global.php</b> on line 
<b>26</b>
<br />

That class doesn't even exist, so I change to the correct class which seems to be: PaypalExpressCheckoutGatewayFactory

and then we start to get process, but there are so many issues - firstly the arguments sent to this constructer are reversed and need to be swapped to work and then many errors with sending objects to type array arguments...

Has this been tested? Am I using the right docs???

Thanks for any help you can give!

**Comment by makasim** [comment]
Which version do you use? stable 0.15? or master?

Stable version is expected to be work, at least it had been tested before I released it. Though doc may be out of sync with code. 

The master version of the module does not work with current master version of the library. I'll sync them when I am about release the library and the module.

**Comment by makasim** [comment]
The doc looks good to me http://payum.org/doc/0.15/PayumModule/get-it-started, at least the factory part.

**Comment by Webvida** [comment]
First of all, thank you soooo much for the fast response! Excellent :)

It seems that I somehow navigated to old documentation, sorry about that (http://payum.org/doc/0.11/PayumModule/get-it-started)

**Comment by Webvida** [comment]
Ok I came in from a google search and it seems to default the docs back to 0.11
