### ISSUE TITLE
Add TokenStorage to Registry

### ISSUE THREAD

**Issue by monkeyphp** [Payum/Payum#404]
Would it be feasible to add additional constructor parameter(s) to the AbstractRegistry so that TokenStorage and TokenFactory can be injected into the Registry?

https://github.com/Payum/Payum/blob/0.15/src/Payum/Core/Registry/AbstractRegistry.php#L28

I am trying to use the ZF2 module and although the Payum registry is injected into the PayumController, the TokenStorage isn't which means using the ServiceLocator to retrieve it - which kinda sucks.

**Comment by makasim** [comment]
I dont think it is a good idea
