### ISSUE TITLE
PayPal Express Checkout - missing step or how to add "confirm order" page

### ISSUE THREAD

**Issue by uvoelkel** [Payum/Payum#416]
Hi!

Maybe I'm missing something fundamental but it seems to me that the express checkout process is missing one crucial step namely the "confirm order" step.

If you look at the flow here: https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECGettingStarted/#id084RN0F0OPN
and here: https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECGettingStarted/#id076LF0X0F5Z
there should be a "confirm order" step before executing the payment.

The CaptureAction seems to execute SetExpressCheckout and DoExpressCheckoutPayment in one step. Is this the intended way it should work? Do I need to write my own actions or is there some other way to implement the "confirm order" page that I overlooked?

**Comment by makasim** [comment]
I suppose you show all order details, before user goes to paypal side, and if user click the "pay" button it means he confirms the payment. Also you can provide paypal with payment details, item name, title, unit price, quantity and so on so the user sees this on paypal side. 

And if you still want to do it "paypal way" it is possible. You have to add your capture action (for your model), check the payment status, and render confirm page.

IMO I dont see much sense in it.

**Comment by uvoelkel** [comment]
Thanks for the reply. 
It may not seem sensible but I still have to do it the "paypal way".

It is what people are used to and how they expect it to work. And even if I relabel the "continue" button and provide all the payment details, paypal still says something like "you can review you order before paying" below all the details. Which is just not true.

The bigger issue is that the german law requires you to follow certain guidelines what the final checkout page (the page where the next click actually pays) should look like. The total amount has to be displayed in a certain way and the pay-button needs a certain size, color/contrast and text. 
To follow these guidelines I see no way around the extra confirmation step.

So writing my own capture action it is. It's no big deal, I was just surprised that I seem to be the first to pick up on that issue.

**Comment by makasim** [comment]
> The bigger issue is that the german law requires you to follow certain guidelines what the final checkout page (the page where the next click actually pays) should look like.

I never thought about it from this perspective, I think the solution has to be provided out of the box.

**Comment by uvoelkel** [comment]
> I think the solution has to be provided out of the box.

Great to hear. I will gladly help out if give me some direction. I'm not sure what parts you are willing to change especially now that you are close to a 1.0 release.
Is this something that is exclusive to the PayPal Plugin or a core functionality that other plugins might also use?

**Comment by makasim** [comment]
I am thinking of an extra CaptureWithConfirmationAction, which additionally renders the confirmation template, must be set via constructor, and once user confirms it continue. Not sure it has to replace current one, I think a developer has to explicitly replace current impl with a confirmation one.

**Comment by makasim** [comment]
@uvoelkel there is a PR which fixes the issue
