### ISSUE TITLE
Documentation Request: More verbose details about Recurring Payments

### ISSUE THREAD

**Issue by felicitus** [Payum/Payum#418]
Hi,

I have followed the recurring payments guide on [payum.org](http://payum.org/doc/1.0.0-BETA1/PaypalExpressCheckoutNvp/recurring-payments-basics) but a few things aren't obvious:

* During testing, I noticed that the first recurring payment is booked on PayPal a few minutes later. How can I sync the payment of PayPal to my system? Do I need IPN for that?
* How can I initiate a recurring payment when the period is over? I have found the API Call `BillOutstandingAmount` in the PayPal documentation, however, it doesn't seem to be implemented in Payum.

Thanks
Felicitus

**Comment by makasim** [comment]
> During testing, I noticed that the first recurring payment is booked on PayPal a few minutes later. How can I sync the payment of PayPal to my system? Do I need IPN for that?

Yes, the IPN is the way to use it. Payum handles Paypal's notification out of the box, what you need is to register an extension which do what you need when the payment status is changed.

> How can I initiate a recurring payment when the period is over? I have found the API Call BillOutstandingAmount in the PayPal documentation, however, it doesn't seem to be implemented in Payum.

`BillOutstandingAmount` yes it is not implemented yet, but it is not big deal to add it.
