### ISSUE TITLE
Render a html form from captureAction

### ISSUE THREAD

**Issue by PurpleBabar** [Payum/Payum#427]
Hi everybody,

I created a captureAction and I get a response from an API inside my captureAction. 

The response I get, is a form returned in a string and I'd like to display it and have no clue how to do it : How should i do it ?

I have tried creating a renderTemplate Request but nothing seems to happen when i execute it.

If i don't do anything after getting this string in the captureAction i'm redirected to payment Step, not really what i'm looking for.

Thank you for your help

**Comment by makasim** [comment]
RenderTemplate request must do the job. What exactly does not work? Do you get an exception or?

**Comment by PurpleBabar** [comment]
Here is what I tried, but nothing seems to happen... I do not get an exception :/
```php
        $renderTemplateRequest = new RenderTemplate('WeeknlearnWebBundle:Frontend/Checkout/Step:mercanet.html.twig');
        $renderTemplateRequest->setResult($result);

        $this->payment->execute($renderTemplateRequest);
```

**Comment by makasim** [comment]
Indeed. You have to throw it: https://github.com/Payum/Payum/blob/master/src/Payum/Stripe/Action/Api/ObtainTokenAction.php#L75

**Comment by makasim** [comment]
And do not set result, the result is set by the action, at this line $this->payment->execute($renderTemplateRequest);

**Comment by PurpleBabar** [comment]
Thanks a lot, you saved the day :) 
By the way thanks too for the Payum library which is very useful :)
