### ISSUE TITLE
Fatal Error when using custom implementation of your library

### ISSUE THREAD

**Issue by adilsaeed31** [Payum/Payum#433]
HI,

i getting Call to undefined method Payum\Core\Payum::getHttpController() in /var/www/html/ppc/capture.php on line 8

I'm using below example

http://payum.org/doc/1.0/PaypalExpressCheckoutNvp/get-it-started

use same steps which you provide but undefined method, i have already load your dependency through composer vendor and include in config.php file like below

require __DIR__.'/vendor/autoload.php';

the prepare.php works fine but when we hit the our localhost/projectname then it redirects to capture.php file but without projectname with localhost/capture.php after that i need to add my custom name before capture.php file then it again press enter then it gives me above error. please advise what to do now.

Thanks
Adil

**Comment by makasim** [comment]
You have to set a custom token factory to the payum builder

```php
<?php
use Payum\Core\Registry\StorageRegistryInterface;
use Payum\Core\Storage\StorageInterface;
use Payum\Core\Bridge\PlainPhp\Security\TokenFactory;

$payum = (new PayumBuilder())
    ->addDefaultStorages()

    ->addGateway('gatewayName', [
        'factory' => 'paypal_express_checkout'
        'username'  => 'change it',
        'password'  => 'change it',
        'signature' => 'change it',
        'sandbox'   => true,
    ])

    ->setTokenFactory(function(StorageInterface $tokenStorage, StorageRegistryInterface $storageRegistry) {
        $baseUrl = 'http://localhost/projectname'; 

        return new TokenFactory($tokenStorage, $storageRegistry, $baseUrl);
    })

    ->getPayum()
;

```

Pay attention to baseUrl argument; I just wrote the code so it may not work or has typos. Hope you get the idea.

**Comment by adilsaeed31** [comment]
Now I used this code, it's not working too, and your getHttpController() is empty. Do you have any PHP complete test example code which i can download and test locally by only giving username/password/signature ?

**Comment by makasim** [comment]
Just remove that line `$payum->getHttpController()->capture();`. It went to docs accidentally, the http controller feature was not implemented. 

there is not an example for plain php, but bunch of example for frameworks https://github.com/makasim?tab=repositories. Look for PayumXXXSandbox.

**Comment by makasim** [comment]
You can also use https://github.com/Payum/PayumServer  as an example.

**Comment by makasim** [comment]
fixed https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/get-it-started.md

**Comment by adilsaeed31** [comment]
Do you have any Laravel 5 paypal recurring payment package examples.

**Comment by makasim** [comment]
Nope, but it is not hard to adopt exist ones.

**Comment by adilsaeed31** [comment]
Is there any recurring subscription of paypal example there, server.payum.com is paypal standard gateway example, basically i like your library but i need some good example to use it.

**Comment by makasim** [comment]
http://payum.org/doc/1.0/PaypalExpressCheckoutNvp/recurring-payments-basics

**Comment by adilsaeed31** [comment]
I have try this but i'm unable to use it, i'm very much confuse how to use it, can your provide me solid working code example.

**Comment by makasim** [comment]
That's all I have for now.

**Comment by adilsaeed31** [comment]
Can you create one for me, because i already serve 2 days on it, but i'm unable to create something. you know your whole code so it's easy for you to create a dummy example in laravel 5 or in plain php for me. not only for me i know there is lots of users who wants this. :) 
Thanks
