### ISSUE TITLE
Fluent Interface in models

### ISSUE THREAD

**Issue by mrcmorales** [Payum/Payum#441]
Hi,

I'm thinking to do a pull request adding fluent interface in every model, I think that is interesting and more easy to do a sequence to set difference properties,  like this example:

$payment->setNumber(uniqid())->setCurrency()->setXX()->setXXX()

Thanks

**Comment by makasim** [comment]
I dont think it is a good idea to add fluent interface to models, Here's why http://ocramius.github.io/blog/fluent-interfaces-are-evil/
