### ISSUE TITLE
GetHumanStatus uses "cancel" with single l

### ISSUE THREAD

**Issue by Gundars** [Payum/Payum#450]
GetHumanStatus.php constant and methods uses "cancel" with single L
const STATUS_CANCELED = 'canceled';

The paypal response contains "Cancelled" status, therefore usage of above constant and methods markCanceled(), isCanceled() always returns false even when transaction is successfully cancelled
https://github.com/Payum/Payum/blob/master/src/Payum/Core/Request/GetHumanStatus.php#L22

Proposing
- add a new constant and methods with double L to Payum\Core\Request\GetHumanStatus 
- add new methods to Payum\Core\Request\GetStatusInterface
- mark the single L functions deprecated
- fix unit tests, not sure if and how it works with current wrong methods/constant, maybe switch it to  Payum\Paypal\ExpressCheckout\Nvp\Api::RECURRINGPAYMENTSTATUS_CANCELLED in https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Tests/Action/PaymentDetailsStatusActionTest.php#L131

**Comment by makasim** [comment]
There was a fix related to paypal cancelled issue in the latest commits. Could you try the latest stable version. it has to work there.

**Comment by makasim** [comment]
> add new methods to Payum\Core\Request\GetStatusInterface

We cannot do it, because of BC promis.
