### ISSUE TITLE
Core factory is not injected to custom factory. Hence storages are not registered.

### ISSUE THREAD

**Issue by makasim** [Payum/Payum#452]
Originally posted on SO: http://stackoverflow.com/questions/34410960/create-a-custom-gateway-model-problems

i'm trying to create a custom gateway and have followed a lot of the different documentations. Yesterday i discovered the new Payum/Skeleton and started with that and followed that example.
Though i have a problem when redirected to the capture-page, i get the following two exceptions:

> Fatal error: Uncaught exception
> 'Payum\Core\Exception\RequestNotSupportedException' with message
> 'Request Capture{model: Identity} is not supported. Make sure the
> storage extension for "Payum\Core\Model\Payment" is registered to the
> gateway. Make sure the storage find method returns an instance by id
> "5678ff3e481ba". Make sure the gateway supports the requests and there
> is an action which supports this request (The method returns true).
> There may be a bug, so look for a related issue on the issue tracker.'
> in /home/vagrant/code/payumdibs/vendor/payum/core/Payum/Core/Exception/RequestNotSupportedException.php
> on line 57

And

> Payum\Core\Exception\RequestNotSupportedException: Request
> Capture{model: Identity} is not supported. Make sure the storage
> extension for "Payum\Core\Model\Payment" is registered to the gateway.
> Make sure the storage find method returns an instance by id
> "5678ff3e481ba". Make sure the gateway supports the requests and there
> is an action which supports this request (The method returns true).
> There may be a bug, so look for a related issue on the issue tracker.
> in
> /home/vagrant/code/payumdibs/vendor/payum/core/Payum/Core/Exception/RequestNotSupportedException.php
> on line 57

I've used x-debug and figured out that when CaptureAction::supports is called $request->getModel() is not an instance of \ArrayAccess and therefore returns false.

When using the standard payment gateways everything works fine, but using a custom does not.

My config:

    $payum = (new PayumBuilder())
    		->addDefaultStorages()
    		->addGatewayFactory('paypal', new \Acme\Paypal\PaypalGatewayFactory([]))
    		->addGateway('offline', [
    			'factory' => 'offline',
    		])->addGateway('paypal', [
    			'factory' => 'paypal',
    			'sandbox' => true,
    		])->getPayum();

Anyone have any ideas whats going wrong?

**Comment by makasim** [comment]
The core factory, one created by the builder is not injected to your gateway factory. This is the root of the problem. Because of that the storages and their extensions are not added to your gateway.

Solution: The fix in the master, so you have to upgrade to the latest version first. After you'll be able to add your gateway factory like this:

```php
<?php

$payum = (new PayumBuilder())
    ->addGatewayFactory('paypal', function(array $config, GatewayFactoryInterface $coreGatewayFactory) {
        return new \Acme\Paypal\PaypalGatewayFactory($config, $coreGatewayFactory)
    })

    // ... 
   ->getPayum()
;
```

**Comment by henriksjodahl** [comment]
Works great, thanks!

**Comment by krinkel** [comment]
@makasim i think it is the same reason of my problem but i use laravel package and payex getway, and i tried this fix but i got the same error every time:
https://github.com/Payum/PayumLaravelPackage/issues/40

**Comment by KirbyFox** [comment]
@makasim Please could you tell me where I add the following code to register a WorldPay gateway within my Sylius website?

`<?php

$payum = (new PayumBuilder())
    ->addGatewayFactory('paypal', function(array $config, GatewayFactoryInterface $coreGatewayFactory) {
        return new \Acme\Paypal\PaypalGatewayFactory($config, $coreGatewayFactory)
    })

    // ... 
   ->getPayum()
;`

**Comment by makasim** [comment]
@KirbyFox https://github.com/makasim/PayumBundleSandbox/blob/23200c1aab156eef0f7c1e3f2373ab7414dce27e/app/config/payum.yml#L217

**Comment by KirbyFox** [comment]
Thanks for the quick response @makasim 

So I add it to the build() function within https://github.com/Payum/Core/blob/master/Bridge/Symfony/Builder/CoreGatewayFactoryBuilder.php

Isn't that likely to get overwritten when I run composer update in future?

Thank you for your help. Been struggling with this for six days.

**Comment by KirbyFox** [comment]
@makasim The payum.yml file within Sylius looks nothing like the one you linked above. 

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/config/routing/payum.yml

So confusing.

I only want to use WorldPay within my Sylius website. :-(

**Comment by makasim** [comment]
your link is to **routing** payum.yml file and indeed it is completely different stuff. You need a file where you can define your DI services. it could be `app/config/config.yml` or similar.

**Comment by KirbyFox** [comment]
Thanks @makasim I've added the following to my <code>app/config/config.yml</code> and I still get "Gateway "worldpay" does not exist."

<code>
payum:
    gateways:
        paypal_express_checkout:
            factory: paypal_express_checkout
            payum.http_client: "@sylius.payum.http_client"
            username: TEST
            password: TEST
            signature: TEST
            sandbox: true
        credit_card:
            factory: stripe_checkout
            secret_key: EDITME
            publishable_key: EDITME
            payum.template.layout: SyliusShopBundle::Checkout/layout.html.twig
            payum.template.obtain_token: SyliusPayumBundle::Action/Stripe/obtainCheckoutToken.html.twig
        worldpay_checkout:
            factory: worldpay

services:
    acme_payment.worldpay.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Payum\Worldpay\WorldpayGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: worldpay }
</code>

**Comment by makasim** [comment]
@KirbyFox have you cleaned the cache?

**Comment by KirbyFox** [comment]
Yes @makasim I'm clearing it before every attempt. Thanks.
