### ISSUE TITLE
[doc] Examples Index: all links broken

### ISSUE THREAD

**Issue by vercotux** [Payum/Payum#455]
>The server returned a "404 Not Found".

Both for [1.1](http://payum.org/doc/1.1/Core/examples/index) and [1.0](http://payum.org/doc/1.0/Core/examples/index).

**Comment by makasim** [comment]
Yes, I know, I dont have time to fix it.

**Comment by makasim** [comment]
Thanks for reporting it though. The examples (as the rest of the doc) are stored in this repository here: https://github.com/Payum/Payum/tree/master/src/Payum/Core/Resources/docs/examples

**Comment by vercotux** [comment]
Thank you.

Are they up to date? I am looking at the [get it started](http://payum.org/doc/1.1/Core/get-it-started) page and have noticed some methods do not exist anymore (for example there does not seem to be a *addGatewayConfig* method in the current builder).

**Comment by makasim** [comment]
Pretty much up to date. Regarding `addGatewayConfig` method. It is typo in the doc. It must be `addGateway` method.
