### ISSUE TITLE
Use paragonie/random_compat to generate secured hashes. 

### ISSUE THREAD

**Issue by makasim** [Payum/Payum#457]
https://packagist.org/packages/paragonie/random_compat

**Comment by paragonie-scott** [comment]
Since you're using defuse/php-encryption, this should already be loaded as a dependency.

https://github.com/Payum/Payum/blob/fd6863d5aa707a5b41e775b3cbe52613b34af101/src/Payum/Core/Security/Util/Random.php#L26-L48

This should probably just be replaced to a call to `random_bytes()`.

**Comment by pierredup** [comment]
This has been implemented in #783
