### ISSUE TITLE
Cancelled PayPal payments are marked as pending

### ISSUE THREAD

**Issue by stefankleff** [Payum/Payum#462]
In commit ce3ef2f the way cancelled payments are detected has changed. But now, if you click on "cancel payment" on the paypal website, the GetBinaryStatus Command returns 1024 = pending. It looks like the isset($model['CANCELLED'])) check must be before false == $model['PAYERID']...

Here my model details after coming back from paypal:

          'NOSHIPPING' => string '1' (length=1)
          'LOGOIMG' => string 'g' (length=50)
          'PAYFLOWCOLOR' => string '470403' (length=6)
          'NOTETOBUYER' => string '' (length=24)
          'LOCALECODE' => string 'de' (length=2)
          'L_PAYMENTREQUEST_0_AMT0' => string '20.00' (length=5)
          'L_PAYMENTREQUEST_0_TAXAMT0' => string '1.40' (length=4)
          'L_PAYMENTREQUEST_0_QTY0' => string '1' (length=1)
          'L_PAYMENTREQUEST_0_NAME0' => string 'yyy' (length=19)
          'PAYMENTREQUEST_0_TAXAMT' => string '1.40' (length=4)
          'PAYMENTREQUEST_0_ITEMAMT' => string '20.00' (length=5)
          'INVNUM' => string '31144' (length=5)
          'PAYMENTREQUEST_0_CURRENCYCODE' => string 'EUR' (length=3)
          'PAYMENTREQUEST_0_AMT' => string '21.40' (length=5)
          'PAYMENTREQUEST_0_DESC' => string 'yyy' (length=16)
          'PAYMENTREQUEST_0_PAYMENTACTION' => string 'Sale' (length=4)
          'AUTHORIZE_TOKEN_USERACTION' => string 'commit' (length=6)
          'RETURNURL' => string 'http://xxx/' (length=72)
          'CANCELURL' => string 'http://xxxh?cancelled=1' (length=84)
          'PAYMENTREQUEST_0_NOTIFYURL' => string 'http://xxx' (length=71)
          'TOKEN' => string 'EC-6K343159N9783733H' (length=20)
          'TIMESTAMP' => string '2016-01-26T13:54:39Z' (length=20)
          'CORRELATIONID' => string 'cf20396f68edd' (length=13)
          'ACK' => string 'Success' (length=7)
          'VERSION' => string '65.1' (length=4)
          'BUILD' => string '18308778' (length=8)
          'BILLINGAGREEMENTACCEPTEDSTATUS' => string '0' (length=1)
          'CHECKOUTSTATUS' => string 'PaymentActionNotInitiated' (length=25)
          'CURRENCYCODE' => string 'EUR' (length=3)
          'AMT' => string '21.40' (length=5)
          'ITEMAMT' => string '20.00' (length=5)
          'SHIPPINGAMT' => string '0.00' (length=4)
          'HANDLINGAMT' => string '0.00' (length=4)
          'TAXAMT' => string '1.40' (length=4)
          'DESC' => string 'yyyy' (length=16)
          'NOTIFYURL' => string 'http://xxx' (length=71)
          'INSURANCEAMT' => string '0.00' (length=4)
          'SHIPDISCAMT' => string '0.00' (length=4)
          'L_NAME0' => string 'yyyy' (length=19)
          'L_QTY0' => string '1' (length=1)
          'L_TAXAMT0' => string '1.40' (length=4)
          'L_AMT0' => string '20.00' (length=5)
          'L_ITEMWEIGHTVALUE0' => string '   0.00000' (length=10)
          'L_ITEMLENGTHVALUE0' => string '   0.00000' (length=10)
          'L_ITEMWIDTHVALUE0' => string '   0.00000' (length=10)
          'L_ITEMHEIGHTVALUE0' => string '   0.00000' (length=10)
          'PAYMENTREQUEST_0_SHIPPINGAMT' => string '0.00' (length=4)
          'PAYMENTREQUEST_0_HANDLINGAMT' => string '0.00' (length=4)
          'PAYMENTREQUEST_0_INSURANCEAMT' => string '0.00' (length=4)
          'PAYMENTREQUEST_0_SHIPDISCAMT' => string '0.00' (length=4)
          'PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED' => string 'false' (length=5)
          'L_PAYMENTREQUEST_0_ITEMWEIGHTVALUE0' => string '   0.00000' (length=10)
          'L_PAYMENTREQUEST_0_ITEMLENGTHVALUE0' => string '   0.00000' (length=10)
          'L_PAYMENTREQUEST_0_ITEMWIDTHVALUE0' => string '   0.00000' (length=10)
          'L_PAYMENTREQUEST_0_ITEMHEIGHTVALUE0' => string '   0.00000' (length=10)
          'PAYMENTREQUESTINFO_0_ERRORCODE' => string '0' (length=1)
          'CANCELLED' => boolean true

**Comment by makasim** [comment]
Are you sure you tagged the commit (where it was changed) correctly? It looks like there is a change in doc file only.

**Comment by stefankleff** [comment]
Sorry! It is 88c6b32e43903cf857923ba95c0b72d35c856d9b

**Comment by makasim** [comment]
Looks like you are right. Do you have time to roll the fix out?

/cc @tumbochka

**Comment by stefankleff** [comment]
What do you mean with "roll the fix out"? Should I test the fix, write a PR with the fix or wait, till you fix it? ;)

**Comment by makasim** [comment]
work on PR, sorry

**Comment by makasim** [comment]
@stefankleff were you able to work on it?
