### ISSUE TITLE
ConvertPaymentAction division problem

### ISSUE THREAD

**Issue by nickworker** [Payum/Payum#465]
Hello.
When I pass data as array everything look fine

          'PAYMENTREQUEST_0_CURRENCYCODE' => string 'USD'
          'PAYMENTREQUEST_0_AMT' => float 5.28
          'NOSHIPPING' => int 1
          'REQCONFIRMSHIPPING' => int 0
          'L_PAYMENTREQUEST_0_AMT0' => float 2.64
          'L_PAYMENTREQUEST_0_QTY0' => int 2

But When I pass it like object i got division issue

         'PAYMENTREQUEST_0_CURRENCYCODE' => string 'USD'
         'PAYMENTREQUEST_0_AMT' => float 0.05

As You can see, the problem is PAYMENTREQUEST_0_AMT divided by 100

**Comment by makasim** [comment]
You have to set the price as [an integer](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/PaymentInterface.php#L30) when the Payment model is used. It must also be in cents so for example if want to pay 5.28 USD it must be 528 int.

Payum does the rest.

**Comment by makasim** [comment]
When you use payment specific format you are on your own and you have to pass everything as Paypal wants it.

**Comment by nickworker** [comment]
Ok, Thanks
