### ISSUE TITLE
Symfony 3.0.x URL generator issue

### ISSUE THREAD

**Issue by dbykadorov** [Payum/Payum#467]
In Symfony 3.0 I'm experienced an issue with UrlGenerator, used by Payum to generate absolute URLs. Lets see an example (mostly same as in documentation):

```php
            $payment = $storage->create();
            $payment->setNumber(uniqid("", true));
            $payment->setCurrencyCode("EUR");
            $payment->setTotalAmount($amount * 100); // Amount in cents
            $payment->setDescription("DEMO CHECKOUT");
            $payment->setClientId($customer->getId());
            $payment->setClientEmail($customer->getEmail());

            $storage->update($payment);
            $tokenFactory = $this->get("payum.security.token_factory");
            $captureToken = $tokenFactory->createCaptureToken(
                $gatewayName,
                $payment,
                "application_frontend_payment_done"
            );
```

This code works perfectly with Symfony 2.8, but fails in 3.0 because now UrlGenerator does not support `$absolute = true` for absolute URLs. Since 2.7 (I'm not sure, maybe since 2.6) UrlGenerator::generate() method have 3rd parameter as INT, not BOOL:

```php
// var/cache/dev/classes.php (near line 880 in my case)
public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
```

But in the Payum code still used old form `$absolute = true`. This will be ok for symfony <= 2.8 because doGenerate method support it:

```php
protected function doGenerate($variables, $defaults, $requirements, $tokens, $parameters, $name, $referenceType, $hostTokens, array $requiredSchemes = array())
{
if (is_bool($referenceType) || is_string($referenceType)) {
@trigger_error('The hardcoded value you are using for the $referenceType argument of the '.__CLASS__.'::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead.', E_USER_DEPRECATED);
if (true === $referenceType) {
$referenceType = self::ABSOLUTE_URL;
} elseif (false === $referenceType) {
$referenceType = self::ABSOLUTE_PATH;
} elseif ('relative'=== $referenceType) {
$referenceType = self::RELATIVE_PATH;
} elseif ('network'=== $referenceType) {
$referenceType = self::NETWORK_PATH;
}
```

The following code did the trick:

```php
if (true === $referenceType) {
$referenceType = self::ABSOLUTE_URL;
}
```

and Payum can generate absolute URLs. 

But in the symfony 3.0 UrlGenerator::doGenerate() method evaluates true to the 1, that equals to `const ABSOLUTE_PATH = 1`

So, all urls generated as absolute paths. So I have an error: `Unable to generate a URL for the named route "/app_dev.php/account/demo-payment-done/?payum_token=mB0JNULi-J_DxpsZxlKCjCVPO4WOjHlZlwu6v4KNYIg" as such route does not exist.` because Payum check presence of 'http' on the start of the url, else it will be interpreted as route and will throw an error:

http://prntscr.com/a0njf6

OK, in this case I can genrate absolute url manually:

```php
            $afterPath = $this->generateUrl("application_frontend_payment_done", [], UrlGeneratorInterface::ABSOLUTE_URL);
            $storage->update($payment);
            /** @var GenericTokenFactory $tokenFactory */
            $tokenFactory = $this->get("payum.security.token_factory");
            $captureToken = $tokenFactory->createCaptureToken(
                $gatewayName,
                $payment,
                $afterPath
            );
```

but now CaptureAction will fails: "The given URL: ///app_dev.php/payment/capture/uogqGPAcR4Kz4H1ORRIpeG2fx6gjNmtbdP4qwzGU0-M could not be parse"

http://prntscr.com/a0opbe

For now I'm looking workaround for this issue, but the fix would be appreciated.

Sorry for long description =\

**Comment by makasim** [comment]
What version of payum/payum are you using? Similar issue has been fixed in the master recently.

**Comment by makasim** [comment]
> Sorry for long description =\

TIP: In this case It is faster to do the fix himself than to write such a big issue

**Comment by dbykadorov** [comment]
Now I'm have a workarround by decorating routing service )

My env:


```
// composer.json
    "require": {
        ...
        "payum/payum-bundle": "^1.0",
        "payum/paypal-express-checkout-nvp": "^1.1",
       ...
    }
    "minimum-stability": "dev",
    "prefer-stable": false
```

```
// composer.lock
            "name": "payum/payum-bundle",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/Payum/PayumBundle.git",
                "reference": "114a12559505b7a5e9eb15cfa1f566a9d3c1638a"
            },
```

**Comment by dbykadorov** [comment]
Sorry, I cant find payum/payum version by quickly grepping installed files. Where it must be?

**Comment by makasim** [comment]
You have to use 1.2 (has not been released yet), it is the current dev version.

Change this "payum/paypal-express-checkout-nvp": "^1.1" to "payum/payum": "1.2@dev"

And more note: try to avoid "minimum-stability": "dev" usage as much as possible.

**Comment by dbykadorov** [comment]
@makasim thank you!
