### ISSUE TITLE
Where goes RecurringPaymentDetails

### ISSUE THREAD

**Issue by nickworker** [Payum/Payum#470]
In old version of the paypal a saw 
https://github.com/Payum/PaypalExpressCheckoutNvp/blob/0.5/src/Payum/Paypal/ExpressCheckout/Nvp/Model/RecurringPaymentDetails.php

Why it removed? And Will be in new versions?

Thanks.

**Comment by makasim** [comment]
Oh, pretty old version.... That model will be removed completely (I found it not so useful).  Instead you have to use ArrayObject model and configure fields yourself, or you can use brand new Payment model which is abstract details for most common cases.

I'd suggest you to instal the latest version at once and re code the integration. There were a lot of changes so far: https://github.com/Payum/Payum/blob/master/UPGRADE.md

And it is nightmare to upgrade from 0.5 to 1.0
