### ISSUE TITLE
GetRecurringPaymentsProfileDetails without update

### ISSUE THREAD

**Issue by nickworker** [Payum/Payum#472]
Hello!

It's possible to GetRecurringPaymentsProfileDetails without update in Db?

Did not found in documentation.

Thanks.

**Comment by makasim** [comment]
There is not a simple solution. What the problem with update?

**Comment by nickworker** [comment]
I need just api result without any updates

**Comment by makasim** [comment]
So than you should not use the model for which you registed the storage, for example if you use Payment model do not pass it directly but take details (it is an array), wrap them by ArrayObject instance and use with the request.
