### ISSUE TITLE
How to get tokenFactory in actions

### ISSUE THREAD

**Issue by BoShurik** [Payum/Payum#474]
Hello,

I am developing gateway and can't figure out how to get tokenFactory to generate a redirect url for gateway API.

I've implemented `GenericTokenFactoryAwareInterface`, but tokenFactory is always `null`

Thank you!

**Comment by makasim** [comment]
You have to make sure that the [token factory extension](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Extension/GenericTokenFactoryExtension.php) is added to your gateway. Usually it is done behind the scene if you use a builder of course:  https://github.com/Payum/Payum/blob/master/src/Payum/Core/PayumBuilder.php#L395
