### ISSUE TITLE
RequestNotSupportedException: Request Capture{model: Identity}

### ISSUE THREAD

**Issue by henriksjodahl** [Payum/Payum#479]
I've seen this issue previously but the solution on those issues have not solved my issue.
(i'm using the LaravelPackage)

My ServiceProvider:
```
App::resolving('payum.builder', function(PayumBuilder $payumBuilder) {

	$payumBuilder
		->addDefaultStorages()
		->addGatewayFactory('offline', new OfflineGatewayFactory([
			"extension" => (new StorageExtension(new EloquentStorage(Payment::class)))
		]))
		->addGatewayFactory('klarna_checkout', new KlarnaCheckoutGatewayFactory([
			"extension" => (new StorageExtension(new EloquentStorage(Payment::class)))
		]))
		->addGateway('offline',[
			'factory' => 'offline',
		])
		->addGateway('klarna_checkout', [
			'factory'     => 'klarna_checkout',
			'merchant_id' => '',
			'secret'      => '',
			'sandbox'     => true,
			'terms_uri'   => '',
		])
		->setTokenStorage(new EloquentStorage(PaymentToken::class))
		->addStorage(Payment::class, new EloquentStorage(Payment::class))
	;
});
```

The error i'm getting on page {redacted}/capture/FbdaKzTYYPRqTrr5QBi4z5l7G1KENdwqNhAwNk4MZzM" is:

> RequestNotSupportedException in RequestNotSupportedException.php line 57:
Request Capture{model: Identity} is not supported. Make sure the storage extension for "Modules\Order\Entities\Payment" is registered to the gateway. Make sure the storage find method returns an instance by id "6". Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.

The token is created in DB with the hash above.
A payment is created in database in the payment-table with id 6.

I get the same error using both offline and klarna_checkout gateways.

**Comment by makasim** [comment]
Why do you add storage extension manually? they should be registered automatically. I dont think you have to use `addDefaultStorages` method.

**Comment by makasim** [comment]
You should not also register the gateway factories, the standard factories are already there

**Comment by henriksjodahl** [comment]
Alright, i've made som changes to the ServiceProvider. Still getting the same exception though
```
App::resolving('payum.builder', function(PayumBuilder $payumBuilder) {
	$payumBuilder
		->addGateway('offline',[
			'factory' => 'offline',
		])
		->addGateway('klarna_checkout', [
			'factory'     => 'klarna_checkout',
			'merchant_id' => 'test',
			'secret'      => 'test',
			'sandbox'     => true,
			'terms_uri'   => '',
		])
		->setTokenStorage(new EloquentStorage(PaymentToken::class))
		->addStorage(Payment::class, new EloquentStorage(Payment::class))
	;
});
```

**Comment by henriksjodahl** [comment]
Okey, i changed my ServiceProvider and removed the overhead stuff:
```
App::resolving('payum.builder', function(PayumBuilder $payumBuilder) {

    $payumBuilder
        ->addGateway('offline',[
            'factory' => 'offline',
        ])
        ->addGateway('klarna_checkout', [
            'factory'     => 'klarna_checkout',
            'merchant_id' => '',
            'secret'      => '',
            'sandbox'     => true,
            'terms_uri'   => '',
        ])
        ->setTokenStorage(new EloquentStorage(PaymentToken::class))
        ->addStorage(Payment::class, new EloquentStorage(Payment::class))
    ;
});
```
And that made it work. I guess i made a mess of things :) Thank you for the help.
