### ISSUE TITLE
[question] Klarna Checkout Confirmation

### ISSUE THREAD

**Issue by henriksjodahl** [Payum/Payum#481]
Just a quick question, is there built in support for the mandatory Klarna Checkout confirmation page in the klarna checkout gateway somehow?
Documentation: https://developers.klarna.com/en/se+php/kco-v2/checkout/3-show-confirmation
Or should i use the klarna api for that?

**Comment by makasim** [comment]
You can use payum to retrieve the details (especially the snippet), but the
page has to be designed by yourself as it app specific.

On the confirmation step (the payment done in payum terms) do the status
check, and if it is authorized do the sync request and get the snippet from
the details and show it on the page.

**Comment by henriksjodahl** [comment]
Great, that snippet is really all i need. Do you have an existing example of how to retrieve the external order data?

**Comment by makasim** [comment]
```php
<?php
$gateway->execute(new Sync($payment));

$payment['gui']['snippet'];

// or

$payment->getDetails()['gui']['snippet'];
```

**Comment by henriksjodahl** [comment]
Works like a charm
