### ISSUE TITLE
Include Klarna Checkout in view

### ISSUE THREAD

**Issue by robbens** [Payum/Payum#484]
So far, everything has been a breeze setting up and it works as expected.

But I can't seem to understand how to include the actual Klarna Checkout iframe inside my own views.
At this point, I get redirected to `http://localhost/payment/authorize/{token_here}`

    $storage = $this->getPayum()->getStorage('Payum\Core\Model\ArrayObject');

    $details = $storage->create();
    $details['purchase_country'] = 'SE';
    $details['purchase_currency'] = 'SEK';
    $details['locale'] = 'sv-se';
    $storage->update($details);

    $authorizeToken = $this->getPayum()->getTokenFactory()->createAuthorizeToken('klarna', $details, 'payment_done');
    $notifyToken = $this->getPayum()->getTokenFactory()->createNotifyToken('klarna', $details);

    $details['merchant'] = array(
        'terms_uri' => 'http://example.com/terms',
        'checkout_uri' => $authorizeToken->getTargetUrl(),
        'confirmation_uri' => $authorizeToken->getTargetUrl(),
        'push_uri' => $notifyToken->getTargetUrl()
    );

    $cart = array(
        array(
            'reference' => '123456789',
            'name' => 'Klarna t-shirt',
            'quantity' => 2,
            'unit_price' => 12300,
            'discount_rate' => 1000,
            'tax_rate' => 2500
        ),
        array(
            'type' => 'shipping_fee',
            'reference' => 'SHIPPING',
            'name' => 'Shipping Fee',
            'quantity' => 1,
            'unit_price' => 4900,
            'tax_rate' => 2500
        )
    );

    $details['cart'] = array(
        'items' => $cart
    );

    $storage->update($details);

    $details = $storage->create();
    $details['PAYMENTREQUEST_0_CURRENCYCODE'] = 'SEK';
    $details['PAYMENTREQUEST_0_AMT'] = 1.23;
    $storage->update($details);

    return \Redirect::to($authorizeToken->getTargetUrl());

Big thumbs up to the creators!

**Comment by makasim** [comment]
Just overwrite the tempalte, or layout If you are fine with an extra page. If not execute authorize request manually. grab snippet from it and include to your page.

**Comment by robbens** [comment]
Yeah I need the snippet.

I'm actually totally lost right now. Just started learning Laravel.

`HttpResponse in AuthorizeAction.php line 119:`

    public function authorize(Request $request, $token)
    {
        $payum_token = $token;
        $request->attributes->set('payum_token', $payum_token);

        $token = $this->getPayum()->getHttpRequestVerifier()->verify($request);
        $gateway = $this->getPayum()->getGateway($token->getGatewayName());

        $gateway->execute($status = new Authorize($token));

        dd($status);
    }

**Comment by robbens** [comment]
So this works now. Tell me if something is off :smile: 

    public function authorize(Request $request, $payum_token)
    {
        $request->attributes->set('payum_token', $payum_token);

        $token = $this->getPayum()->getHttpRequestVerifier()->verify($request);
        $gateway = $this->getPayum()->getGateway($token->getGatewayName());

        try {
            $gateway->execute($status = new Authorize($token));
        } catch (ReplyInterface $reply) {
            return \Response::json(array(
                'details' => iterator_to_array($status->getFirstModel())
            ));
        }

        $this->getPayum()->getHttpRequestVerifier()->invalidate($token);
    }


Also made my own redirect.
`Route::get('/payment_authorize/{token}', ['as' => 'payum_authorize_do', 'uses' => 'KlarnaController@authorize']);`

**Comment by makasim** [comment]
I am not sure you have to expose all the details here `'details' => iterator_to_array($status->getFirstModel())` just send what you need in the client.

And you dont need to overwrite the controller, it is better to do with a payum extension.

**Comment by robbens** [comment]
Thanks! I'll look into creating an extension right away.
