### ISSUE TITLE
What is the proper way to check payment status?

### ISSUE THREAD

**Issue by BoShurik** [Payum/Payum#485]
Hello
Where should I process user's order after payment is captured? In my case payment system send me notification via NotifyAction, so I cant process it in doneAction, like documentation said.
I've done this via doctrine listener:
```php
/**
     * @param LifecycleEventArgs $event
     */
    public function postUpdate(LifecycleEventArgs $event)
    {
        $entity = $event->getEntity();
        if (!$entity instanceof Payment) {
            return;
        }

        /** TODO: GetStatusAction */
        $details = $entity->getDetails();
        if ($details['status'] != 'captured') {
            return;
        }

        /** @var User $user */
        $user = $this->userRepository->find($entity->getClientId());
        $this->balanceManager->inc($user, $entity->getTotalAmount());
    }
```
but I don't think it is a good idea to rely on payment details. I suppose I need to call GetStatusAction, but how to do it without a token?

**Comment by BoShurik** [comment]
Should i do this from extension, like here: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php?

**Comment by makasim** [comment]
Yes, the payum extension is the way to go.
