### ISSUE TITLE
Better documentation for CustomStorage?

### ISSUE THREAD

**Issue by iadj** [Payum/Payum#487]
Currently, the documentation for integrating our own Storage model is only this:

    <?php
    use Payum\Core\Storage\StorageInterface;
    
    class CustomStorage implements StorageInterface 
    {
      // implement all declared methods
    }

I don't see an example or documentation for what the 'declared methods to implement' are. I have no idea where to go from this example.

**Comment by makasim** [comment]
You have to implement the [StorageInterface](http://www.maranello.kharkov.ua/pizzerii-restorani/). The interface declares some methods to be implemented, right? I believe the interface methods are self descriptive enough.

If you need some inspirations look at some implementations of the interface, like filesystem storage, doctrine storage, propel storage etc.

If you still think the doc could be improved, send a PR.

**Comment by iadj** [comment]
@makasim Thanks. I assume you meant to link to the StorageInterface file. I pizzerias though :D
