### ISSUE TITLE
Replace Guzzle6 with HTTPlug

### ISSUE THREAD

**Issue by Nyholm** [Payum/Payum#491]
I order to remove the dependency on Guzzle I suggest we use [Httplug](http://docs.php-http.org/en/latest/) instead. This way we can let our users to still use Buzz, Guzzle5, Curl or whatever they want. 

Im happy to send a PR if you think this idea is worth considering.

**Comment by makasim** [comment]
Do you suggest to change this https://github.com/Payum/Payum/blob/master/src/Payum/Core/HttpClientInterface.php  with the one from Httplug. What benefits it gives us?

Do you see a BC way to migrate to Httplug?

There must a default http adapter which comes with payum so things works out of the box. Currently it is guzzle. what would it be if we migrate to httplug

**Comment by Nyholm** [comment]
Thank you for reviewing this. 

We do not have to replace that Interface now. But that should preferably be done when you go to 2.0. I can use a HttplugClient the same way as you use the Guzzle client (wrapped into an adapter object).

The benefit that this give you it that users that are stuck with Guzzle5 will be able to use this library. And also when (if) Guzzle7 comes out you do not need to care. (Which is a good thing, we are doing payment not http messaging). 

> Do you see a BC way to migrate to Httplug?

I think so. Im not too sure how why [this](https://github.com/Payum/Payum/blob/master/src/Payum/Core/CoreGatewayFactory.php#L65) is needed. That would obviously not be there anymore. 

> There must a default http adapter which comes with payum so things works out of the box. Currently it is guzzle. what would it be if we migrate to httplug

This is the thing, no it must not. This is the D in SOLID, Dependency Inversion principle. Payum should not be tightly coupled to **any** http messaging provider. It should depend on an abstraction. We will however require the virtual package [php-http/client-implementation](https://packagist.org/providers/php-http/client-implementation) which forces the user to choose an implementation of their own or composer will complain. 

One other change, In order for us to know which HttpClient the user want to use we must pass the client or fallback on auto discovery. 

Passing the client might look like this: 
```php
/** @var Payum $payum */
$payum = (new PayumBuilder())
    ->addDefaultStorages()
    ->addGateway('gatewayName', [
        'factory' => 'aGateway'
        'httplug_client' => new \Http\Adapter\Guzzle6\Client(),
    ])
    ->getPayum()
;
```

We will fallback on discovery. That uses Puli to find the proper class. I would suggest writing something like this in the `CoreGatewayFactory`. 

```php
if (!isset($config['httplug_client'])) {
   $config['httplug_client'] = HttpClientDiscovery::find();
}
```

If you do not provide a HttpClient nor have Puli installed to use the discovery you will get an Exception saying that no clients were found.

**Comment by makasim** [comment]
Okay, let's do it.
