### ISSUE TITLE
A lot of warnings in composer

### ISSUE THREAD

**Issue by cmarfil** [Payum/Payum#498]
Hello,

Thanks but this library gives a little scary..

![image](https://cloud.githubusercontent.com/assets/798849/13845862/13ca9e76-ec43-11e5-8284-0e537315abe8.png)

It's normal?

Regards,

**Comment by makasim** [comment]
What does scare you? This what library [suggest to install](https://github.com/Payum/Payum/blob/master/composer.json#L85). If you do not need anything from that list just ignore it.

**Comment by cmarfil** [comment]
Ok, I'll try, thanks!

**Comment by makasim** [comment]
You can also install a specific package like payum/stripe.
