### ISSUE TITLE
Is there any way to ommit convert action?

### ISSUE THREAD

**Issue by skornev** [Payum/Payum#502]
I am trying to implement a new gateway.  Everything is fine except that if I comment 
```

class AcmeGatewayFactory extends GatewayFactory

{

    protected function populateConfig(ArrayObject $config)
    {
        $config->defaults(array(

          //  'payum.action.convert' => new ConvertPaymentAction(
         )
       );
   }
 ...
}
```

I get 

> Request Convert is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker. 

Is it a normal behavior or a bug?
If it's not a bug and I dont' need any conversion. Does it mean that  all I  need  is just to pass request to  the next action, do I?
Also where can I get  the  list and the order of other actions executed ? This moment is not clear for me from documentation. From the docs I learned that there is a capture action that should decide pass or not the request next, but now this moment is not obvious for me.

**Comment by makasim** [comment]
Could you provide some details about your context:

* Do you use any frameworks?
* What model do you use Payment or ArrayObject, custom one?
* Payum config 
* Other info you may find useful

**Comment by skornev** [comment]
Sure.

- I use Symfony 3. 
- I use custom Payment model. 
```
/**
 * @ORM\Table
 * @ORM\Entity
 */
class Payment extends BasePayment
{
    use TimestampableTrait;
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     *
     * @var integer $id
     */
    protected $id;
}
```
- there is not much anything special in the config
  $config->defaults(array(
            'payum.factory_name' => 'acme_payment_factory',
            'payum.factory_title' => 'ACME payment',
            'payum.action.capture' => new CaptureAction(),
            'payum.action.status' => new StatusAction(),
//            'payum.action.convert' => new ConvertPaymentAction(),
        ));

**Comment by skornev** [comment]
There is the same issue with offline gateway

```
class OfflineGatewayFactory extends GatewayFactory
{
    /**
     * {@inheritDoc}
     */
    protected function populateConfig(ArrayObject $config)
    {
        $config->defaults([
            'payum.factory_name' => 'offline',
            'payum.factory_title' => 'Offline',
            'payum.action.capture' => new CaptureAction(),
            'payum.action.authorize' => new AuthorizeAction(),
            'payum.action.status' => new StatusAction(),
            //'payum.action.convert_payment' => new ConvertPaymentAction(),
        ]);
    }
}
```

> Request Convert is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.

**Comment by makasim** [comment]
Well Payum works with an array format and only understands it, If you want to use any other type of models (such as Payment object) you have to provide a converter to an array format (gateway specific).
