### ISSUE TITLE
Fatal Error Class CreditCardExpirationDateType

### ISSUE THREAD

**Issue by Nexyssify** [Payum/Payum#517]
Hello, 

I have some error when I try to do a "composer.phar update" or et "cache:clear".

My message is : 
"Fatal error: Class Payum\Core\Bridge\Symfony\Form\Type\CreditCardExpirationDateType contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Form\FormTypeInterface::getName) in ...\vendor\payum\core\Payum\Core\Bridge\Symfony\Form\Type\CreditCardExpirationDateType.php on line 54" 

Do you have any ideas ? 

Thank you.

**Comment by makasim** [comment]
What version of symfony are you using?

**Comment by makasim** [comment]
What version of payum you had and what is it after update?

**Comment by Nexyssify** [comment]
I use the 2.7. 

And for payum : 
payum/core                                           1.2.8              
payum/iso4217                                      1.0.0              
payum/offline                                         1.2.0              
payum/paypal-express-checkout-nvp    1.2.0             
payum/payum-bundle                             1.0.3

**Comment by makasim** [comment]
Payum require symfony 2.8 or higher https://github.com/Payum/Core/blob/master/composer.json#L56

**Comment by Nexyssify** [comment]
Ok sorry, Since when ? Because I take a project.

**Comment by makasim** [comment]
Since 1.2. I was not able to do it BC way because I already announced symfony 3.0 support and later find out that it is not possible to supoprt 2.7,2.8 and 3.0. Either 2.7 or 2.8,3.0

**Comment by makasim** [comment]
https://github.com/Payum/Payum/blob/master/CHANGELOG.md#120-2016-02-12

**Comment by Nexyssify** [comment]
Ok Thank's

**Comment by Nexyssify** [comment]
Hi again, sorry I have question because I can't update Symfony for some resons of dependecies of my project. So I want to know if it possible to installe a lower version of Payum ? 
I use this parameters in my composer : 
        "payum/payum-bundle": "^1.0",
        "payum/offline": "^1.0",
        "payum/paypal-express-checkout-nvp": "^1.0",

But I have this version instal with "composer.phar update" : 
         payum/core 1.2.8
         payum/iso4217 1.0.0
         payum/offline 1.2.0
         payum/paypal-express-checkout-nvp 1.2.0

Thank's.

**Comment by makasim** [comment]
Yes you can always install a lower version by explicitly setting them. Like 

```
payum/payum-bundle 1.1.*
payum/core 1.1.*
payum/iso4217 ^1
payum/offline ^1.1.*
payum/paypal-express-checkout-nvp 1.1.*
```

or similar things

**Comment by Nexyssify** [comment]
Ok thank's. It worded. I juste forget to force the payum/core.
