### ISSUE TITLE
How to implement PayPal Payment with PayPal Pro

### ISSUE THREAD

**Issue by wataruoguchi** [Payum/Payum#519]
Hi,
Thank you for developing such a great bundle.

Here I'm trying to implement PayPal Pro feature on my Sympfony2 web app.
My goal is to having 2 ways of payments both credit card payment and PayPal payment on the same page [like this image](https://www.paypalobjects.com/webstatic/en_US/mktg/caImages/3_Pro_CustomersSeeModule_Step3.png).
I got to integrate credit card payment following [this tutorial](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ProCheckout/Nvp/Resources/docs/get-it-started.md), but have no idea how to implement the PayPal Payment button on the same page.
Would you please tell me how to do that please?

Thank you in advance.

**Comment by makasim** [comment]
You have to create a form type with a credit card fields (you can reuse Payum's [CreditCardType](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Symfony/Form/Type/CreditCardType.php)). Once the form is submitted you have to check whether it has credit card set or not, If set you use one paypal pro account if not you fallback to paypal express.
