### ISSUE TITLE
Using Httplug instead of Guzzle6 #505

### ISSUE THREAD

**Issue by juvabien** [Payum/Payum#534]
Could you write a sample implementation in the documentation ?
I have difficulties to instantiate the second argument of a call via the API :

[http://stackoverflow.com/questions/36829937/payum-httpclientinterface-not-given-in-argument-2-passed]()

thank you

**Comment by makasim** [comment]
You are not using the gateway factory but the api directly. The API class is a low level logic and is not supposed to be used directly. It is possible but still you have to do some initialization work manually.

This is now the api is created in the factory: https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/PaypalExpressCheckoutGatewayFactory.php#L89. You can implement similar things doing something similar.
