### ISSUE TITLE
GetHttpRequest with Symfony fails on empty RequestStack

### ISSUE THREAD

**Issue by davidfuhr** [Payum/Payum#535]
The Symfony GetHttpRequestAction fails if the request stack is empty.

It would be great if you could release this as bugfix for 1.2 (so 1.2.9 at the moment). Can you create a branch (1.2) for this, than I can create the pull request.

I've created an appropriate patch for this: https://github.com/davidfuhr/Payum/commit/64b266bccfd39e77b5ca7015e10f5ee98e857d17

**Comment by makasim** [comment]
fixed since 1.2.9 and 1.3.2
