### ISSUE TITLE
Paypal Masspay errors while configuring

### ISSUE THREAD

**Issue by vdomah** [Payum/Payum#548]
Hi!

Following the masspay instructions https://github.com/Payum/Payum/pull/511.

First, I got undefined function about this string 
`$payout->setCurrenyCode('USD');`
 Just commented it and moved forward. But still the issue.

Next I got 
>A storage for model Payum\Core\Model\Payout was not registered. There are storages for next models: Payum\Core\Model\Payment, Payum\Core\Model\ArrayObject.

adding this:
`->addStorage(Payout::class, new FilesystemStorage(sys_get_temp_dir(), Payout::class))`
fixed the issue

Next:
>The path "payout" is not found. Possible paths are capture, notify, authorize, refund
Found that the paths are defined here: https://github.com/Payum/Payum/blob/master/src/Payum/Core/PayumBuilder.php#L386

But I don't see a way to add path for payout except of directly insert it in the package code. How to set $this->genericTokenFactoryPaths ?

**Comment by makasim** [comment]
Hm, it has to be added to the library as it is part of the core, like capture or authroize, as a workaround for now you can try:

$builder->setGenericTokenFactoryPaths(['payout' => 'payout.php'])

**Comment by makasim** [comment]
addDefaultStorages - has to register a storage for Payout model too

**Comment by vdomah** [comment]
$builder->setGenericTokenFactoryPaths(['payout' => 'payout.php']); helped, thanks!

But
addDefaultStorages() doesn't register payout:

> public function addDefaultStorages()
 {
        $this
            ->setTokenStorage(new FilesystemStorage(sys_get_temp_dir(), Token::class, 'hash'))
            ->addStorage(Payment::class, new FilesystemStorage(sys_get_temp_dir(), Payment::class, 'number'))
            ->addStorage(ArrayObject::class, new FilesystemStorage(sys_get_temp_dir(), ArrayObject::class));
        return $this;
}

But it's ok - manualy calling addStorage solves.

**Comment by vdomah** [comment]
> Any suggestions about $payout->setCurrenyCode('USD'); error?
Just noticed that Curreny is without c. setCurrencyCode works fine. That's error in documentation example: https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/Masspay/Nvp/Resources/docs/get-it-started.md#configphp

also in this peace of code ',' required: https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/Masspay/Nvp/Resources/docs/get-it-started.md#configphp

but that's much easier to see

**Comment by makasim** [comment]
@vdomah try out 1.3.4 version 
https://github.com/Payum/Payum/releases
