### ISSUE TITLE
Paypal Masspay capture.php script

### ISSUE THREAD

**Issue by vdomah** [Payum/Payum#549]
Can't figure out what script should I use after getting $payoutToken in https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/Masspay/Nvp/Resources/docs/get-it-started.md#preparephp

according to general documentation it should be capture.php script like here https://github.com/Payum/Core/blob/master/Resources/docs/get-it-started.md#capturephp

Tried to implement it but not sure what to do exactly to make it work. Please point me

**Comment by makasim** [comment]
No it is not, you have to put something like this to payout.php script: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/scripts/payout-script.md

The differnce between payout script and capture script is here `$gateway->execute(new Payout($token));`

**Comment by vdomah** [comment]
Thanks! I implemented this payout script but now got another error:

> Request Payout is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.

**Comment by makasim** [comment]
Post your code please

**Comment by vdomah** [comment]
Here is the code: https://github.com/vdomah/dyna/blob/master/routes.php

It's Laravel routes.php file.With few modifications that I described in previous issue https://github.com/Payum/Payum/issues/548

**Comment by makasim** [comment]
Try to add an id field to payout model (I have to extend it) and tell the storage to use it (the third argument)

btw Why dont you use payum laravel package?

**Comment by vdomah** [comment]
Sorry, I'm not sure what you mean by 'add an id'. Extend Payout class and add id property? And telling storage to use it - by calling addStorage? But I see there already 3rd arument that is Payout::class.
Sorry if I don't see something obvious.

**Comment by makasim** [comment]
yes you have to add an id property 
and tell storage to use

```
->addStorage(Payout::class, new FilesystemStorage(sys_get_temp_dir(), Payout::class, 'id'))
```

**Comment by vdomah** [comment]
Didn't help. Same error. 

Added 'id' parameter and added this class:
    
    class Payout extends \Payum\Core\Model\Payout {

        public $id;
    }

And used it instead of original class.

**Comment by vdomah** [comment]
I've set up the same thing from scratch using Laravel Package. And now facing the same error message:

> Request Payout is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.

This code of my controller is here:
https://github.com/vdomah/dyna/blob/master/Payments.php

error appears at line 67: $gateway->execute(new Payout($token));

**Comment by makasim** [comment]
It works in the sandbox http://sandbox.payum.org/paypal/masspay/prepare. It somehow related to a storage and its extension,

so try to debug in onPreExecute method https://github.com/Payum/Payum/blob/master/src/Payum/Core/Extension/StorageExtension.php#L31

**Comment by vdomah** [comment]
Using your example found that I passed wrong class into execute method.

now execute line looks like that:
$gateway->execute($status = new GetHumanStatus($token));

So payment should be made after that, but it doesn't. After debugging I found that there are 3 actions in Masspay Nvp:
ConvertPayoutAction
GetPayoutStatusAction
PayoutAction

And only GetPayoutStatusAction fires. How to call other?

**Comment by makasim** [comment]
they must be called after you are redirected to payout controller at this line https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaymentBundle/Controller/PayoutPaypalMasspayController.php#L42

**Comment by vdomah** [comment]
I got that redirection but can't find out where to search for the place where that events are fired.
Can you help saying what to search? I tried to search for action classnames, action codes like get_payout_status, convert_payout, api.masspay.

**Comment by makasim** [comment]
here https://github.com/Payum/PayumBundle/blob/master/Controller/PayoutController.php#L15

**Comment by vdomah** [comment]
Thanks, that helped, now I see the message:

> The number of input records is less than or equal to zero

Can it be related to lines where I add payment info?


$storage = $this->getPayum()->getStorage(Payout::class);

$payment = $storage->create();

$payment->setCurrencyCode('EUR');

$payment->setRecipientEmail('firebatt-buyer@ukr.net');

$payment->setTotalAmount(123);

$storage->update($payment);

$captureToken = $this->getPayum()->getTokenFactory()->createCaptureToken($this->gatewayName, $payment, 'payoutDone');

**Comment by makasim** [comment]
Why do you create a capture token? It must be createPayoutToken one.

**Comment by vdomah** [comment]
changed to createPayoutToken, and see the same message: The number of input records is less than or equal to zero
