### ISSUE TITLE
paypal-express-checkout-nvp version ^1.3

### ISSUE THREAD

**Issue by nickworker** [Payum/Payum#553]
Attempted to load trait "GatewayAwareTrait" from namespace "Payum\Core"
on
payum/paypal-express-checkout-nvp/Payum/Paypal/ExpressCheckout/Nvp/Action/PurchaseAction.php:26

**Comment by makasim** [comment]
You need payum/core version 1.3 at least. It requires http client implementation package.

```
php composer.phar update payum/core php-http/guzzle6-adapter
```

**Comment by nickworker** [comment]
Thanks For Quick Reply
