### ISSUE TITLE
Probleme with chrome

### ISSUE THREAD

**Issue by Nexyssify** [Payum/Payum#555]
Hello, 

I have probleme do generate paypal Url on but it work good with firefox or chromium.

Do you have any ideas with my probleme ? 

Thanks.

**Comment by makasim** [comment]
The url generation has nothing to do with browser. If it works in one browser it must work in another too. 
So I guess you have another problem. Could you provide more info about your issue?

**Comment by Nexyssify** [comment]
Sorry it's my fault, I have implements multi language to my web site and due to this the format of number change and cause problemes to paypal.
