### ISSUE TITLE
How to access gateway sdk related methods

### ISSUE THREAD

**Issue by safoorsafdar** [Payum/Payum#561]
I'm trying to access authorized.net customer profile information, but i'm totally blind, how to perform such action using payum, and also unable to find any information/mechanism to access gateway sdk api related methods through payum in documentation.

Want to implement https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/get-customer-profile.php

Framework I'm using Laravel5 with payum laravel and payum authorize.net aim package.

**Comment by makasim** [comment]
Create a custom api aware action (let's say GetCustomerProfileAction), register it to the gateway, create a custom request (Let's say GetCustomerProfile) for it. 

and call $gateway->execute(new GetCustomerProfile($model));

**Comment by safoorsafdar** [comment]
Thanks for your rapid response, By reviewing the The architecture documentation, i'm trying to run full example using below code:

```
$gateway = new Gateway;
$gateway->addAction(new CaptureAction);

//CaptureAction does its job.
$gateway->execute($capture = new Capture(array(
    'amount' => 100,
    'currency' => 'USD'
)));

var_export($capture->getModel());
```

but I confused with couple of things like:
- what this code `$gateway = new Gateway;`  doing, what the namespace of this class?
- I create the sample action in my laravel5 application, and added the action as mention here, but what is the `$capture = new Capture`, mean what is the custom request?

**Comment by safoorsafdar** [comment]
by using above method i'm facing `The merchant login ID or password is invalid or the account is inactive.`

**Comment by safoorsafdar** [comment]
Thanks for your help, by reviewing the available documentation I able to develop another gateway to meet my requirement because available `AuthorizeNetAim` wasn't meeting my requirement.

but I think that would be great, if you add package api documentation. and also prepare documentation is such way package beginner understand the setup to develop without taking any assumption. 

and also I think that would be helpful to understand the package by including below in documentation:
- Request execution cycle (respective to best practices like first create storage then add data to it, I know there is already available example but it's not meet the all of scenarios in generic way)
- Component documentation individually like Action, Request, Storage with some basic information and api information. and Component relation documentation.

I hope this would help.
