### ISSUE TITLE
Access Gateway with different Factory rather than default

### ISSUE THREAD

**Issue by safoorsafdar** [Payum/Payum#562]
I have register the factory `AuthorizeNetCimGatewayFactory` with ` 'payum.factory_name' =>'authorize_net_cim',` config.
and also added the factory `payum.builder` using `->addGatewayFactory('authorize_net', new \App\AuthorizeNet\Cim\AuthorizeNetCimGatewayFactory())`

and also I added the config for available action something like:
`'payum.action.get_customer_profile' => new GetCustomerProfileAction(),`

so my question is, how I can access different registered factory action

Thanks in advance.

**Comment by makasim** [comment]
I suppose the support method of GetCustomerProfileAction looks like this 

return $request instanceof GetCustomerProfile;

If so you have to execute such request.


$gateway->execute(new GetCustomerProfile($payment));

**Comment by safoorsafdar** [comment]
Sorry, i didn't understand. I have two factory `authorize_net_cim` and `authorize_net_cim` against same gateway `authorize_net`, so how i would execute `authorize_net_cim` action rather than default factory action? or using the request its automatically call/execute appropriate action according to factory?

**Comment by safoorsafdar** [comment]
and also I didn't understand the purpose of Request classes in the whole mechanism. can you explain me little about Request class respective to app architecture?
