### ISSUE TITLE
Attempted to load trait "ApiAwareTrait"

### ISSUE THREAD

**Issue by rafikck** [Payum/Payum#564]
Hello,
I have some problem with PayPal Rest Bundle.

**Error message:**
> Attempted to load trait "ApiAwareTrait" from namespace "Payum\Core".
> Did you forget a "use" statement for another namespace?

**Stack trace:**
class CaptureAction implements ActionInterface, GatewayAwareInterface, ApiAwareInterface
{
    use ApiAwareTrait;
    use GatewayAwareTrait;
    public function __construct()

**composer.json:**
      "require": {
            "php": ">=5.3.9",
            "symfony/symfony": "2.8.*",
            "doctrine/orm": "^2.4.8",
            "doctrine/doctrine-bundle": "~1.4",
            "symfony/swiftmailer-bundle": "~2.3",
            "symfony/monolog-bundle": "~2.4",
            "sensio/distribution-bundle": "~5.0",
            "sensio/framework-extra-bundle": "^3.0.2",
            "incenteev/composer-parameter-handler": "~2.0",
            "stof/doctrine-extensions-bundle": "^1.1",
            "symfony/assetic-bundle": "^2.7",
            "stfalcon/tinymce-bundle": "1.0",
            "knplabs/knp-paginator-bundle": "dev-master",
            "payum/payum-bundle": "2.0.1",
            "payum/offline": "1.2.0",
            "payum/paypal-express-checkout-nvp": "1.2.0",
            "payum/authorize-net-aim": "1.2.0",
            "twig/extensions": "dev-master",
            "seferov/aws-bundle": "dev-master",
            "symfony/console": "dev-master",
            "rickysu/tagcache-bundle": "^0.1.3",
            "openpayu/openpayu" : "2.2.*",
            "payum/paypal-rest": "1.3.2"

Is something missing?

**Comment by makasim** [comment]
In order to use ApiAwareTrait you have to have payum versino 1.3.x at least.

Make sure you installed http client too:

php composer.phar require payum/paypal-rest php-http/guzzle6-adapter
