### ISSUE TITLE
Recurring payment cancel process issue

### ISSUE THREAD

**Issue by narendra-addweb** [Payum/Payum#565]
I was creating recurring profile using basic [guide](https://github.com/Payum/PaypalExpressCheckoutNvp/blob/master/Resources/docs/recurring-payments-basics.md). This is working fine.

Now, I want to create code for canceling that profile using [guide](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Resources/docs/cancel-recurring-payment.md). But I'm stuck here with an error message: "Invalid model given. Should be instance of Payum\Core\Model\ArrayObject but it is array".

Is there any complete example for cancel profile functionality?

Any quick help would be appreciated.

**Comment by makasim** [comment]
I've just tested in in the sandbox and worked fine. Here's the how it looks there: https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaypalExpressCheckoutBundle/Controller/RecurringPaymentExamplesController.php#L177

At first glance the code looks similar to the guide. Could you please check everything again? Cuz the code looks like working

**Comment by narendra-addweb** [comment]
Thank for quick replay.

I checked your provided example code [PayumBundleSandbox](https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaypalExpressCheckoutBundle/Controller/RecurringPaymentExamplesController.php#L177). 

Can I use this with payum bundle? If yes, how?

**Comment by makasim** [comment]
The code in the sandbox, which I use to test releases and people may use as examples. It is not expected to be used as base project or so. 

So a good way to go is to copy paste needed parts of the code to your app and adjust them to your needs.
