### ISSUE TITLE
Authorize.Net disable capture form

### ISSUE THREAD

**Issue by nash4ever** [Payum/Payum#566]
Hi,
I tried to integrate Authorize.Net payment with symfony2 framework.
I'm using the demo code:
`public function prepareAuthorizeNetPaymentAction(Request $request){
        $gatewayName = "your_gateway_name";

        $storage = $this->get('payum')->getStorage('Acme\PaymentBundle\Entity\PaymentDetails');

        /** @var \Acme\PaymentBundle\Entity\PaymentDetails $details */
        $details = $storage->create();

        $details['amount'] = 1.23;
        $details['clientemail'] = 'user@email.com';
        $details['card_Num'] = new SensitiveValue('1111222233334444');
        $details['exp_date'] = new SensitiveValue('15-11');
        $storage->update($details);

        $captureToken = $this->get('payum')->getTokenFactory()->createCaptureToken(
            $gatewayName,
            $details,
            'acme_gateway_done' // the route to redirect after capture
        );

        return $this->redirect($captureToken->getTargetUrl());
    }`

My problem is that I always get a 'payment/capture/' page, where I should set the card informations, but I would like to set these informations in a popup, 
What should I do to avoid the capture form? Is it possible to send all information in the 'prepareAuthorizeNetPaymentAction' and don't get capture page?

Thanks for your help.

**Comment by makasim** [comment]
Use forward instead of redirect. the credit card information is not stored to database that's why payum tries to get it again.

**Comment by nash4ever** [comment]
Thanks for your fast resposne, but could you help me where (which action or route) do I should forward the customer?
