### ISSUE TITLE
PayPal IPN

### ISSUE THREAD

**Issue by nash4ever** [Payum/Payum#567]
Hi,
I try to implement PayPal IPN.
I use your sandbox code for testing, but my details field in the payum_notification_details table is always empty.
`
        $this->gateway->execute($getHttpRequest = new GetHttpRequest());
        $notification->setDetails($getHttpRequest->query);
`
And I read the documentation of PayPal IPN, and I foud that there are 4 steps to validate the IPN:

> Receives an IPN message sent from PayPal
> Confirms to PayPal that the message was received
> Verifies that it is a valid IPN message using the request-response handshaking required by PayPal
> Processes the IPN messages according to your needs

Does Payum do these steps, or I should do it myself?

Thanks for your help.

**Comment by makasim** [comment]
If you are using the payum express checkout extension you do not need paypal-ipn package. The notification management is already there. The secure notify url is generated and is sent to paypal. Later paypal uses that url to send notifications back to you (make sure the web server accessible from the internet) and processed. 

What you have to do is to register an extension that will do app specific logic ones the payment status is changed. This is described here: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/instant-payment-notification.md

If your app is not accessible from the Internet, it is not a problem. In this case, you have to find `NOTIFY_URL` in payment's details (payments table details column in the database) and paste it to the browser and request yourself.
