### ISSUE TITLE
How do I configure stripe?

### ISSUE THREAD

**Issue by safwan74** [Payum/Payum#571]
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "gateway" under "payum"

Using the following configuration 

gateways:
        stripe_js:
            factory: stripe_js
            publishable_key: my publishable key
            secret_key: my secret key

**Comment by makasim** [comment]
What is you version of payum bundle?

**Comment by makasim** [comment]
Looks like they are related http://stackoverflow.com/questions/39157427/symfony-payum-and-stripe-error

If so I gave an answer in the SO as a comment.
