### ISSUE TITLE
Stripe - Save Credit Card

### ISSUE THREAD

**Issue by adrian410** [Payum/Payum#572]
Hi guys,

I try to get the token of the credit card to save it, but i keep getting this error :

> Request GetCreditCardToken{model: ArrayObject} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.

But my model is not a ArrayObject, is a  \Payum\Core\Model\PaymentInterface.

I based my code on "PayumBundleSandbox" (Just changed from PaymentDetails to Payment, i tried with PaymentDetails and i get the same error but with "PaymentDetails" instead of "ArrayObject" ) :

My Prepare.php : 

From https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/StripeBundle/Controller/PurchaseExamplesController.php

    public function prepareSubscriptionAction(Request $request)
    {
        $gatewayName = 'stripe_checkout';

        $storage = $this->getPayum()->getStorage(Payment::class);

        $form = $this->createForm('form', null, ['method' => 'POST']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user= $this->get('security.context')->getToken()->getUser();

            /** @var $payment PaymentDetails */
            $payment = $storage->create();

            $payment->setNumber(uniqid());
            $payment->setCurrencyCode('EUR');
            $payment->setTotalAmount(2000); // 20.00 EUR
            $payment->setDescription('Test');
            $payment->setClientId($user->getId());
            $payment->setClientEmail($user->getEmail());

            $payment->setDetails(array(
                 'local' => ['save_card' => true, 'customer' => ['plan' => 'test','email'=>"foo@example.com"]]
            ));

            $storage->update($payment);

            $captureToken = $this->getPayum()->getTokenFactory()->createCaptureToken(
                $gatewayName,
                $payment,
                'croa_payment_done'
            );

            

            return $this->redirect($captureToken->getTargetUrl());
        }

        return ['form' => $form->createView()];
    }`

My Done.php :

From
https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaymentBundle/Controller/DetailsController.php

```
public function viewAction(Request $request)
    {
        $token = $this->getPayum()->getHttpRequestVerifier()->verify($request);

        $gateway = $this->getPayum()->getGateway($token->getGatewayName());



        try {
            $gateway->execute(new Sync($token));
        } catch (RequestNotSupportedException $e) {}

        $gateway->execute($status = new GetHumanStatus($token));

        
        $payment = $status->getFirstModel();

        $em = $this->container->get('doctrine')->getEntityManager(); 
        $className = $em->getClassMetadata(get_class($payment))->getName();
        echo $className;

        dump($payment);
        //exit();
        // Sauvegarde de la carte de crédit
        $user= $this->get('security.context')->getToken()->getUser();
        $gateway->execute($getToken = new GetCreditCardToken($payment)); // !! ERROR !!
        //exit();

        $this->get('credit_card.service')->save($getToken,$user);

        $refundToken = null;
        if ($status->isCaptured() || $status->isAuthorized()) {
            $refundToken = $this->getPayum()->getTokenFactory()->createRefundToken(
                $token->getGatewayName(),
                $status->getFirstModel(),
                $request->getUri()
            );
        }

        $captureToken = null;
        if ($status->isAuthorized()) {
            $captureToken = $this->getPayum()->getTokenFactory()->createCaptureToken(
                $token->getGatewayName(),
                $status->getFirstModel(),
                $request->getUri()
            );
        }
        
        $details = $status->getFirstModel();
        if ($details instanceof  DetailsAggregateInterface) {
            $details = $details->getDetails();
        }

        if ($details instanceof  \Traversable) {
            $details = iterator_to_array($details);
        }



        return $this->render('CroaPaymentBundle:Details:view.html.twig', array(
            'status' => $status->getValue(),
            'payment' => htmlspecialchars(json_encode($details, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)),
            'gatewayTitle' => ucwords(str_replace(array('_', '-'), ' ', $token->getGatewayName())),
            'refundToken' => $refundToken,
            'captureToken' => $captureToken,
        ));
    }
}

```
Anybody has an idea what's going on ?

Thanks,
Adrian.

**Comment by makasim** [comment]
The answer is simple, there is no stripe action that support such a request. It has to be implemented.

**Comment by makasim** [comment]
But is not in the master branch, for some reason.

**Comment by adrian410** [comment]
Thanks for your informations.

How can i get these modification ? I can't find the version of these changes to put in my composer.json.

**Comment by adrian410** [comment]
Is it possible for you to add this file 
https://github.com/formapro-forks/Payum/blob/62683b9e427eed7429bfe18d757ea55e83b8be1d/src/Payum/Stripe/Action/GetCreditCardTokenAction.php
in the master branch.

I tried to put your branch "stripe-subscription" into my composer.json but it doesn't work.

**Comment by makasim** [comment]
I am going to re add it, dont have any idea why it disappeared

**Comment by adrian410** [comment]
Ok thanks man, it's strange indeed.

**Comment by adrian410** [comment]
Can you tell me please when it's resolved please ?

**Comment by makasim** [comment]
done

**Comment by adrian410** [comment]
Thanks man, u are the best chico ! Peace out vato
