### ISSUE TITLE
Paypal Do Capture after Authorization

### ISSUE THREAD

**Issue by bretto36** [Payum/Payum#576]
I'm attempting to implement Authorization payments for a site, we want to progressively take the money for products we can stock, otherwise don't take that part of the money. 

I'm attempting to do the doCapture call, but when there is an error it does not let me know. Am i doing this incorrectly or is it a bug. 

```
$model = [
            'PAYMENTREQUEST_0_AMT' => 1,
            'PAYMENTREQUEST_0_COMPLETETYPE' => 'NotComplete',
            'PAYMENTREQUEST_0_CURRENCYCODE' => 'EUR',
            'PAYMENTREQUEST_0_TRANSACTIONID' => $order->getPaypalAuthorizationId()
        ];

        $gateway = $this->get('payum')->getGateway('paypal_express_checkout');
        $gateway->execute($response = new DoCapture($model, 0));
        $payment = $response->getFirstModel();
        $gateway->execute($status = new GetHumanStatus($payment));
```
If i purposely change the currencycode to empty, or something that doesn't match the auth, i do not receive any error messages (unless i go in and output the result of the doCapture [see below] call to the paypal api). 

Am i just implementing this incorrectly? The $status value tells me 'new' but if i output the doCapture result (which never gets handled by anything), i get:

```
DoCaptureAction.php on line 48:
array:10 [▼
  "AUTHORIZATIONID" => "xxxxxxx"
  "TIMESTAMP" => "2016-09-12T03:32:31Z"
  "CORRELATIONID" => "xxxxxxxxxx"
  "ACK" => "Failure"
  "VERSION" => "65.1"
  "BUILD" => "25184459"
  "L_ERRORCODE0" => "10613"
  "L_SHORTMESSAGE0" => "Currency mismatch."
  "L_LONGMESSAGE0" => "Currency of capture must be the same as currency of authorization."
  "L_SEVERITYCODE0" => "Error"
]
```

**Comment by makasim** [comment]
@bretto36 Are you sure you want to use DoCapture from api level (kind of low level) instead of Capture? 

Try to create the model like this 

```php
<?php
$model = new \ArrayObject([
            'PAYMENTREQUEST_0_AMT' => 1,
            'PAYMENTREQUEST_0_COMPLETETYPE' => 'NotComplete',
            'PAYMENTREQUEST_0_CURRENCYCODE' => 'EUR',
            'PAYMENTREQUEST_0_TRANSACTIONID' => $order->getPaypalAuthorizationId()
]);
```

and see if it stores data in this case

**Comment by bretto36** [comment]
I will try using the capture and by changing the model type. Thanks for the quick response. Will post back with more info.

**Comment by bretto36** [comment]
When i do a Capture i get give an error message - 

"L_ERRORCODE0" => "10005"
"L_SHORTMESSAGE0" => "Option not supported"
"L_LONGMESSAGE0" => "Transaction ID is not supported."
"L_SEVERITYCODE0" => "Error"

new implementation (return url and cancel url are mandatory when using Capture)

        $model = new \ArrayObject([
            'PAYMENTREQUEST_0_AMT'           => $resource->getTotal(),
            'PAYMENTREQUEST_0_COMPLETETYPE'  => 'NotComplete',
            'PAYMENTREQUEST_0_CURRENCYCODE'  => $order->getCurrencyCode(),
            'PAYMENTREQUEST_0_TRANSACTIONID' => $order->getPaypalAuthorizationId(),
            'RETURNURL' => 'test',
            'CANCELURL' => 'test',
            'PAYMENTINFO_0_PENDINGREASON' => 'authorization',
        ]);

But the Capture actually worked
```
DoCaptureAction.php on line 49:
array:20 [▼
  "AUTHORIZATIONID" => "97061141E8050425N"
  "TIMESTAMP" => "2016-09-12T23:49:17Z"
  "CORRELATIONID" => "2a4928459fc3d"
  "ACK" => "Success"
  "VERSION" => "65.1"
  "BUILD" => "25037053"
  "TRANSACTIONID" => "9LP85156K9533120F"
  "PARENTTRANSACTIONID" => "97061141E8050425N"
  "TRANSACTIONTYPE" => "cart"
  "PAYMENTTYPE" => "instant"
  "ORDERTIME" => "2016-09-12T23:49:17Z"
  "AMT" => "1.00"
  "FEEAMT" => "0.39"
  "TAXAMT" => "0.00"
  "CURRENCYCODE" => "EUR"
  "PAYMENTSTATUS" => "Completed"
  "PENDINGREASON" => "None"
  "REASONCODE" => "None"
  "PROTECTIONELIGIBILITY" => "Eligible"
  "PROTECTIONELIGIBILITYTYPE" => "ItemNotReceivedEligible,UnauthorizedPaymentEligible"
]
```
I can't find anyone else who's put code up to achieve this. I might just switch to the Paypal PHP Sdk for this.

**Comment by makasim** [comment]
I've just tested the authorize and later capture flow on the [sandbox](https://github.com/makasim/PayumBundleSandbox).

Heres some direct links to the example:

https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaypalExpressCheckoutBundle/Controller/PurchaseExamplesController.php#L343
https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaymentBundle/Controller/DetailsController.php#L41

Everything works just fine.
