### ISSUE TITLE
Documentation problem for paypal_rest, undefined $paypalRestPaymentDetailsClass

### ISSUE THREAD

**Issue by cariba** [Payum/Payum#586]
the documentation ([link](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/Rest/Resources/docs/get-it-started.md)) uses in the prepare payment section this code:
`$storage = $payum->getStorage($paypalRestPaymentDetailsClass);`
It's unclear what the variable "`$paypalRestPaymentDetailsClass`" shall represent.
Could someone please clarify?
Thank you!

**Comment by makasim** [comment]
This one https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/Rest/Model/PaymentDetails.php

The doc has to be fixed

**Comment by cariba** [comment]
Thank you for the reply, makasim!

Tried it already in a symfony context but could not get it work.

What is the procedure, to make in work in symfony?
