### ISSUE TITLE
OmnipayBridge does not seem to support Notify requests

### ISSUE THREAD

**Issue by steffenbrem** [Payum/Payum#590]
I am using Payum and the Payum OmnipayBridge in production for some time now and most of the payments (95%) go through properly. But sometimes I get a message from the payment provider Mollie that the webhook returns a 500 error. Now it turns out that the `notify` url returns the following error:

![d](https://puu.sh/rrMTP/fac0213b99.png)

I have been trying to find out what is missing but don't know if it's a bug in Sylius or Payum itself.

I am using the latest stable payum.

**Comment by makasim** [comment]
for ref https://github.com/Sylius/Sylius/issues/6249

**Comment by steffenbrem** [comment]
Thanks for helping out @makasim I now know what to do and will try to add the `NotifyAction` for Omnipay!
