### ISSUE TITLE
Question - amount division by 100

### ISSUE THREAD

**Issue by KilroggD** [Payum/Payum#597]
Hello! I've recently integrated payum into my project in order to allow users to buy premium membership. Is it OK that Payum functions divide my amount (e.g. if I pass 19 USD payment, paypal shows 0,19$). What is a correct way to avoid it, except multiplying amount manually ($amount*=100)? 
I found this code in ConvertPaymentAction.php. Does the multiplier depend on currency chosen? Is it only for paypal or all supported payments?
_>         $this->gateway->execute($currency = new GetCurrency($payment->getCurrencyCode()));
>         $divisor = pow(10, $currency->exp);
>         $details['PAYMENTREQUEST_0_AMT'] = $payment->getTotalAmount() / $divisor;_

I am sorry but I couldn't find anything about it in documentation =(

**Comment by makasim** [comment]
Payum use int for the whole prices it deal with. So 10.23$ is 1023 int. and 100JPY is 100 as they do not have cents. 

Internally the amount is converted to that format that the gateway accepts. Paypal for example works with floats and the amount has to be adjusted, other gateways accepts integer in cents

**Comment by makasim** [comment]
And the doc https://github.com/Payum/Core/blob/master/Resources/docs/get-it-started.md have a note about this rule: 

There's a code like this:

```
$payment->setTotalAmount(123); // 1.23 EUR
```
