### ISSUE TITLE
[Question] Interest / Docs on providing new payment-providers?

### ISSUE THREAD

**Issue by benbender** [Payum/Payum#605]
I'm implementing two new payment-providers (bitpay.com / paymill.com) for Payum as part of a client-project. The client is willing to provide the implementations to the community.

When I've finished the project I would clean some parts, write a little documentation and would be able to provide pull-requests. My questions, before starting the effort, would be if there is interest in those new providers and if there is any documentation/specific codingstyle/preferences etc about doing so?

Thanks for your work & all the best!

**Comment by makasim** [comment]
something like this should be done in order to be merged in this repo

```
Thanks for the contribution. In order to make it part of official lib some things have to be done. such as:

tests
at least get it started doc
code should look similar to other parts
code review
link to the gateway documentation
sandbox example
If you do not want to bother with all that stuff you can release the code as the standalone package. I'd be happy to add it to list of supported gateways.
```

https://github.com/Payum/Payum/pull/536#issuecomment-215625357

**Comment by makasim** [comment]
but you can create your own repo, put the code there. Send a pull request with links to it. I'd be more than happy to accept it. Here's the list of available gateways https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/supported-gateways.md

**Comment by makasim** [comment]
The easiest way to start with new gateway is to use skeleton project. Here's more: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/develop-gateway-with-payum.md

**Comment by benbender** [comment]
Thanks for the quick response. I had seen most of it and hoped that there is something I've overlooked. I thought about something like this: http://symfony.com/doc/current/contributing/index.html

It think most of it could be simply adapted for Payum and would be helpful. 

I think, to get a fast start, I will put both providers in their own repositories and give the community a peak. If there is interest in merging them, I would be willing to implement missing features etc.

**Comment by makasim** [comment]
so basically nothing special 

* code style psr2\symfony
* tests
* basic docs
* sandbox example (so I can manually test it works while releasing stuff). I could help here.
