### ISSUE TITLE
How to get IPN details?

### ISSUE THREAD

**Issue by binarious** [Payum/Payum#606]
In an older version it was possible to get the current model (via `$request->getModel()`) and the received IPN (via `$request->getNotification()`). This is not possible with the new `ExtensionInterface` anymore. How can I compare the two states (current local state <-> new paypal state)?

**Comment by makasim** [comment]
good question.

In the extension you can clone\store payment data (usually an array) to a property `onPreExecute` and take update data `onPostExecute` and compare the two.

**Comment by binarious** [comment]
Thank you, I'll try that and reopen if anything fails. This information would be very useful in the IPN docs.

**Comment by binarious** [comment]
@makasim I'm still having problems on this one.
I have the following:
```php
protected function getModel($request)
{
    if (!($request instanceof Generic)) {
        return null;
    }
    if ($request instanceof GetStatusInterface) {
        return null;
    }

    $payment = $request->getModel();

    if (!($payment instanceof PaymentDetails)) {
        return null;
    }

    return $payment;
}

public function onPreExecute(Context $context)
{
    $this->oldModel = $this->getModel($context->getRequest());
}
```
And the same in `onPostExecute`. Then I compare these two, right?
But `$context->getRequest()` contains a `PayumSecurityToken` which contains just the `Payum\Core\Model\Identity`. Isn't there an built-in way to get the PaymentDetails here? Or do I have to query with Doctrine manually?

**Comment by makasim** [comment]
try $context->getFirstModel().

**Comment by binarious** [comment]
That's empty:
```php
$model = $request->getFirstModel();
die('model: ' . print_r($model, true) . ' identity: ' . print_r($request->getModel()->getDetails(), true));
```
Outputs:
```
model:  identity: Payum\Core\Model\Identity Object
(
    [class:protected] => MYVENDOR\PaymentBundle\Entity\PaymentDetails
    [id:protected] => 1
)
```
But PaymentDetails with ID 1 contains data.
