### ISSUE TITLE
Authorize card Code is required

### ISSUE THREAD

**Issue by edvinasnet** [Payum/Payum#607]
Hello,

we are working with authorize.net payments, and with card payments we get "card Code is required." error. When added in CaptureAction.php 53line:
`$model['card_code'] = SensitiveValue::ensureSensitive($card->getSecurityCode());`
everything working  perfect. Is it security solution to fix this error? 

Thanks!

**Comment by makasim** [comment]
As I can see from the code capturing by a code is not supported. 
https://github.com/Payum/Payum/blob/master/src/Payum/AuthorizeNet/Aim/Action/CaptureAction.php#L45

**Comment by edvinasnet** [comment]
@makasim it is supporting card code ( https://support.authorize.net/authkb/index?page=content&id=A546 )

**Comment by makasim** [comment]
fixed in https://github.com/Payum/Payum/pull/608
