### ISSUE TITLE
Reversed and Cancel Reversal statuses

### ISSUE THREAD

**Issue by Great-Antique** [Payum/Payum#609]
There are some questions about above-mentioned statuses.

1. Why do we mark Payment as failed if `PAYMENTREQUEST_n_PAYMENTSTATUS` is `Api::PAYMENTSTATUS_CANCELED_REVERSAL`?

Afaik Payment has transitions `Completed/Processed -> Reversed` and `Reversed -> Canceled-Reversal`. So `Canceled-Reversal` means that Payment is `Completed/Processed` again and as I understand we should mark it as captured but not as failed.

2. Why don't we process `Reversed` status?
Should we add
* `GetHumanStatus::STATUS_REVERSED` and `GetBinaryStatus::STATUS_REVERSED` constants
* `GetStatusInterface::isReversed()` and `GetStatusInterface::markReversed()` methods
?

**Comment by makasim** [comment]
> 1. Why do we mark Payment as failed if PAYMENTREQUEST_n_PAYMENTSTATUS is Api::PAYMENTSTATUS_CANCELED_REVERSAL?

I am not sure, we have to dig into paypal's doc. As for me `Reversed` sounds like cancelled or failed but not captured.

> Why don't we process Reversed status?
Missing feature?

**Comment by Great-Antique** [comment]
> I am not sure, we have to dig into paypal's doc. As for me Reversed sounds like cancelled or failed but not captured.
Imo `Reversed` sounds like `Canceled order and canceled (or reversed) payment` (Like `Refunded` = `Canceled order and refunded (or maybe canceled) payment`. 
But `Canceled reversal` is more like `Captured again payment` and `Canceled` or `In progress` **order**.
Order status depends on reverse reason (for e.g., https://github.com/magento/magento2/blob/develop/app/code/Magento/Paypal/Model/Info.php#L476-L520). So in every case of `Canceled reversal` we have to decide to refund payment and cancel order; or not to refund payment and process order.

> Missing feature?
I need this status so I'm going to create pull request

**Comment by Great-Antique** [comment]
As I figured out status `Failed` (PayPal status) is used only when transaction is canceled by bank. So if we use `Failed` (Payum status) to mark `Expired` and `Failed` PayPal statuses (By this logic, we should mark `Failed` payments with `Reversed` PayPal status too), then `Canceled-Reversal` should be marked `Failed` (And we do it). This sounds logical.

The problem with reversed payments I can solve by handling transition `Captured -> Failed` (as I never get expired authorization after the payment was captured). Good.

Other problem is to handle Payment flow when `Reversed` payment returns. In Payum statuses the transition would be `Failed` -> `Failed`. The only thing I can do in this case is to handle `Canceled-Reversal` in PayPal seller's account manually (or create some interface for resolution these cases). Am I right?

**Comment by Great-Antique** [comment]
Maybe `CHECKOUTSTATUS` of reversed payments is always `PaymentActionFailed`. I can't find info that proves it. But if so - PR #611 makes no sense.

**Comment by makasim** [comment]
@Great-Antique merged 611
