### ISSUE TITLE
add Omnipay gateways?

### ISSUE THREAD

**Issue by Marquis-H** [Payum/Payum#612]
can i add Omnipay gateways to payum?

**Comment by makasim** [comment]
Yes, it is. There is a bridge https://github.com/Payum/OmnipayBridge

**Comment by Marquis-H** [comment]
example ， i add lokielse/omnipay-alipay , how can i  do ?

**Comment by Marquis-H** [comment]
@makasim

**Comment by makasim** [comment]
Have you checked out the readme on the link I posted? It shows how to use omnipay gateway.
