### ISSUE TITLE
Again on cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by Leggy7** [Payum/Payum#614]
I'm using the guzzle6 adapter and when the process reaches the doAction I get the following error:

> cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

And I can't get rid of the problem. I tried to set the curl option to false in this way

```
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
```

And while browsing for solutions I found a [SO post](http://stackoverflow.com/questions/28941061/overload-symfony2-vendor-class-to-set-curl-verify-peer-option-to-false/28960181#28960181) which deal with the buzz adapter. In the guzzle adapter I could not find anything like that so I'm stuck.

Any suggestion?

**Comment by makasim** [comment]
The problem does not relate to Payum in any way. Long story short: you are missing a required cipher. try to to update openssl, curl, php to the latest versions

**Comment by makasim** [comment]
Please never disable security it is not a solution. 

curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

**Comment by Leggy7** [comment]
Thank you, anyhow [this](https://github.com/Payum/PayumBundle/issues/99) solved the problem.
