### ISSUE TITLE
New gateways

### ISSUE THREAD

**Issue by liamsorsby** [Payum/Payum#615]
Hi @makasim,

I will need to add a couple of new gateway extensions to the payum over the next month. What would be the advised method of doing this? Would it be best to create the extensions and then message you once all tests have passed to be forked into the repo?

Regards,
Liam

**Comment by liamsorsby** [comment]
I've actually just read about the omnipay gateway bridge which I shall look into. However, this question is based on if it doesn't exist in either library.

**Comment by makasim** [comment]
It would be easier to create a stand alone package. Later it could be merged to payum's repo.
