### ISSUE TITLE
Twig 2.x - compatibility (update required version of twig/twig)

### ISSUE THREAD

**Issue by wernerdweight** [Payum/Payum#616]
Is there any reason not to have Payum compatible with the current version of twig (2.1.0)? Is it possible to change the entry in composer.json to something like this, so that Payum could be used with newer projects based on current twig (which is installed as default for standard symfony 3 distribution)?
```json
...
"twig/twig": "~1.0|~2.0",
...
```
Deprecated features of Twig 1.x are listed [here](http://twig.sensiolabs.org/doc/1.x/deprecated.html)

**Comment by makasim** [comment]
That's indeed something we have to do. Most possibly it would require only a composer requirement to be updated.
