### ISSUE TITLE
stripe API version

### ISSUE THREAD

**Issue by frechina** [Payum/Payum#627]
Hi,

is it possible to update the stripe API version used in payum/stripe ?

thanks

**Comment by makasim** [comment]
Why not? (If there is not BC breaks in the lib) 

What version would you like to update to?

**Comment by frechina** [comment]
The latter (4.4.0 ?) would be fine!

**Comment by makasim** [comment]
There is slight BC. I guess we are affected.

https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md#400-2016-09-28

**Comment by frechina** [comment]
lets jump at least to 3.23.0 until we can update to 4.x

**Comment by makasim** [comment]
3.23 could be used at the moment 

https://github.com/Payum/Payum/blob/master/src/Payum/Stripe/composer.json#L24

**Comment by frechina** [comment]
oh sure! I hope we can jump to 4.4.0
