### ISSUE TITLE
Make notification_urls configurable for payum/sofort

### ISSUE THREAD

**Issue by blubberblah** [Payum/Payum#628]
Hi!
Is there already the possibility to prevent payum/sofort implementation sending the notification_url via the XML payload when requesting the payment URL? I've upgraded to a recent version of payum/sofort. Before I've used the abandoned wiseape/payum-sofortuberweisung which didn't send the notification_url. Currently I'm having problems because the host the notification_url is pointing at, isn't reachable from internet (staging-system). We don't use the notification_url anyway.

This ist the Response from sofort API if the notification_urls can't be looked up:
```
<?xml version="1.0" encoding="UTF-8"?>
<errors>
  <error>
    <code>8016</code>
    <message>Must be a valid URL.</message>
    <field>notification_urls.notification_url.1</field>
  </error>
</errors>
```

Thanks for any help,
Regards

**Comment by blubberblah** [comment]
In the meantime I figured out how to override the default notiication_url:
```
$storage = $payum->getStorage('MyPaymentDetails');
$paymentDetails = $storage->create();
$paymentDetails->setDetails(['notification_url' => 'http://my.public.url']);
$storage->update($paymentDetails);
```
unfortunately preventing payum from setting the notification_url at all isn't possible via this method. We don't use the notification_url so i would like to simply not send it at all. Setting the notification_url to `false`, `null` or an empty string doesn't help. In these cases payum just uses generated default URL and but doesn't unset it.

**Comment by makasim** [comment]
What the problem with a default url? Does it affect a payment process somehow?

**Comment by makasim** [comment]
That's indeed correct that the staging server is not reachable from the Internet

**Comment by blubberblah** [comment]
> That's indeed correct that the staging server is not reachable from the Internet

exactly, and there seems no way preventing payum NOT to put notification_url into the generated Sofort-API request. The following would be an nice enhancement:

```
$paymentDetails->setDetails(['notification_url' => false]);
```

Setting notification_url to false would then result in NOT setting it at all into the generaten Request as it seems not be a mandatory requirement for a Sofort-API request

**Comment by makasim** [comment]
Does the notify url prevent you from making a success payment?
Does it affect the flow in some way or another?

**Comment by blubberblah** [comment]
Yes, it't prevents a successful payment. There is no flow at all because even the first page of the payment flow isn't displayed.
Sofortüberweisung doesn't respond via a Payment URL but does immediatelly redirect to the error_url. The reason is, that it checks the DNS of the notification_url which isn't reachable from the internet. The column `details` in the PaymentDetails Entity has the following content:

```
{
   "currency_code":"EUR",
   "amount":2.99,
   "reason":"sofort:12",
   "success_url":"http:\/\/myshop.staging.company.com\/payment\/capture\/UPWGgOtyg5Mow2n2gzE1ZB84f10ZVVxhSIDodqjQYpM",
   "abort_url":"http:\/\/myshop.staging.company.com\/payment\/capture\/UPWGgOtyg5Mow2n2gzE1ZB84f10ZVVxhSIDodqjQYpM",
   "notification_url":"http:\/\/myshop.staging.company.com\/payment\/notify\/3vz_Oc6O9pqCvusURHOwA2M1zsh212yNpi0jBPhgxhM",
   "error":"Error: 8016:Must be a valid URL."
}
```
When I log into Sofortüberweisung admin-area the aborted transaction contains the following Error:

```
<?xml version="1.0" encoding="UTF-8"?>
<errors>
  <error>
    <code>8016</code>
    <message>Must be a valid URL.</message>
    <field>notification_urls.notification_url.1</field>
  </error>
</errors>
```

So leaving out notification_url in the initial request would prevent such an error. As I already mentioned, we didn't had this Problem with the abandoned wiseape/payum-sofortuberweisung Bundle because it didn't add payment_url to the inital request.

**Comment by makasim** [comment]
well then it has to be disabled for sandbox indeed. 

Though I do not think we have to configure the behavior from the concret payment model. Instead

We can add an extra option to the sofort gateway factory like `use_notification_url`. Later we can use that option in the api class `createTransaction` method to include or exclude notification url. 

Wdyt?

**Comment by blubberblah** [comment]
Looks reasonable and would do the trick :-)
