### ISSUE TITLE
GatewayAwareAction is deprecated

### ISSUE THREAD

**Issue by StudioMaX** [Payum/Payum#632]
Hi,

In the Symfony Profiler I saw a lot of deprecations like:

> The Payum\Paypal\ExpressCheckout\Nvp\Action\ConvertPaymentAction class extends Payum\Core\Action\GatewayAwareAction that is deprecated since 1.3 will be removed in 2.0. Use trait+interface in your classes.

> The Payum\Paypal\ExpressCheckout\Nvp\Action\NotifyAction class extends Payum\Core\Action\GatewayAwareAction that is deprecated since 1.3 will be removed in 2.0. Use trait+interface in your classes.

> The Payum\Paypal\ExpressCheckout\Nvp\Action\PaymentDetailsSyncAction class extends Payum\Core\Action\GatewayAwareAction that is deprecated since 1.3 will be removed in 2.0. Use trait+interface in your classes.

> The Payum\Paypal\ExpressCheckout\Nvp\Action\RecurringPaymentDetailsSyncAction class extends Payum\Core\Action\GatewayAwareAction that is deprecated since 1.3 will be removed in 2.0. Use trait+interface in your classes.

> The Payum\OmnipayBridge\Action\ConvertPaymentAction class extends Payum\Core\Action\GatewayAwareAction that is deprecated since 1.3 will be removed in 2.0. Use trait+interface in your classes.

This class GatewayAwareAction was changed in 28 Mar 2016, around a year, but it's still used in differen places in Payum... I think that all usages of it should be fixed in case this class is still deprecated.

**Comment by makasim** [comment]
It is still deprecated
