### ISSUE TITLE
How update status into storage after replace model in NotifyAction?

### ISSUE THREAD

**Issue by roquie** [Payum/Payum#649]
Hello,

In the NotifyAction, at end of execute method, I replaced model with http request data:
```php
// ...
 $model->replace($httpRequest->request);
 throw new HttpResponse('OK');
}
```
and I received status, like so:

```php
$gateway = $this->getPayum()->getPayment('uniteller');
$payment = $this->getPayum()
                ->getStorage(Payment::class)
                ->findBy(array(
                    'number' => $request->get('Order_ID'),
                ));

if ($reply = $gateway->execute(new Notify($payment), true)) {
    if ($reply instanceof HttpResponse) {
        $gateway->execute($status = new GetHumanStatus($payment));

        if ($status->isCaptured() || $status->isAuthorized()) {
            // Yes! Payment is done!
            // But where database changes for payment row?
            // Current payment to have is `pending` status
        }

        throw $reply;
    }

    throw new \LogicException('Unsupported reply', null, $reply);
}
```

Library should to update status in storage or not?

**Comment by makasim** [comment]
> Library should to update status in storage or not?

no it is not. 

you can `$gateway->execute(new GetHumanStatus($model));`

to find out new status and store it yourself. You can take it from status request and set to the model.

**Comment by makasim** [comment]
here's how Sylius updates its Payment status https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php#L88

**Comment by roquie** [comment]
It so strange, if create record with status on `capture` action, it would be nice to update them on `done` action.

Thanks, I'll see how use extensions.
