### ISSUE TITLE
Custom Gateway

### ISSUE THREAD

**Issue by liamsorsby** [Payum/Payum#651]
In the skeleton for creating a payment gateway it doesn't give any information to tell payum to redirect to a 3rd party site.

For example it redirects the user to PayPal when using the PayPal Express Checkout Bundle. Can you advise how to do this?

The documentation on the skeleton is quiet thin and I've spent a while looking through the other gateway bundles but cannot see anywhere other than AuthorizeTokenAction that initialises this.

Regards,
Liam

**Comment by makasim** [comment]
The best thing is to look at existing gateways and try to do the same. 

Regarding the redirect you have to throw a reply HttpRedirect or HttpPostRedirect (depends what payment provider wants from you). 

You might need to set a return url (the capture token one) to payment data so the payment provider knows where to redirect a user after the purchasement. 

Some providers do not allow to set a return url per payment instead you have to configure one return url for all payments in their backend. (like be2bill). That is harder to implement at app side but still possible. Look at be2bill offsite, it is implemented there.

**Comment by liamsorsby** [comment]
Hi @makasim,

Thank you, it seems that the HttpPostRedirect is what I was looking for and I was over complicating the issue.

Regards,
Liam

**Comment by liamsorsby** [comment]
Hi Makasim,

I wonder if you could clarify a few things to do with Be2Bill.

I've managed to get the redirect over to the card processing facility however, I cannot seem to get the notify token to work at all. The request seems to go from the Capture Execute method to the The controller that handles the Response. Once it hits this it fails stating that payum_token hasn't been set.

These execute method looks like:
```php
        RequestNotSupportedException::assertSupports($this, $request);

        $model = ArrayObject::ensureArrayObject($request->getModel());

        $httpRequest = new GetHttpRequest();
        $this->gateway->execute($httpRequest);

        if (isset($httpRequest->request["status"])) {
            $model->replace($httpRequest->request);
        } else {
            
            $notifyToken = $this->tokenFactory->createNotifyToken(
                $request->getToken()->getGatewayName(),
                $request->getToken()->getDetails()
            );
            $model["notify_token"] = $notifyToken->getHash();

            throw new HttpPostRedirect(
                $this->api->getApiEndpoint(),
                $this->api->addAuthorizeFields($model->toUnsafeArray())
            );
        }
```

Unfortunately, as soon as it hits ```$token = $this->get('payum')->getHttpRequestVerifier()->verify($request);``` it comes back stating that the token isn't set. Isn't this something that payum would generate and send back itself?

It seems that I can never get payum to use the notifyAction although it is registered in the gateway. Can you offer any advise as I've been looking through the code for Be2Bill for days trying to work out if I have missed something.

Any advise would be fantastic.

Kind Regards,
Liam

**Comment by makasim** [comment]
The notify url must contains either query parameter named `payum_token` or be a route parameter. The notify route which is shipped with the bundle has signature `/payment/notify/{payum_token}`.

A few questions: 

1. Does your server accessible from the internet ?
2. Try to var_dump `$notifyToken->getTargetUrl()`. What do you see there?
3. If the notify url looks good. Try to put it to the browser and perform the request  manually. Is the error still remain? 
4. Does the payment gateway understands that `$model["notify_token"]` must be used as a notification endpoint?

**Comment by liamsorsby** [comment]
I have tried this already and the notify url works manually. As I removed all validation from the notify url. The server does have access to the Internet and i have tested on a domain to make sure that post request works.

As for point 4. It does request a notification endpoint that is an optional field. Whether it uses it or not is another issue all together as I've had many issues with their lack of documentation and errors within it. Carnet only has two methods of sending over the data. 1 is the notify endpoint and the seconditions being a post request. However the post request only ever occurs if the user clicks on a return to website button which is highly unreliable.

If the gateway uses notify. I presume it would still require the token to be invalidated and the status updated? Or is this a step that wouldn't need to be implemented for a payment gateway that would only use notify?

**Comment by liamsorsby** [comment]
The issue seems to come from the following line:

```php
$token = $this->get('payum')->getHttpRequestVerifier()->verify($request);
```

which throws a 404 error and seems to be unable to verify the request.

**Comment by makasim** [comment]
@liamsorsby  Could you post here your everything you have in the request, including its attributes.

**Comment by liamsorsby** [comment]
Makism, do you mean the request that is being updated in the model? I seem to have got the notify to work but it just isn't validating or the request to initialise the gateway?

The one to request the gateway is:

```php
            $payment['chargetotal'] = $orderClass->getTotal();
            $payment['responseSuccessURL'] = $this->generateUrl("_eezeecommerce_payment_done", array(), UrlGeneratorInterface::ABSOLUTE_URL);
            $payment['responseFailURL'] = $this->generateUrl("_eezeecommerce_payment_done", array(), UrlGeneratorInterface::ABSOLUTE_URL);

            $payment->setOrder($orderClass);
            $storage->update($payment);

            $captureToken = $this->get('payum')->getTokenFactory()->createCaptureToken(
                $gatewayName, $payment, '_eezeecommerce_payment_done'
            );
            return $this->forward('PayumBundle:Capture:do', array('payum_token' => $captureToken));
```

I've also tried the return with ```return $this->redirect($captureToken->getTargetUrl());```

**Comment by makasim** [comment]
The symfony http request, the one you pass to verify method.

**Comment by liamsorsby** [comment]
The action that it throws the 404 is:

```php
public function doneAction(Request $request)
    {
        $token = $this->get('payum')->getHttpRequestVerifier()->verify($request);
        ......
}
```

And the notify updates the models as this:

```
{"gateway":"eezee_cardnet","currency":"826","chargetotal":"34.34","responseSuccessURL":"http:\/\/www.mytestdomain.co.uk\/payment\/done","responseFailURL":"http:\/\/www.mytestdomain.co.uk\/payment\/done","notify_token":"3H1_WLYmrdvDb6UmIkauTabmbS00w_azI5SQaZy_XOg","transactionNotificationURL":"http:\/\/www.mytestdomain.co.uk\/payment\/notify\/3H1_WLYmrdvDb6UmIkauTabmbS00w_azI5SQaZy_XOg","txndate_processed":"26\/04\/17 09:47:46","ccbin":"527475","timezone":"Europe\/London","shared_secret":"H>6dnT8#er","oid":"C-38274796-d041-4949-8a3a-afb40c05e899","password":"Xd)fZ5[6dh","cccountry":"N\/A","expmonth":"05","hash_algorithm":"SHA256","endpointTransactionId":"0062","processor_response_code":"00","terminal_id":"21401587","approval_code":"Y:478950:4120350874:PPXP:0062","expyear":"2019","response_code_3dsecure":"7","notification_hash":"3452443762323c97f0b907f6be8464e1ab7ea85cc897f7deaa7f14bb54e39aef","tdate":"1493192866","bname":"asd","ccbrand":"MASTERCARD","refnumber":"478950","txntype":"sale","paymentMethod":"M","txndatetime":"2017:04:26-08:47:29","cardnumber":"(MASTERCARD) ... 1770","ipgTransactionId":"84120350874","status":"APPROVED"}

**Comment by makasim** [comment]
The expected flow is next. 

1. prepare 
2. capture that results in redirect
3. capture when you come back
4. done where you act accoding to the payment status, remove the done token (so it could not be used second time and redirect a user to another page success or failure.

If you need a done action to be used several times then you can remove `invalidate` method from it.
The notify flow is completely  standalone process and should not interfere with neither capture nor done actions.

**Comment by liamsorsby** [comment]
Thank you for your help.

It looks like It was my flow was incorrect and it only seems to work with the notify. The capture token still doesn't validate but I am able to get the payment through the notify. I am assuming that this provider doesn't use capture, if that is even possible. Thank you for your assistance.

Kind Regards,
Liam
