### ISSUE TITLE
Paypal Payouts support

### ISSUE THREAD

**Issue by karser** [Payum/Payum#653]
Does this bundle support [Paypal Payouts](https://developer.paypal.com/docs/api/payments.payouts-batch/)?
I saw some [Paypal Rest API examples](https://github.com/Payum/Payum/blob/master/docs/paypal/rest/get-it-started.md) but I haven't seen payouts one.

**Comment by tacman** [comment]
@makasim has commits that seem to indicate that there's some support:

https://github.com/Payum/Core/search?q=payout&type=Commits&utf8=%E2%9C%93

**Comment by makasim** [comment]
https://github.com/Payum/Payum/blob/master/docs/paypal/masspay/get-it-started.md

**Comment by karser** [comment]
MassPay is different:
```
The Payouts API is a brand new REST-based API that replaces Mass Payments classic APIs. Payouts has more features as compared to Mass Payments.
Businesses which need to send disbursements to up to 500 recipients in a single API call will use the Payouts API.
```
http://stackoverflow.com/a/31174340/1642477

**Comment by makasim** [comment]
@karser There is a support in the payum core but the Paypal Payout is not supported.
