### ISSUE TITLE
paypal recurring payments

### ISSUE THREAD

**Issue by frechina** [Payum/Payum#654]
Hi,

I'm following the docs for implementing paypal recurring payments and I'm getting that after creating the recurring payment profile and call sync action I always get a "pending" status.

I see on sandbox paypal page that the payment is made a few seconds after I get the payment state, so my backend didn't know that the payment was finally successful.

is there any way to solve this?

Thank you for the help in advance

**Comment by makasim** [comment]
You have to enable notifications. In case of Paypal

1. If your host is not accessible from the Internet. copy the notification url from payment details and call it manually.
2. Add an extension to handle the payment changes https://github.com/Payum/Payum/blob/master/docs/instant-payment-notification.md

**Comment by frechina** [comment]
notification url is not working for me. As I see, it only makes a Sync action. I tried run the sync action after checking that the payment was completed on Paypal and it does not update the payment with status Active. It remains pending.

**Comment by makasim** [comment]
there must be a reason for pending status. what does `get transaction details` API call returns?

**Comment by frechina** [comment]
as I see, I can't get transaction details using GetTransactionDetails because I don't have a transaction id.

This is what I have in the aggreement

`		"PAYMENTREQUEST_0_AMT" : "0.00", 
        "L_BILLINGTYPE0" : "RecurringPayments", 
        "L_BILLINGAGREEMENTDESCRIPTION0" : "Some description", 
        "PAYMENTREQUEST_0_PAYMENTACTION" : "Sale", 
        "AUTHORIZE_TOKEN_USERACTION" : "commit", 
        "RETURNURL" : "http://localhost/payment/capture/ec6YxvAZJLviycsX5liZKjzm7vNyKr19Pq-BkjGzGQs", 
        "CANCELURL" : "http://localhost/payment/capture/ec6YxvAZJLviycsX5liZKjzm7vNyKr19Pq-BkjGzGQs?cancelled=1", 
        "PAYMENTREQUEST_0_NOTIFYURL" : "http://localhost/payment/notify/b10Lj2FhN5QdJohIGhiQ_jD1s3OArNBKlsvqnFZPiho", 
        "TOKEN" : "EC-0TJ50503DD776592V", 
        "TIMESTAMP" : "2017-05-09T14:12:54Z", 
        "CORRELATIONID" : "872a784f82eb2", 
        "ACK" : "Success", 
        "VERSION" : "65.1", 
        "BUILD" : "33435567", 
        "BILLINGAGREEMENTACCEPTEDSTATUS" : "1", 
        "CHECKOUTSTATUS" : "PaymentActionNotInitiated", 
        "CURRENCYCODE" : "USD", 
        "AMT" : "0.00", 
        "SHIPPINGAMT" : "0.00", 
        "HANDLINGAMT" : "0.00", 
        "TAXAMT" : "0.00", 
        "NOTIFYURL" : "http://localhost/payment/notify/b10Lj2FhN5QdJohIGhiQ_jD1s3OArNBKlsvqnFZPiho", 
        "INSURANCEAMT" : "0.00", 
        "SHIPDISCAMT" : "0.00", 
        "PAYMENTREQUEST_0_CURRENCYCODE" : "USD", 
        "PAYMENTREQUEST_0_SHIPPINGAMT" : "0.00", 
        "PAYMENTREQUEST_0_HANDLINGAMT" : "0.00", 
        "PAYMENTREQUEST_0_TAXAMT" : "0.00", 
        "PAYMENTREQUEST_0_INSURANCEAMT" : "0.00", 
        "PAYMENTREQUEST_0_SHIPDISCAMT" : "0.00", 
        "PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED" : "false", 
        "PAYMENTREQUESTINFO_0_ERRORCODE" : "0", 
        "EMAIL" : "mypaypal@account.com", 
        "PAYERID" : "4V2BM3L3WEKKN", 
        "PAYERSTATUS" : "verified", 
        "FIRSTNAME" : "same", 
        "LASTNAME" : "other", 
        "COUNTRYCODE" : "ES", 
        "SHIPTONAME" : "some other", 
        "SHIPTOSTREET" : "address", 
        "SHIPTOCITY" : "city", 
        "SHIPTOSTATE" : "state", 
        "SHIPTOZIP" : "02001", 
        "SHIPTOCOUNTRYCODE" : "ES", 
        "SHIPTOCOUNTRYNAME" : "Country", 
        "ADDRESSSTATUS" : "Unconfirmed", 
        "PAYMENTREQUEST_0_SHIPTONAME" : "some othe", 
        "PAYMENTREQUEST_0_SHIPTOSTREET" : "address", 
        "PAYMENTREQUEST_0_SHIPTOCITY" : "city", 
        "PAYMENTREQUEST_0_SHIPTOSTATE" : "state", 
        "PAYMENTREQUEST_0_SHIPTOZIP" : "02001", 
        "PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE" : "ES", 
        "PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME" : "country", 
        "PAYMENTREQUEST_0_ADDRESSSTATUS" : "Unconfirmed"`

and this is the recurring payment details

`"TOKEN" : "EC-0TJ50503DD776592V", 
        "DESC" : "Some description", 
        "EMAIL" : "mypaypal@account.com", 
        "AMT" : "0.99", 
        "INITAMT" : 0.99, 
        "CURRENCYCODE" : "EUR", 
        "BILLINGFREQUENCY" : "1", 
        "PROFILESTARTDATE" : "2017-05-08T22:00:00Z", 
        "BILLINGPERIOD" : "Day", 
        "PROFILEID" : "I-A8DC7ENS7YY8", 
        "PROFILESTATUS" : "PendingProfile", 
        "TIMESTAMP" : "2017-05-09T14:05:13Z", 
        "CORRELATIONID" : "d1f01b00248b6", 
        "ACK" : "Success", 
        "VERSION" : "65.1", 
        "BUILD" : "25237094", 
        "STATUS" : "Pending", 
        "AUTOBILLOUTAMT" : "NoAutoBill", 
        "MAXFAILEDPAYMENTS" : "0", 
        "SUBSCRIBERNAME" : "credit card", 
        "NUMCYCLESCOMPLETED" : "0", 
        "NUMCYCLESREMAINING" : "0", 
        "OUTSTANDINGBALANCE" : "0.00", 
        "FAILEDPAYMENTCOUNT" : "0", 
        "TRIALAMTPAID" : "0.00", 
        "REGULARAMTPAID" : "0.00", 
        "AGGREGATEAMT" : "0.00", 
        "AGGREGATEOPTIONALAMT" : "0.00", 
        "FINALPAYMENTDUEDATE" : "1970-01-01T00:00:00Z", 
        "SHIPTONAME" : "my name", 
        "SHIPTOSTREET" : "address", 
        "SHIPTOCITY" : "city", 
        "SHIPTOSTATE" : "state", 
        "SHIPTOZIP" : "02001", 
        "SHIPTOCOUNTRYCODE" : "ES", 
        "SHIPTOCOUNTRY" : "ES", 
        "SHIPTOCOUNTRYNAME" : "Spain", 
        "SHIPADDRESSOWNER" : "PayPal", 
        "SHIPADDRESSSTATUS" : "Unconfirmed", 
        "TOTALBILLINGCYCLES" : "0", 
        "SHIPPINGAMT" : "0.00", 
        "TAXAMT" : "0.00", 
        "REGULARBILLINGPERIOD" : "Day", 
        "REGULARBILLINGFREQUENCY" : "1", 
        "REGULARTOTALBILLINGCYCLES" : "0", 
        "REGULARCURRENCYCODE" : "EUR", 
        "REGULARAMT" : "0.99", 
        "REGULARSHIPPINGAMT" : "0.00", 
        "REGULARTAXAMT" : "0.00"`

**Comment by makasim** [comment]
`"CHECKOUTSTATUS" : "PaymentActionNotInitiated", ` means you have not visited the PayPal side and haven't confirmed the agreement.

**Comment by frechina** [comment]
So maybe am I doing something wrong? These are the steps I follow:

1) I create a Payment with this details for make it recurrent.
	```
	$details['PAYMENTREQUEST_0_AMT'] = 0; // I don't want an initial charge
	$details['L_BILLINGTYPE0'] = Api::BILLINGTYPE_RECURRING_PAYMENTS;
	$details['L_BILLINGAGREEMENTDESCRIPTION0'] = "Some description"

```
2) I create the capture token for the payment. This gives me a target url (paypal url) and I redirect the user to such url.

3) When the user accepts fills the credentials and accepts the payment, I get on the callback (/done) a status "Captured" and the agreement in the request. Then I create the Recurring Payment Profile with this data

	```
	$recurringPayment['TOKEN'] = $agreement['TOKEN'];
	$recurringPayment['DESC'] = $agreement['L_BILLINGAGREEMENTDESCRIPTION0'];
	$recurringPayment['EMAIL'] = $agreement['EMAIL'];
	$recurringPayment['AMT'] = 0.99;
	$recurringPayment['INITAMT'] = 0.99;
	$recurringPayment['CURRENCYCODE'] = 'EUR';
	$recurringPayment['BILLINGFREQUENCY'] = 1;
	$recurringPayment['PROFILESTARTDATE'] = date(DATE_ATOM);
	$recurringPayment['BILLINGPERIOD'] = Api::BILLINGPERIOD_DAY;
```
	
4) I run the following actions CreateRecurringPaymentProfile, Sync, and GetHumanStatus.
5) I return the status of the recurringPayment

Thank you so much for your help.

**Comment by frechina** [comment]
> "CHECKOUTSTATUS" : "PaymentActionNotInitiated", means you have not visited the PayPal side and haven't confirmed the agreement.

BTW the agreement is confirmed. The problem is that the status of the payment is not updated after agreement confirmation and after recurringPayment creation

**Comment by frechina** [comment]
After some research I found that if I remove INITAMT of the recurring payment then I get a status Capture, although I still getting PaymentActionNotInitiated in CHECKOUTSTATUS.

I need INITAMT so please if someone can help me to avoid Pending status when using INITAMT. 
Thank you

**Comment by ansien12** [comment]
Having a similair problem, when I do ```$gateway->execute(new Cancel($recurringPayment));``` nothing happens because there is no transaction id.

**Comment by frechina** [comment]
> "CHECKOUTSTATUS" : "PaymentActionNotInitiated", means you have not visited the PayPal side and haven't confirmed the agreement.

with `"PAYMENTREQUEST_0_PAYMENTACTION" : "Sale"` the `CHECKOUTSTATUS` is always `PaymentActionNotInitiated` even though you visited the paypal site and confirmed the agreement

**Comment by frechina** [comment]
I continue with this issue, I don't know why this is closed.

**Comment by ansien12** [comment]
Having the exact same problem atm.

`"CHECKOUTSTATUS" => "PaymentActionNotInitiated"`

Using https://github.com/Payum/Payum/blob/master/docs/paypal/express-checkout/get-it-started.md

**Comment by kubaceg** [comment]
Did anybody fix this? I have same problem with authorization on pp sandbox mode. 

```
{
    "ACK": "Success",
    "AMT": "30.00",
    "DESC": "Zeremi - payment for ad: New user ad",
    "BUILD": "43715881",
    "EMAIL": "client@gmail.com",
    "TOKEN": "EC-7TM97493R86977335",
    "INVNUM": "5a99c98e85b8b",
    "TAXAMT": "0.00",
    "ITEMAMT": "30.00",
    "PAYERID": "643SFE2DDXXWS",
    "VERSION": "65.1",
    "LASTNAME": "Ce",
    "CANCELURL": "http://symfony.local/payment/authorize/9tGLArcpCAPP3gCD18aYqXgdSYi2J_HASwAEo0xHRBQ?cancelled=1",
    "FIRSTNAME": "Jakub",
    "NOTIFYURL": "http://symfony.local/payment/notify/3xOud9qFVIB6_u3nn5uyIA3nzIz-knfIVUMnoRxkX9A",
    "RETURNURL": "http://symfony.local/payment/authorize/9tGLArcpCAPP3gCD18aYqXgdSYi2J_HASwAEo0xHRBQ",
    "SHIPTOZIP": "00800",
    "TIMESTAMP": "2018-03-02T22:01:35Z",
    "SHIPTOCITY": "Warszawa",
    "SHIPTONAME": "Jakub Ce",
    "COUNTRYCODE": "PL",
    "HANDLINGAMT": "0.00",
    "PAYERSTATUS": "verified",
    "SHIPDISCAMT": "0.00",
    "SHIPPINGAMT": "0.00",
    "CURRENCYCODE": "EUR",
    "INSURANCEAMT": "0.00",
    "L_ERRORCODE0": "10001",
    "SHIPTOSTREET": "Bajkowa 2 / 5,",
    "ADDRESSSTATUS": "Confirmed",
    "CORRELATIONID": "a976d87aad492",
    "SHIPTOSTREET2": "Case postale 12",
    "CHECKOUTSTATUS": "PaymentActionNotInitiated",
    "L_LONGMESSAGE0": "Internal Error",
    "L_SEVERITYCODE0": "Error",
    "L_SHORTMESSAGE0": "Internal Error",
    "SHIPTOCOUNTRYCODE": "PL",
    "SHIPTOCOUNTRYNAME": "Poland",
    "PAYMENTREQUEST_0_AMT": "30.00",
    "PAYMENTREQUEST_0_DESC": "desc",
    "INSURANCEOPTIONOFFERED": "false",
    "PAYMENTREQUEST_0_TAXAMT": "0.00",
    "PAYMENTREQUEST_0_ITEMAMT": "30.00",
    "AUTHORIZE_TOKEN_USERACTION": "commit",
    "PAYMENTREQUEST_0_NOTIFYURL": "http://symfony.local/payment/notify/3xOud9qFVIB6_u3nn5uyIA3nzIz-knfIVUMnoRxkX9A",
    "PAYMENTREQUEST_0_SHIPTOZIP": "00800",
    "PAYMENTREQUEST_0_SHIPTOCITY": "Warszawa",
    "PAYMENTREQUEST_0_SHIPTONAME": "Jakub Ce",
    "PAYMENTREQUEST_0_HANDLINGAMT": "0.00",
    "PAYMENTREQUEST_0_SHIPDISCAMT": "0.00",
    "PAYMENTREQUEST_0_SHIPPINGAMT": "0.00",
    "SUCCESSPAGEREDIRECTREQUESTED": "false",
    "PAYMENTREQUEST_0_CURRENCYCODE": "EUR",
    "PAYMENTREQUEST_0_INSURANCEAMT": "0.00",
    "PAYMENTREQUEST_0_SHIPTOSTREET": "Bajkowa 2 / 5,",
    "BILLINGAGREEMENTACCEPTEDSTATUS": "0",
    "PAYMENTREQUESTINFO_0_ERRORCODE": "0",
    "PAYMENTREQUEST_0_ADDRESSSTATUS": "Confirmed",
    "PAYMENTREQUEST_0_PAYMENTACTION": "Authorization",
    "PAYMENTREQUEST_0_SHIPTOSTREET2": "Case postale 12",
    "PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE": "PL",
    "PAYMENTREQUEST_0_SHIPTOCOUNTRYNAME": "Poland",
    "PAYMENTREQUEST_0_SELLERPAYPALACCOUNTID": "test@gmail.com",
    "PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED": "false"
}
```

**Comment by makasim** [comment]
The Payal sandbox does not work from time to time, that's expected. Try again after a while
