### ISSUE TITLE
Create recurring profile using Paypal rest

### ISSUE THREAD

**Issue by narendra-addweb** [Payum/Payum#655]
Hi team payum,

I'm using [Paypal Rest](https://github.com/Payum/Payum/blob/master/docs/paypal/rest/get-it-started.md) to create recurring profile with payment by credit card. I followed the given example of [prepare.php](https://github.com/Payum/Payum/blob/master/docs/paypal/rest/get-it-started.md), [capture.php](https://github.com/Payum/Payum/blob/master/docs/examples/capture-script.md) and [done.php](https://github.com/Payum/Payum/blob/master/docs/examples/done-script.md).

I'm confused here that where I need to pass the number of cycle/period...all require parameter for recurring? Please help.

**Comment by makasim** [comment]
I've never done it myself so I can not help.

**Comment by narendra-addweb** [comment]
@makasim: Thanks for reply, is there any way/example/link/reference for the same which help me out here?

**Comment by makasim** [comment]
I am not aware of any. The thing is Payum Rest does not provide any abstractions over the sdk library. It uses the models from sdk as well. So an examples for Paypal Rest SDK will work for payum paypal rest as well (with slight adjustments) .
