### ISSUE TITLE
Why I gets empty firstModel (in the extension) when gateway call notify action...?

### ISSUE THREAD

**Issue by roquie** [Payum/Payum#656]
[I develop new gateway](https://github.com/tmconsulting/payum-uniteller-gateway) for Payum and I have a little problem.

When gateway sent callback request to `notify` action, I simply run this like as Sylius [bundle](https://github.com/Payum/PayumBundle/blob/master/Controller/NotifyController.php#L10)

```php
try {
    $gateway = $this->getPayum()->getGateway($gatewayName);
    $gateway->execute(new Notify(null));

    return $this->responseFactory->make(null, 204);
} catch (ReplyInterface $reply) {
    return $this->converter->convert($reply);
}
```

Next, I write code like Be2bill with two actions: `NotifyNullAction` ([link](https://github.com/tmconsulting/payum-uniteller-gateway/blob/master/src/Action/TokenExtraWorkaround/NotifyNullAction.php)) and `NotifyAction` ([link](https://github.com/tmconsulting/payum-uniteller-gateway/blob/master/src/Action/NotifyAction.php)). 

It works! But after... I would like to update payment record in the database. Create extension`UpdateStatusExtension` and him I associate with the library (`payum.extension.update_payment_status`).

```php
 public function onPostExecute(Context $context)
    {
        if ($context->getPrevious()) {
            return;
        }
        /** @var Generic $request */
        $request = $context->getRequest();
        if (false === $request instanceof Generic || $request instanceof GetStatusInterface) {
            return;
        }
        
        dump($request);
        
        $payment = $request->getFirstModel();
        if ($payment instanceof PaymentInterface) {
            /* @var Payment $payment */
            $status = new GetHumanStatus($payment);
            $context->getGateway()->execute($status);
            if ($payment instanceof PaymentStatus) {
                $payment->setStatus($status->getValue());
            }
        }
    }
```

`dump($request)` returns `Notify` core object with empty firstModel property. 

![screen shot 2017-05-12 at 12 49 51](https://cloud.githubusercontent.com/assets/3214290/25993146/c5498684-3711-11e7-8680-a7f0c61f79bd.png)

If I `dump` all executed requests (`onExecute` method), I receive filled `Notify` objects for all calls.

https://jsfiddle.net/z7mq9omp/

I don't understand why firstModel is null and how to fix this problem. I so long understood with problem and I don't see correct solution. Need your help.

P.S. I speak Russian and may be I can to clarify this issue more better for understanding?

**Comment by roquie** [comment]
May be I asked something wrong?

**Comment by makasim** [comment]
The firstModel is set here https://github.com/Payum/Payum/blob/ab6723e851b9d7452f65a721e124495e81caafc1/src/Payum/Core/Request/Generic.php#L82. 


The request may be executed several times with different models. First, it could be the token, then an identity and only after that one it could become a real model. 

So if you never set a model `new Notify(null)` you will not have it.

**Comment by roquie** [comment]
What I should I do? How I can update model with library workflow without workarounds (of course for gateways which is not support dynamic callbacks-urls)?

**Comment by makasim** [comment]
You can set the first model inside NotifyNullAction. You fetch it by some parameter from db in any case.

**Comment by roquie** [comment]
Like as in my readme?
https://github.com/tmconsulting/payum-uniteller-gateway

**Comment by roquie** [comment]
What difference between `new Notify($token)` inside `NotifyNullAction` and `new Notify($token)` inside `PaymentController`? Why second variant may fill payment object (he is implement `PaymentInterface`) and payment record may be updatetable using `UpdateStatusExtension` class. But `new Notify($token)` runned inside `NotifyNullAction` not works properly? It's strange behavior.

**Comment by makasim** [comment]
> But new Notify($token) runned inside NotifyNullAction not works properly? It's strange behavior.

It must work

**Comment by makasim** [comment]
Last time I tested it it worked https://github.com/Payum/Payum/blob/master/src/Payum/Be2Bill/Action/NotifyNullAction.php#L42

**Comment by makasim** [comment]
you can try to see what is going on in the profiler. there is execution tree

**Comment by roquie** [comment]
https://github.com/tmconsulting/payum-uniteller-gateway/blob/master/src/Action/TokenExtraWorkaround/NotifyNullAction.php#L36
I got token and pass arg to `NotifyNullAction action`, `$getToken->getToken()` output:
![screen shot 2017-06-09 at 12 29 42](https://user-images.githubusercontent.com/3214290/26969591-f6d5c92a-4d0e-11e7-9903-63a0a73c3e16.png)

After that, request reached to `NotifyAction`, I replace model with `ArrayObject` and now she have with payment info:
![screen shot 2017-06-09 at 12 37 18](https://user-images.githubusercontent.com/3214290/26969841-d17a4808-4d0f-11e7-8659-ae6153342e11.png)

Third I checked extension and can't to see filled payment object:
![screen shot 2017-06-09 at 12 40 51](https://user-images.githubusercontent.com/3214290/26969981-523fa9f6-4d10-11e7-9889-eaa9e530fdc2.png)

If I set the model inside `NotifyNullAction` (`$request->setModel($httpRequest->request);`), I got
![screen shot 2017-06-09 at 12 42 09](https://user-images.githubusercontent.com/3214290/26970025-82582118-4d10-11e7-8197-ee9f4b280ffa.png)

Sure, is not an implementation of PaymentInterface...

> "you can try to see what is going on in the profiler. there is execution tree"
I will try it

**Comment by makasim** [comment]
Any news?

**Comment by roquie** [comment]
Oh, first project which was written without this library still works 😅  Version 2 was written too (with this library) and still in "development status". Now payment gate will re-written again where microservices. 😄 Okay, I close this issue.
