### ISSUE TITLE
Ecrypting Configuration in the backend

### ISSUE THREAD

**Issue by liamsorsby** [Payum/Payum#659]
I've just been reading the PayumBundle docs and cannot seem to find any configuration reference for encrypting the db as per the standalone payum bundle: https://github.com/Payum/Payum/blob/master/docs/encrypt-gateway-configs-stored-in-database.md

Has this been implemented already for PayumBundle or is this feature not available yet?

**Comment by makasim** [comment]
The bundle supports it: https://github.com/Payum/PayumBundle/pull/417

**Comment by liamsorsby** [comment]
Great, thank you. Does the configs need to be re-saved when this option is added?

**Comment by makasim** [comment]
I advise you to do that though it is not required. The not encrypted data will be encrypted whenever updated.

**Comment by liamsorsby** [comment]
I've checkout your commit, but I'm not using sonata admin for the configuration of the backend.

Is there a service that payum has internally to save/handle the backend so I can use the payum settings to automatically encrypt the data saved to the Storage. They way I am currenctly saving the backend config doesn't know anything about payum and acts independently.

**Comment by makasim** [comment]
You do not need sonata admin to use the feature. You have to add config like there https://github.com/Payum/PayumBundle/pull/417 to make it work while processing payments.

For the backend, you have to call encrypt\decrypt method manually. There must be events or hooks for the gateway config model. 

Like this https://github.com/Payum/PayumBundle/blob/master/Sonata/GatewayConfigAdmin.php#L74

``

**Comment by makasim** [comment]
Has it been solved?

**Comment by liamsorsby** [comment]
Hi Makasim,

I've not had cance to even look at this to be honest. I will close the issue and if I require any further assistance I will drop you a message. Thank you again for your time.

Kind Regards,
Liam
