### ISSUE TITLE
Cancel recurring paypal express

### ISSUE THREAD

**Issue by ansien12** [Payum/Payum#660]
Having a problem when i try to cancel a recurring paypal payment. 

When I do ```$gateway->execute(new Cancel($recurringPayment));``` nothing happens. I tried tracing the root of the problem and in ```ExpressCheckout/Nvp/Action\CancelAction.php``` there are these lines of code:

```
if (!$details['TRANSACTIONID']) {
    return;
}
```

A recurring payment will never have a transaction ID. So how is this supposed to work? Are the [docs](https://github.com/Payum/Payum/blob/master/docs/paypal/express-checkout/cancel-recurring-payment.md) wrong?

**Comment by dincho** [comment]
I stumbled across the same issue recently. It looks like to me that indeed the docs are wrong.
Currently implemented Cancel action does not handle recurring payments.

I'm using below code to cancel a recurring payment, however an new action would be better:

```php
        $gateway->execute(new ManageRecurringPaymentsProfileStatus([
            'PROFILEID' => $subscription['PROFILEID'],
            'ACTION' => 'Cancel',
        ]));
```

**Comment by dincho** [comment]
Here is the action I just implemented, I'm not sure if reusing the core Cancel request is good idea 🤔

```php
<?php

namespace AppBundle\Payment\Payum\Action;

use Payum\Core\Action\ActionInterface;
use Payum\Core\Bridge\Spl\ArrayObject;
use Payum\Core\Exception\RequestNotSupportedException;
use Payum\Core\GatewayAwareInterface;
use Payum\Core\GatewayAwareTrait;
use Payum\Core\Request\Cancel;
use Payum\Core\Request\Sync;
use Payum\Paypal\ExpressCheckout\Nvp\Request\Api\ManageRecurringPaymentsProfileStatus;

class CancelRecurringPaymentAction implements ActionInterface, GatewayAwareInterface
{
    use GatewayAwareTrait;

    /**
     * {@inheritDoc}
     */
    public function execute($request)
    {
        /** @var $request Cancel */
        RequestNotSupportedException::assertSupports($this, $request);

        $details = ArrayObject::ensureArrayObject($request->getModel());

        if (!$details['PROFILEID']) {
            return;
        }

        $cancelDetails = new ArrayObject([
            'PROFILEID' => $details['PROFILEID'],
            'ACTION' => 'Cancel',
        ]);

        $this->gateway->execute(new ManageRecurringPaymentsProfileStatus($cancelDetails));
        $this->gateway->execute(new Sync($request->getModel()));
    }

    /**
     * {@inheritDoc}
     */
    public function supports($request)
    {
        return
            $request instanceof Cancel &&
            $request->getModel() instanceof \ArrayAccess
        ;
    }
}
```

I could try finding some spare time to prepare PR if the maintainers are interested.

**Comment by makasim** [comment]
>  I'm not sure if reusing the core Cancel request is a good idea

That is valid use case. The request only defines the purpose.  The request model (context) is defines the way the cancel will be done.

**Comment by makasim** [comment]
> I could try find some spare time to prepare PR if the maintainers are interested.

I am looking forward to it

**Comment by dincho** [comment]
@makasim It looks like such action [already exists](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/CancelRecurringPaymentsProfileAction.php), it's also registered in the factory. However for some reason it seems it's not executed during my testing. Any idea what to look for?

**Comment by makasim** [comment]
@dincho I'd start from the payum's debug command. And look for that action if it was loaded or not.
Then I'd debug the action's `support` method to see why it is not working. There is also a profiler extension which shows an execution plan, could be in help too.

**Comment by dincho** [comment]
@makasim I did. The weird thing is that the action is associated with the gateway (during debug command) but it's support method is never called. I'm not familiar with the lib behaviour, does it stop the request once the first action match? This might be the issue because the transaction only Cancel action is registered before recurring profile cancel action.

```
paypal (Payum\Core\Gateway):
	Actions:
	AppBundle\Payment\Payum\Action\StoreNotificationAction
	AppBundle\Payment\Payum\Action\CancelRecurringPaymentsProfileAction
--- snip
	Payum\Paypal\ExpressCheckout\Nvp\Action\CaptureAction
	Payum\Paypal\ExpressCheckout\Nvp\Action\CancelAction
	Payum\Paypal\ExpressCheckout\Nvp\Action\AuthorizeAction
--- snip
	Payum\Paypal\ExpressCheckout\Nvp\Action\Api\GetRecurringPaymentsProfileDetailsAction
	Payum\Paypal\ExpressCheckout\Nvp\Action\Api\CancelRecurringPaymentsProfileAction
	Payum\Paypal\ExpressCheckout\Nvp\Action\Api\ManageRecurringPaymentsProfileStatusAction
--- snip

```

**Comment by makasim** [comment]
Maybe there is another action that says it supports the action.

**Comment by dincho** [comment]
> Maybe there is another action that says it supports the action.

Yep, the transaction [Cancel action](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php) kick in because of weak support method.

I modified it and now the correct cancel action is executed. @makasim Please let me know if you see any issues with this, otherwise I'll create bug fix PR for transaction Cancel action:
```php
    /**
     * {@inheritDoc}
     */
    public function execute($request)
    {
        /** @var $request Cancel */
        RequestNotSupportedException::assertSupports($this, $request);

        $details = ArrayObject::ensureArrayObject($request->getModel());

        $voidDetails = new ArrayObject([
            'AUTHORIZATIONID' => $details['TRANSACTIONID'],
        ]);

        $this->gateway->execute(new DoVoid($voidDetails));
        $this->gateway->execute(new Sync($request->getModel()));
    }

    /**
     * {@inheritDoc}
     */
    public function supports($request)
    {
        if (false == ($request instanceof Cancel && $request->getModel() instanceof \ArrayAccess)) {
            return false;
        }

        // it must take into account only common payments, recurring payments must be cancelled by another action.
        $model = $request->getModel();
        return isset($model['TRANSACTIONID']);
    }
```

**Comment by makasim** [comment]
Looks good
