### ISSUE TITLE
Request GetHumanStatus{model: ArrayObject} is not supported.

### ISSUE THREAD

**Issue by shoaibgits** [Payum/Payum#661]
Using the Sofort Method on my project all the configuration is done now at the capture step it gives error as 
     `Request GetHumanStatus{model: ArrayObject} is not supported.`

My config file is as:
        ` 'sofort' => $sofortFactory->create(array(
                'factory' => 'sofort',
                'config_key' => 'foo',
            )),`

And Controller is looks like:

    public function sofortAction()
            {
    $storage = $this->getServiceLocator()->get('payum')->getStorage('Reisesparer\Model\SofortueberWeisung');

    $payment = $storage->create();

    $payment->setNumber(uniqid());
    $payment->setCurrencyCode('EUR');
    $payment->setTotalAmount(123); // 1.23 EUR
    $payment->setDescription('A description');
    $payment->setClientId('anId');
    $payment->setClientEmail('foo@example.com');

    $storage->update($payment);

    $captureToken = $this->getServiceLocator()->get('payum.security.token_factory')->createCaptureToken(
        'sofort', $payment, 'payment_done'
    );
    $this->redirect()->toUrl($captureToken->getTargetUrl());
     }

And Model has the following code:

          <?php
              namespace Reisesparer\Model;

              use Payum\Core\Model\Payment;

              class SofortueberWeisung extends Payment
                {
	            protected $id;
                 }

**Comment by makasim** [comment]
The action is [there](https://github.com/Payum/Payum/blob/master/src/Payum/Sofort/SofortGatewayFactory.php#L33) and last time I tested in the [sandbox](https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaymentBundle/Controller/SimplePurchaseSofortController.php) it worked (half a year ago). I cannot recall any change that could broker it.


So, most likely you configured something wrongly

**Comment by makasim** [comment]
The status action supports: https://github.com/Payum/Payum/blob/master/src/Payum/Sofort/Action/StatusAction.php#L83

**Comment by makasim** [comment]
try to debug this method findActionSupported

**Comment by shoaibgits** [comment]
I have print the capture token and got the array:

      Reisesparer\Model\PaymentSecurityToken Object
       (
       [details:protected] => Payum\Core\Model\Identity Object
       (
       [class:protected] => Reisesparer\Model\SofortueberWeisung
       [id:protected] => 5932894bbe235
       )

    [hash:protected] => 0lhhrs0IWtZqHeQ8arABNz2-ORdVNHMkPYjh7azbV0M
    [afterUrl:protected] => http://localhost:8088/payment/done/NbUdwDbCVNuI-sHrNd_LBCBjySQdFEfShx51MWZQ_Kc
    [targetUrl:protected] => http://localhost:8088/payment/capture/0lhhrs0IWtZqHeQ8arABNz2-ORdVNHMkPYjh7azbV0M
    [gatewayName:protected] => sofort
     )
But after capture the token it redirect to targetUrl(); it gave me this error:

   Request GetHumanStatus{model: ArrayObject} is not supported.

   `#0 C:\xampp\htdocs\reisenmasrer_udpated\vendor\payum\payum\src\Payum\Core\Gateway.php(99): Payum\Core\Exception\RequestNotSupportedException::create(Object(Payum\Core\Request\GetHumanStatus))
    #1 C:\xampp\htdocs\reisenmasrer_udpated\vendor\payum\payum\src\Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction.php(32): Payum\Core\Gateway->execute(Object(Payum\Core\Request\GetHumanStatus))
    #2 C:\xampp\htdocs\reisenmasrer_udpated\vendor\payum\payum\src\Payum\Core\Gateway.php(107): Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction->execute(Object(Payum\Core\Request\GetHumanStatus))
    #3 C:\xampp\htdocs\reisenmasrer_udpated\vendor\payum\payum\src\Payum\Core\Action\CapturePaymentAction.php(25): Payum\Core\Gateway->execute(Object(Payum\Core\Request\GetHumanStatus))
    #4 C:\xampp\htdocs\reisenmasrer_udpated\vendor\payum\payum\src\Payum\Core\Gateway.php(107): Payum\Core\Action\CapturePaymentAction->execute(Object(Payum\Core\Request\Capture))
    #5 C:\xampp\htdocs\reisenmasrer_udpated\vendor\payum\payum\src\Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction.php(32): Payum\Core\Gateway->execute(Object(Payum\Core\Request\Capture))
    #6 C:\xampp\htdocs\reisenmasrer_udpated\vendor\payum\payum\src\Payum\Core\Gateway.php(107): Payum\Core\Action\ExecuteSameRequestWithModelDetailsAction->execute(Object(Payum\Core\Request\Capture))
    #7 C:\xampp\htdocs\reisenmasrer_udpated\vendor\payum\payum-module\src\Payum\PayumModule\Controller\CaptureController.php(19): Payum\Core\Gateway->execute(Object(Payum\Core\Request\Capture))
   #8 C:\xampp\htdocs\reisenmasrer_udpated\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Payum\PayumModule\Controller\CaptureController->doAction()
   #9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
   #10 C:\xampp\htdocs\reisenmasrer_udpated\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
   #11 C:\xampp\htdocs\reisenmasrer_udpated\vendor\zendframework\zend-eventmanager\src\EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
   #12 C:\xampp\htdocs\reisenmasrer_udpated\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
   #13 C:\xampp\htdocs\reisenmasrer_udpated\vendor\zendframework\zend-mvc\src\DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
   #14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
   #15 C:\xampp\htdocs\reisenmasrer_udpated\vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
   #16 C:\xampp\htdocs\reisenmasrer_udpated\vendor\zendframework\zend-eventmanager\src\EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
   #17 C:\xampp\htdocs\reisenmasrer_udpated\vendor\zendframework\zend-mvc\src\Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
   #18 C:\xampp\htdocs\reisenmasrer_udpated\public\index.php(24): Zend\Mvc\Application->run()
   #19 {main}`

**Comment by makasim** [comment]
This looks strange: 

```
C:\xampp\htdocs\reisenmasrer_udpated\vendor\payum\payum-module\src\Payum\PayumModule\Controller\CaptureController.php(19): Payum\Core\Gateway->execute(Object(Payum\Core\Request\Capture)) #8 
```

the stack trace you posted have calls to core factory method but there is no one to https://github.com/Payum/Payum/blob/master/src/Payum/Sofort/SofortGatewayFactory.php

But it must be used in your case

**Comment by shoaibgits** [comment]
my global.php in zend framework2 is like follows.

            use Buzz\Client\Curl;
            use Payum\Core\Extension\StorageExtension;
            use Payum\Core\Storage\FilesystemStorage;
            use Payum\Paypal\ExpressCheckout\Nvp\PaypalExpressCheckoutGatewayFactory;
            use Payum\Stripe\StripeJsGatewayFactory;
            use Payum\Sofort\SofortGatewayFactory;
            use Payum\AuthorizeNet\Aim\AuthorizeNetAimGatewayFactory;

            $paypalFactory = new PaypalExpressCheckoutGatewayFactory();
            $stripeFactory = new StripeJsGatewayFactory();
            $sofortFactory = new SofortGatewayFactory();
            $authorizedFactory = new AuthorizeNetAimGatewayFactory();

            $paymentClass = 'Reisesparer\Model\SofortueberWeisung';
            $detailsClass = 'Reisesparer\Model\PaymentDetails';

            return array(
                // ...
                'db' => array(
                    'driver'         => 'Pdo',
                    'dsn'            => 'mysql:dbname=reisenupdated;host=localhost',
                    'driver_options' => array(
                        PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
                    ),
                ),
                'service_manager' => array(
                    'factories' => array(
                        'Zend\Db\Adapter\Adapter'
                        => 'Zend\Db\Adapter\AdapterServiceFactory',
                    ),
                ),
                'doctrine' => array(
                    'connection' => array(
                        'orm_default' => array(
                            'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                            'params' => array(
                                'host'     => 'localhost',
                                'port'     => '3306',
                            )
                        )
                    )
                ),

                'payum' => array(
                    'token_storage' => new FilesystemStorage(
                        __DIR__.'/../../data',
                        'Reisesparer\Model\PaymentSecurityToken',
                        'hash'
                    ),
                    'gateways' => array(
                        
                        'sofort' => $sofortFactory->create(array(
                            'factory' => 'sofort',
                            'config_key' => '12345:12345:5dbdad2bc861d907eedfd9528127d002',
                        )),
                    ),
                    'storages' => array(
                        $detailsClass => new FilesystemStorage(__DIR__.'/../../data', $detailsClass, 'id'),
                        $paymentClass => new FilesystemStorage(__DIR__.'/../../data', $paymentClass, 'id'),
                    )
                ),`

**Comment by shoaibgits** [comment]
Also i have traced to vendor\payum\payum\src\Payum\Core\Action\CapturePaymentAction.php

and print the $payment so it give me result the same i have request from the controller method as follows:

    Reisesparer\Model\SofortueberWeisung Object
    (
    [id:protected] => 5932a91fbf88e
    [number:protected] => 5932a91fbf879
    [description:protected] => A description
    [clientEmail:protected] => foo@example.com
    [clientId:protected] => anId
    [totalAmount:protected] => 123
    [currencyCode:protected] => EUR
    [details:protected] => Array
        (
            [notification_url] => https://google.com
        )

    [creditCard:protected] => 
    )

**Comment by makasim** [comment]
I have tested it in the [sandbox](https://github.com/makasim/PayumBundleSandbox). It works fine. 

* The payment model: https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaymentBundle/Entity/Payment.php
* The prepare action code: https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaymentBundle/Controller/SimplePurchaseSofortController.php#L17
* Done action code: https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaymentBundle/Controller/DetailsController.php#L27

Please look at the code and match with yours. You did something incorrectly.
