### ISSUE TITLE
Paypal Express Checkout not Showing the Order summery

### ISSUE THREAD

**Issue by shoaibgits** [Payum/Payum#662]
$storage = $this->getServiceLocator()->get('payum')->getStorage('Reisesparer\Model\PaymentDetails');
     $details = $storage->create();
     $details['PAYMENTREQUEST_0_CURRENCYCODE'] = 'EUR';
     $details['PAYMENTREQUEST_0_AMT'] = $request->getPost('grandtotal_price');
     $details['ORDER_CUSTOM_ID'] = $orderNumber;
     $storage->update($details);
     $captureToken =    this->getServiceLocator()->get('payum.security.token_factory')->createCaptureToken(               this->redirect()->toUrl($captureToken->getTargetUrl().'?amout='.$details['PAYMENTREQUEST_0_AMT']);
![no-summery](https://cloud.githubusercontent.com/assets/26060844/26825578/188008b6-4acf-11e7-92ab-fb20f95c6c78.png)

**Comment by makasim** [comment]
You have to add those options to the payment details yourself.  Payum does not do any assumptions on this. 

https://github.com/makasim/PayumBundleSandbox/blob/master/src/Acme/PaypalExpressCheckoutBundle/Controller/PurchaseExamplesController.php#L215

**Comment by shoaibgits** [comment]
Thanks For the Response It solved the issue :)
