### ISSUE TITLE
Notify request - response content

### ISSUE THREAD

**Issue by dincho** [Payum/Payum#666]
Some payment processors e.g. Dotpay require specific response content (in this case "OK") to acknowledge successful callback.

To accomplish this I think it would be reasonable to add "responseContent" property of [Notify request](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Request/Notify.php), so that it can be used in [NotifyControllers](https://github.com/Payum/PayumBundle/blob/master/Controller/NotifyController.php#L27).

Each gateway would then be able to set the specific response in their action [e.g. Dotpay](https://github.com/pixers/payum-dotpay/blob/master/src/Pixers/Payum/Dotpay/Action/NotifyAction.php#L26)

I'm willing to prepare PR's if you think this solution is acceptable.

**Comment by dincho** [comment]
Current workaround is to replace the [NotifyController](https://github.com/Payum/PayumBundle/blob/master/Controller/NotifyController.php#L27), which I don't like.

**Comment by makasim** [comment]
You can send a reply when you are done. For example, Redsys require an empty response with 200 status. The bundle returns  204 by default. 

https://github.com/crevillo/payum-redsys/blob/master/Action/NotifyAction.php#L70

**Comment by dincho** [comment]
> You can send a reply when you are done. For example, Redsys require an empty response with 200 status. The bundle returns 204 by default.
> 
> https://github.com/crevillo/payum-redsys/blob/master/Action/NotifyAction.php#L70

Ah, I see. Thank you very much!
