### ISSUE TITLE
[Sofort] Cancellation is not handled

### ISSUE THREAD

**Issue by Tykzz** [Payum/Payum#669]
I'm integrating Payum Sofort payments with Sylius and have come across a problem with cancellation - https://github.com/Sylius/Sylius/issues/8269. After cancelling the payment on the Sofort page it goes to the same URL as the target URL. In the Paypal implementation it has additional parameter `cancelled=1` which results in changing the payment status to `cancelled`. Shouldn't the same be implemented in Sofort integration?

**Comment by lasotaartur** [comment]
I have this same problem

**Comment by makasim** [comment]
why not?  If it is possible 

PR is welcome

**Comment by Tykzz** [comment]
What would be the best way to implement it?
Would it suffice to set the `abort_url` as the target URL with `cancelled` parameter and mark the payment as cancelled when it's visited?

**Comment by makasim** [comment]
Sounds reasonable though I cannot say for sure I haven't worked with Sofort for quite some time.
