### ISSUE TITLE
[Sofort] Pending status marks the payment as captured

### ISSUE THREAD

**Issue by Tykzz** [Payum/Payum#670]
Maybe I'm missing something but it's confusing. In the `StatusAction` for Sofort integration it sets the payment as captured (instead of pending) when the Sofort status is `pending`. Should it be that way? If so why is that?

https://github.com/Payum/Payum/blob/master/src/Payum/Sofort/Action/StatusAction.php

```php
// ...
switch ($details['status']) {
            case Api::STATUS_LOSS:
                $request->markFailed();
                break;
            case Api::STATUS_PENDING:
                $request->markCaptured();
                break;
// ...
```

**Comment by makasim** [comment]
It looks like a bug, could you please send a fix?
