### ISSUE TITLE
Update OmnipayBridge to Support Symfony 3.*

### ISSUE THREAD

**Issue by dpfaffenbauer** [Payum/Payum#675]
Hi,

OmnipayBridge currently doesn't support Symfony 3 applications. The reason is the dependency to omnipay/common:^2.3 which has a dependency to symfony/http-foundation: ~2.1 and therefore conflicts with Symfony 3.*

Omnipay/Common already released a Alpha Version where they use symfony/http-foundation:^2.1|^3.

If you could do the same with the OmnipayBridge, it would work again.

Cheers

**Comment by makasim** [comment]
Easier said than done. It would require extensive testing and changes checking before we can raise the supported version.

**Comment by makasim** [comment]
There might be some BC breaks as well.

**Comment by dpfaffenbauer** [comment]
Thats right.

Regardless BC breaks, Omnipay drivers have a dependency on omnipay/common:~2 as well. For example Worldpay: https://github.com/thephpleague/omnipay-worldpay/blob/master/composer.json

So, this is much more far-reaching than first thought.

**Comment by makasim** [comment]
I am not up to the task cuz I do not work with omnipay at the moment. Though if someone willing to contribute I do my best to review it and get it merged.

**Comment by dpfaffenbauer** [comment]
I have to correct the issue description: Problem appear cause of older guzzle version.

I am working on a fix, but as already said: this is gonna be BC break, therefore I would consider this as OmnipayBridge 2?

Here is what I came up with.

#### OmnipayBridge
Integrates new omnipay/common lib **BC break here**  (in OmnipayGatewayFactory: removed first argument, cause Omnipay doesn't tell us which gateways are available anymore, you'll find this in PayumCore (PayumBuilder) as well)
https://github.com/dpfaffenbauer/OmnipayBridge/commit/8e7c59912de73b19a70c7f913756b9995363294a
This removes deprecated classes (since this is a BC anyway, I thought we could remove them as well): https://github.com/dpfaffenbauer/OmnipayBridge/commit/4a9b160957adde6cd450697f5ff8f3e3c9b53afa

#### Payum Core
This integrates the Omnipay Gateways: https://github.com/dpfaffenbauer/Payum/commit/11b684bf2949cd39752d9e5dd17e40a7db3d876c. Here is also where the BC happens, since Omnipay removed "getSupportedGateways", we don't know about installed gateways anymore and can't register a Factory for every type. Therefore I removed the stuff and changed OmnipayGatewayFactory in OmnipayBridge as well. But: since Payum only creates this BC when the Bridge is available, I would consider this only a BC for the Bridge. What do you think?

As soon as this PR (https://github.com/thephpleague/omnipay-dummy/pull/6) gets merged and Alpha-3 gets released, I am gonna create PR's for this issue.

**Comment by makasim** [comment]
I am fine with it. Looks like we are on the safe side and we have to raise only the bridge's major version. 

Good job!

**Comment by dpfaffenbauer** [comment]
I guess we can close this now.
