### ISSUE TITLE
Gateway is null

### ISSUE THREAD

**Issue by Bencsi** [Payum/Payum#677]
I started develop a new custom gateway based on skeleton for a Sylius webshop, i would like to access $this->gateway in ConvertPaymentAction but this is null, any idea why? My goal is access payum configuration for my custom gateway what stored in config.yml in my shop.

**Comment by makasim** [comment]
Have you implemented GatewayAwareInterface on the action?

**Comment by Bencsi** [comment]
@makasim That way the problem thanks. But how can I access my gateway config stored in config.yml?

The relevant part in my config.yml, I would like to access "mids" from action 
`payum:
    gateways:
        khb:
            factory: khb
            mids: '%kh_mids%'`

**Comment by makasim** [comment]
create a service that fetch that data. 

* tag it as payum api for this particular gateway and then inject it using ApiAwareInterface. 
* or tag it as payum action and do sub request (in payum's terms) to that to fetch that data.
