### ISSUE TITLE
Load action order bug in symfony application

### ISSUE THREAD

**Issue by webmake** [Payum/Payum#683]
Hello, seems it is bug which depends on how you registering actions, let's say taking this bundle as an example: https://github.com/umbrellalimited/payum-przelewy24-bunde, there I made small change in `Przelewy24OffsiteGatewayFactory` to reproduce bug, by adding on 20line action
```
            $config['payum.default_options'] = [
                'clientId' => null,
                'clientSecret' => null,
                'sandbox' => true,
                'payum.action.capture_offsite' => new \Umbrella\PayumPrzelewy24Bundle\Action\CaptureOffsite(),
            ];
```
Now here is the example how actions are loaded:
![default_style](https://user-images.githubusercontent.com/5016464/30313904-a18efafc-97a7-11e7-958e-c9b2ab5616f7.PNG)

But when adding in yml such code:
```
payum:
    gateways:
        przelewy24:
                payum.action.capture_offsite: '@app.payment.przelewy24.capture_offsite'
```
order changes, and capture action is on second array element (before was **actions[11]** and now as **actions[1]**)
![sf_style](https://user-images.githubusercontent.com/5016464/30313906-a2e373ce-97a7-11e7-8d07-29e0153218ea.PNG)

Main question is, why it depends how you register?
Second, maybe it is not a bug and action order has no difference?

**Comment by makasim** [comment]
The gateway configuration goes through several steps before you can see a final version. There is a default global config, a config for such gateway factory and finally, the config you pass to factory create method, all of them are merged and processed. 

If you want to force an action to be earlier than others add it to `payum.prepend_actions` config option. Pay attention, you have to add an action name, in your example it would be `payum.action.capture_offsite`

**Comment by webmake** [comment]
Is it good to leave by default (registering like in first image via gateway factory), that first would be core cancel action, or is it kind of violation, thumb rule? Because mentioned library forces (I believe not intentionally) to load custom capture action before the core?

**Comment by makasim** [comment]
The idea is: the order of action should not be important, but sometimes that is the case whether because of the bug or the way the payment api works.

**Comment by webmake** [comment]
Agreed, thanks :)
