### ISSUE TITLE
Doctrine type json_array is deprecated use json

### ISSUE THREAD

**Issue by phiamo** [Payum/Payum#684]
see http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#json-array

the current implementation uses json_array
https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Doctrine/Resources/mapping/ArrayObject.orm.xml
for instance 

in my current setup with sf3.3 and doctrine migrations this leads to a bug that migrations concerning these fields are always regenerated.

**Comment by nicolasricci** [comment]
@makasim any thought on this change?
I personally had to change it to "text"  in my set up running symfony 4.
I am running some tests atm, I will keep you updated if the column type change cause any other issue.

**Comment by dmitryuk** [comment]
Please close the issue
