### ISSUE TITLE
Why does not have Offline gateway payout and refund actions?

### ISSUE THREAD

**Issue by Tetragramat** [Payum/Payum#688]
I thought of offline gateway as dummy, test gateway. In that case I think payout and refund would be usefull.

**Comment by makasim** [comment]
It could be used as a test gateway, but it was created for real-life cases, buy now pay by cash later in our office for example. 

Those actions haven't been implemented yet, nothing more.

**Comment by makasim** [comment]
You are welcome to contribute them.
