### ISSUE TITLE
Two tokens generated for one payment

### ISSUE THREAD

**Issue by ThomasLandauer** [Payum/Payum#703]
If I understand https://github.com/Payum/Payum/issues/700#issuecomment-338576802 right, then this is a bug:

Following the instructions on https://github.com/Payum/Payum/blob/master/docs/symfony/get-it-started.md (with https://github.com/Payum/Payum/pull/697 ), using the Sofort gateway: When opening the `prepareAction`, I get one `Payment` entity in the database, and **two** `Token` entities.

**Comment by makasim** [comment]
Nope, that's correct. You have token for capture URL and one for done URL

**Comment by makasim** [comment]
This is not common to have two CAPTURE tokens for a payment (though it doesn't immediately mean it is a bug)
