### ISSUE TITLE
Does Paypal Pro Checkout actually work?

### ISSUE THREAD

**Issue by Webvida** [Payum/Payum#706]
Hi there, are there any examples of getting Paypal Pro Checkout to work? 

I keep getting this issue:

[RESPMSG] => User authentication failed

Yet I seem to have the correct configuration:

```php
use Payum\Core\PayumBuilder;
use Payum\Core\Payum;

/** @var Payum $payum */
$payum = (new PayumBuilder())
    ->addDefaultStorages()
    ->addGateway('gatewayName', [
        'factory' => 'paypal_pro_checkout',
        'username' => 'REPLACE IT',
        'password' => 'REPLACE IT',
        'partner' => 'REPLACE IT',
        'vendor' => 'REPLACE IT',
        'sandbox' => true
    ])

    ->getPayum()
;
```

The strange thing was that it asked for a "tender" field as well - which I added as "C"... I dunno if it is because I am a noob or not. Also Paypals docs don't really help, there are so many services and stuff that it is hard to know which configurations to use for what! 

I am using the configuration from the paypal sandbox accounts list to try and access (the info in the info in Profile->API Credentials tab:

![screen shot 2017-11-05 at 8 18 23 pm](https://user-images.githubusercontent.com/260060/32412747-928f77d6-c266-11e7-9118-b592bd44bfa4.png)

Any help would be very much appreciated, thanks.

**Comment by Webvida** [comment]
Oks it was a bit convoluted but I found it (posting here to help others if they are stuck), but you have to sign up for payflow here and follow the steps to create a test account - you can then use these same credentials in your config:

https://developer.paypal.com/docs/classic/payflow/test_hosted_pages/?mark=payflow%20sandbox#create-a-test-only-payflow-gateway-account

**Comment by makasim** [comment]
Would you be so kind as to add it to the doc: https://github.com/Payum/Payum/blob/master/docs/paypal/pro-checkout/get-it-started.md

**Comment by Webvida** [comment]
Done - have added a pull request with some extra docs and the tender param

**Comment by romaricdrigon** [comment]
It should be noted that Paypal Payments Pro won't be fully integrated - we just a basic credit card form, but not quite the "hosted checkout" feature.

**Comment by iatanasov77** [comment]
> Oks it was a bit convoluted but I found it (posting here to help others if they are stuck), but you have to sign up for payflow here and follow the steps to create a test account - you can then use these same credentials in your config:
> 
> https://developer.paypal.com/docs/classic/payflow/test_hosted_pages/?mark=payflow%20sandbox#create-a-test-only-payflow-gateway-account

I try to setup a payflow account but after all steps i cannot login with no-one of accounts. Please help me.
