### ISSUE TITLE
Custom credit card form

### ISSUE THREAD

**Issue by webmake** [Payum/Payum#710]
Hello, I have more dilemma than an issue.

In basic [`ObtainCreditCardAction`](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Symfony/Action/ObtainCreditCardAction.php) contains all necessary logic with templating engine and stuff, and via yours [bundle](https://github.com/Payum/PayumBundle) injects all necessary dependencies, using [`Reference`](https://github.com/Payum/PayumBundle/blob/master/DependencyInjection/PayumExtension.php#L125). My problem is, that I need to add custom fields, such as name, surname, but I don't want to tie with symfony components as it is a package, and can't extend any object, neither [`CreditCardType`](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Symfony/Form/Type/CreditCardType.php) where I could add those fields, neither [action](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Bridge/Symfony/Action/ObtainCreditCardAction.php) itself. So I achieved that by adding plain simple input fields in template and defining that template name. Everything works perfectly if form is not filled or filled with invalid date, or other fields defined in `CreditCardType`, but when filled correctly, I need to check my own fields and re-render that template on error, but I can't because `ObtainCreditCard` returns successfully submitted credit card info via obtain method. I could validate before `ObtainCreditCard` action emit, but also, if my validations are wrong but form type is valid, I loose control of rendering.

Question is, how I could inject my template with all necessary validations?

concept:
Authorize action (if validations before):
```
        $this->gateway->execute($httpRequest = new GetHttpRequest());

        $postParams = [];
        parse_str($httpRequest->content, $postParams);
        $postParams = ArrayObject::ensureArrayObject($postParams);
        if (!$postParams['name'] || !$postParams['surname']) {
            throw new \Exception(); // bad, need Render template of ObtainCreditCard action
        }
        $obtainCreditCard = new ObtainCreditCard($request->getToken());
        $obtainCreditCard->setModel($detailsObject);
        $this->gateway->execute($obtainCreditCard);

        $card = $obtainCreditCard->obtain();
```
template
```
{% extends layout ?: "@PayumCore/layout.html.twig" %}

{% block payum_body %}
    <form method="POST" action="{{ actionUrl }}">
        {{ form_row(form) }}
        {{ form_rest(form) }}
        <div>
            <label for="name">Name</label>
            <input id="name" name="name">
        </div>
        <div>
            <label for="surname">Surname</label>
            <input id="surname" name="surname">
        </div>
        <input type="submit" value="Submit"/>
    </form>

{% endblock %}
```
Factory registering template:
```
        $config->replace([
            'payum.template.obtain_credit_card' => '/Action/authorize_payment.html.twig',
        ]);
```

**Comment by makasim** [comment]
You have to write your own custom obtain credit card action

**Comment by webmake** [comment]
I have to duplicate `ObtainCreditCardActionBuilder` an `ObtainCreditCardAction` (because of `new`), not only action, am I wrong? Then CreditCardType by adding my own fields, and then validation.xml, and even more `CreditCardDate` isn't that too much to achieve this?

**Comment by makasim** [comment]
This is not about adding fields, there is a logic behind it, validation and so on. So I think it is NOT too much.

**Comment by webmake** [comment]
Then how to overwrite `payum.action.obtain_credit_card_builder`, because [`buildActions`](https://github.com/Payum/Payum/blob/master/src/Payum/Core/CoreGatewayFactory.php#L216) catches that builder and can't register

**Comment by webmake** [comment]
I used such command:
```
        $config->replace([
            'payum.template.obtain_credit_card' => '/Action/authorize_payment.html.twig',
            'payum.action.obtain_credit_card_builder' => new Reference(ObtainOverWrittenCreditCardActionBuilder::class),
        ]);
```

**Comment by makasim** [comment]
register a build as a service and use it in the config

```
payum:
    gateways:
        foo:
            payum.action.obtain_credit_card_builder: '@builder_service_id'
```

**Comment by webmake** [comment]
Well, something succeeded, but still can't declare dynamicaly validations, due to symfony `getValidatorMappingFiles` method, because validation rules are loaded from `/var/www/project/vendor/payum/payum-bundle/Resources/config/validation.xml`, how to overwrite  this one? I could be via extended model of `CreditCard`, via annotations, but this is badly, due lack of extend..

**Comment by makasim** [comment]
you can create a yaml file (or any other) add there a validation rule for the CreatedCard class. I've never done that myself but it should work
