### ISSUE TITLE
Custom payment page using Symfony and some custom data - "how to" question.

### ISSUE THREAD

**Issue by PanzerLlama** [Payum/Payum#711]
Hi,

I would like to create a custom page for the actual payment happening. I am using stripe_js at this time. I want to show stripe pay button that launches their modal with some general info regarding the order over the button so I need to inject the array or order object into the twig while it renders the page.

I set the configuration for this page using payum.template.layout and payum.template.obtain_token options for the gateway.

My first problem was that the layout file needed some general data from my backend, I resolved this by injecting the data into twig globals through a kernel listener. 

However when the payment is created I would like to show as well some information regarding the actual placed order on the  payum.template.obtain_token page.

I thought that if I add relation with the order to my class OrderPayment that extends Payum BasePayment I could get it using the available model variable like model.order.some_order_property. But that does not fly as the model stays a simple array like that:

ArrayObject {#1682 ▼
  #input: null
  flag::STD_PROP_LIST: false
  flag::ARRAY_AS_PROPS: false
  iteratorClass: "ArrayIterator"
  storage: array:3 [▼
    "amount" => 10000
    "currency" => "GBP"
    "description" => "Booking BX566UGI1"
  ]
}

i.e. so some data I added to storage while creating the payment shows and some not:

        $storage = $this->get('payum')->getStorage('[...]\Entity\OrderPayment');

        $payment = $storage->create();
        $payment->setNumber('BX566UGI'.[...]);
        $payment->setCurrencyCode('GBP');
        $payment->setTotalAmount(10000);
        $payment->setDescription('Booking BX566UGI');
        $payment->setClientId($this->getUser()->getId());
        $payment->setClientEmail($this->getUser()->getEmail());
        $payment->setorder($order); 

$order is an instance of [...]\Entity\Order and all stores correctly in db...

Not sure how to proceed to add stuff to that ArrayObject or just to the twig variables when the controller runs. Adding this as I did with some other data seems smelly (the other data is needed by all controllers anyway so I considered this ok but the order data is useful for that particular payment page). Grateful for any tips.

Regards.

**Comment by makasim** [comment]
I suggest you add an extension that adds all required info before calling render template action.

**Comment by makasim** [comment]
Also, payment details are available in twig template too. You could take some info from them

**Comment by PanzerLlama** [comment]
Thanks @makasim, 

by "payment details" you mean the ArrayObject passed from payum controller? And by extension a twig extension? I guess not if I think about it... is there any related section on that in docs (I feel a bit lost I admit).

**Comment by makasim** [comment]
> by "payment details" you mean the ArrayObject passed from payum controller

yes

> And by extension a twig extension? I guess not if I think about it... is there any related section on that in docs (I feel a bit lost I admit).

nope. I meant Payum's extension

**Comment by makasim** [comment]
https://github.com/Payum/Payum/blob/master/docs/the-architecture.md#extensions

**Comment by makasim** [comment]
https://github.com/Payum/Payum/blob/master/docs/instant-payment-notification.md

**Comment by makasim** [comment]
https://github.com/Payum/Payum/blob/master/docs/symfony/container-tags.md#extension-tag

**Comment by PanzerLlama** [comment]
@makasim cheers!

**Comment by PanzerLlama** [comment]
I spent a bit of time on that and the links got me started (I read them before in the docs but I just could not figure out what is the correct step forward in my case).

I added an extension where in "onPreExecute" I got something like that:

```
    public function onPreExecute(Context $context)
    {
        $request = $context->getRequest();
        if ($request instanceof Capture)
        {
            $model = $request->getModel();
            if ($model instanceof ArrayObject) {
                $model['dog'] = 'woof';
                $model['pig'] = 'oink';
                $model['cat'] = 'meow';
                $request->setModel($model);
            }
        }
    }
```
That gives me the extra data in the twig template:
```
ArrayObject {#6108 ▼
  #input: null
  flag::STD_PROP_LIST: false
  flag::ARRAY_AS_PROPS: false
  iteratorClass: "ArrayIterator"
  storage: array:6 [▼
    "amount" => 83517.0
    "currency" => "GBP"
    "description" => "Order UGI1"
    "dog" => "woof"
    "pig" => "oink"
    "cat" => "meow"
  ]
}
```
But I understand I should be adding this data to twig tags when the view is rendered instead of adding the extra data to the ArrayObject. I got stuck here  trying to figure out some way to replace the payum.action.render_template but without success :/ I have problems with understanding how exactly the flow/logic works. Should I try to replace the default capture action? But even if - how can I modify then the data that is sent to twig in RenderTemplateAction?

**Comment by PanzerLlama** [comment]
Ok, scratch that, I managed to properly use the payum.action.render_template and it seems to work. So only one question remaining - how can I change the route of the capture action so it is using my "checkout" route flow. This is really not that important but I wonder if can be done easily...

**Comment by PanzerLlama** [comment]
@makasim - finally I think I got everything working as I wanted, grateful for any comments indicating if this approach is correct.

What I wanted is a payment page that blends in with my checkout flow, I wanted the payment page to look like other pages and have some general info like breadcrumbs, basic order info, etc - even if that just technically shows stripe "PAY" button (I want to have similar experience for other gateway).

This turned out to be really easy once I got some level of understanding how the library works, but I was struggling for quite a long time and did not find the documentation too helpful (maybe its just me :).

In order to achieve what I wanted I did the following steps:

1) Switched the gateway templates to my custom versions:
```
            payum.template.layout: '[...]/Payment/layout.html.twig'
            payum.template.obtain_token: '[...]/Payment/stripeJsObtainCheckoutToken.html.twig'
```

2) Created extension that would inject the extra twig objects data into the RenderTemplate request parameters so they are available when rendering the view.

```
class PayumOrderExtension implements ExtensionInterface
{
    protected $data = [];

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function onPreExecute(Context $context)
    {
        $request = $context->getRequest();
        if ($request instanceof RenderTemplate)
        {
            $request->addParameter('data', $this->data);
        }
    }
[...]
}
```
3) Last thing - I just needed to pass the data to my extension from my controller:
```
    /**
     * @Route(
     *     "/order/{orderUid}/payment",
     *     name = "order_payment",
     *     requirements = { "orderUid" = "^[A-Z0-9]+$" }
     * )
     */
    public function orderPaymentAction(Request $request, $orderUid)
    {
        [...]
        $payum = $this->get('payum');

        $gateway = $payum->getGateway('stripe_js');
        $gateway->addExtension(new PayumOrderExtension(array('this' => 'that')));

        $storage = $payum->getStorage('[...]\OrderPayment');
        [...]
        $storage->update($payment);

        $captureToken = $this->get('payum')->getTokenFactory()->createCaptureToken(
            $order->getPaymentMethod(),
            $payment,
            'order_confirmation',
            array('orderUid' => $order->getUid())
        );

        $gateway->execute(new Capture($captureToken));
```

That's it.

**Comment by makasim** [comment]
That's pretty much it! It would be great if you could format it as a doc.

**Comment by PanzerLlama** [comment]
Here you are - https://github.com/Payum/Payum/pull/717
