### ISSUE TITLE
Support Symfony 4

### ISSUE THREAD

**Issue by garak** [Payum/Payum#712]
See http://symfony.com/blog/helping-prepare-for-symfony-4-bundle-support
I tried a basic install and didn't find anythinig deprecated (but I didn't dig too deep).
Things to do:
* update composer.json
* test on travis
* explicit public/private services

**Comment by ThomasLandauer** [comment]
Here's a deprecation warning I'm getting in Symfony 3.4:

> User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since version 3.4 and will be unsupported in 4.0 for class "Payum\Bundle\PayumBundle\Profiler\PayumCollector".
