### ISSUE TITLE
[SupportRequest] Custom NotifyNullAction for IPN, that doesn't send HASH

### ISSUE THREAD

**Issue by diimpp** [Payum/Payum#713]
Hi,

I've encountered payment gateway (g2apay), that supports only single static IPN route, in other words `notify/unsafe/{gateway}`

I've implemented `NotifyNullAction`, getting IPN post data is working well, but problem, is that gateway doesn't provide original capture hash, only order id.

And here is 4 hours questions. :D How do I get token from DB (`sylius_payment_security_token` in my case), if I don't know hash and `sylius_payment<->sylius_payment_security_token` don't have any relation. Obviously I can't use `GetToken`.

Is there any other way besides iterating over all rows from `sylius_payment_security_token`? I would guess it's possible to create doctrine user function for dql access for `Doctrine\Types\ObjectType`, but is there native to payum solution for this problem?

Regards.

**Comment by makasim** [comment]
Don't they have a field that you can use to store the token hash. For example, Be2Bill has `EXTRADATA` field that you can use to store some custom data. 

https://github.com/Payum/Payum/blob/master/src/Payum/Be2Bill/Action/NotifyNullAction.php#L33

**Comment by diimpp** [comment]
Unfortunately no, they don't provide such feature.

I've asked around and my colleague encountered same thing with `unitpay`. He solved it with custom unsafe notify controller, that generates and invalidates a new notify token. But at least `unitpay` provides payment id,

For my case I've ended up doing `paymentSecurityTokenRepository->findAll()`, so now that I'm thinking about it, dql user function seems a good enough solution (Which will allow to pull security token by identity object id). Or at least for `g2apay`, which doesn't allow multiple sessions, which means I can grab any token (in case of several tokens were generated) from DB and complete it without problem.

**Comment by makasim** [comment]
Well, then there is no way but a custom notify action that:

* finds a real payment model by order id 
* execute `$gateway->execute(new Notify($payment));`

**Comment by diimpp** [comment]
Okay, got it. Thank you.

I was doing `$gateway->execute(new Notify($captureToken));`, but `$gateway->execute(new Notify($payment));` works as well in the same manner, so there is no need for token, which solves my question.

**Comment by diimpp** [comment]
May I ask a bit of unrelated question.
I've weird case, where ipn request fails because of some kind of race condition between `NotifyNullAction` and `NotifyAction`

- ipn request, there is single payment for order with correct `details`
- `NotifyNullAction` is called correctly, which I'm sure because I'm setting debug info into `details`
- `NotifyAction` is called, I'm setting debug info into `details` again
- request fails somewhere, payments is marked as `failed`, a new empty payment is created
- `NotifyNullAction` called again, failed because there is no configured new payments.

And strangest of all, I'm doing logging and logger is triggered only on second cycle, where NotifyNullAction fails, but I'm getting debug data in DB from nowhere.

Can you please share your thoughts on this.

**Comment by makasim** [comment]
Sorry, nothing jumps to my mind.
