### ISSUE TITLE
How to handle multiple gateway config's in Doctrine?

### ISSUE THREAD

**Issue by StefanGla** [Payum/Payum#716]
Hello,

I'm writing a multimerchant shop-system, where different sellers should store their different paypal credentials in one GatewayConfig-Entity. So I had the idea, to insert the foreign key of the seller into the GatewayConfig like this:

    /**
     * @ORM\Table(name="payment_gateway_config")
     * @ORM\Entity
     */
    class PaymentGatewayConfig extends BaseGatewayConfig
    {
        /**
         * @ORM\Column(name="id", type="integer")
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="IDENTITY")
         *
         * @var integer $id
         */
        protected $id;

        /**
         * @var \AppBundle\Entity\User
         *
         * @ORM\ManyToOne(targetEntity="\AppBundle\Entity\User")
         * @ORM\JoinColumn(name="id_user", referencedColumnName="id", onDelete="CASCADE")
         */
        private $id_user;
    }

But when I try to fetch the matching config for a seller, I'm not able to add the user-id as an argument.

     $gatewayConfig = $this->get('payum')->getGateway('paypal')

Is there another way, that I can "inject" the individual seller configuration into the gateway-config on demand? Or how should I handle that?
 
Best regards,
Stefan

**Comment by makasim** [comment]
Implement your own storage for gateway config entity with additional logic. The user could be taken from a service that injected via the constructor method.

The storage is used here (https://github.com/Payum/Payum/blob/master/src/Payum/Core/Registry/DynamicRegistry.php#L78) to fetch the gateway.

**Comment by StefanGla** [comment]
Can you please give me some more information about how to do this: "Implement your own storage for gateway config entity with additional logic." ?

- I have the PaymentGatewayConfig-Entity which stores the Payment-Gateways with an empty/default-config in the database.
- I use "$this->get('payum')->getGateway('offline')" to fetch that entity with the stored config.
- There I have to change the config depending on the registered user.

Currently I can't see, how I can overwrite the gatewayConfigStore in the DynamicRegistry to inject my users individual config. Could you please give me some advice, which classes or methods I need to create/overwrite an how to tell the DynamicRegistry to use my custom gatewayConfigStore?

**Comment by cansozeri** [comment]
@makasim There is not any clear example to implement multi-user based config in PAYUM. Can you please provide a clear example about to implement and store the configs per user, not gateway ? 
Two client has paypal gateway with different configs, how can we implement this with Laravel Config Store ??

@StefanGla Could you found a way to implement this ???
