### ISSUE TITLE
Braintree 

### ISSUE THREAD

**Issue by garak** [Payum/Payum#719]
The [suggested](https://github.com/Payum/Payum/blob/master/docs/supported-gateways.md#community) implementation for braintree points to a [repository](https://github.com/JakubKohout/BraintreePayum) that is clearly unfinished.
Maybe it should point to this [alternate repository](https://github.com/gdaws/payum_braintree), that looks more complete.

**Comment by makasim** [comment]
Could you please open a PR with the changes? I'll merge it.

**Comment by makasim** [comment]
Everybody could add a gateway to that list, or suggest removing.
