### ISSUE TITLE
PayPal ExpressCheckout with REST API and Smart Buttons

### ISSUE THREAD

**Issue by AlexSayHello** [Payum/Payum#721]
I am currently integrating Payum into the platform that my company uses to develop websites for clients. The minimum requirement for websites is to accept two types of payments, payment by credit card through a local gateway in my country (Redsys) and payments through Paypal.

I would like to know if it is possible to integrate Paypal ExpressCheckout with the new REST API and Smart Buttons.

I have been reading the [ExpressCheckout documentation](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/add-paypal-button/), and to integrate this with the buttons it is necessary to add a button with JS and make AJAX calls to the web.

```javascript
paypal.Button.render({
  env: 'sandbox'
  style: { color: 'gold', size: 'small' },

  payment: function(data, actions) {
    /* 
    * Set up the payment here, call the prepare.php script?
    * Must return the payment ID created from REST API
    */
  },

  onAuthorize: function(data, actions) {
    /* 
    * Execute the payment here, call the capture.php script?
    */
  },

  onCancel: function(data, actions) {
    /* 
    * Buyer cancelled the payment 
    */
  },

  onError: function(err) {
    /* 
    * An error occurred during the transaction 
    */
  }
}, '#paypal-button');
```

The current PayPal for Payum extension integrates ExpressCheckout using the old NVP API and redirects to the paypal website for payment.

I am not able to understand how to integrate this payment method, as it does not need to perform redirections and operations are performed in a floating window controlled by the Paypal script.

**Comment by makasim** [comment]
It should be implemented as a standalone, new Payum extension.
