### ISSUE TITLE
Class used in payum/core unit test does not exist

### ISSUE THREAD

**Issue by michallkanak** [Payum/Payum#722]
Take a look at: https://github.com/Payum/Core/commit/d4f63395d448e02c67dee74e7d9a8d740504f637#r26188253

Error:
`ReflectionException: Class Payum\Core\Tests\GatewayAwareAction does not exist
...\vendor\payum\core\Payum\Core\Tests\Action\GatewayAwareActionTest.php:16`

**Comment by makasim** [comment]
fixed https://github.com/Payum/Payum/commit/9a5a8bf8367b1f7d613dbcbfe8a501695596c871
