### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by pamil** [Payum/Payum#727]
Is there anything preventing supporting PHP 7.2 / releasing current master branch? May I be of some help?

**Comment by pamil** [comment]
I'm not sure what has to be changed to `>7`. If I'm not wrong, build is already passing for `master` branch on PHP 7.2 - https://travis-ci.org/Payum/Payum/builds/320366426.

**Comment by makasim** [comment]
I messed up, as always. sorry. 

Nothing really. I just wanted to postpone it a little bit to have a change to catch up some unseen bugs.

**Comment by makasim** [comment]
As for me, It works on Symfony4, PHP7.2 like a charm. I've not spotted a bug recently.

**Comment by pamil** [comment]
Ah okay, I'll run Sylius' test with dev-master Payum to test it then :)

**Comment by garak** [comment]
Can we get a new tag? Maybe `1.5.0`

**Comment by makasim** [comment]
@garak yes sure, once it is tested out for some time.

**Comment by pamil** [comment]
@makasim found Payum/PayumBundle#449.

**Comment by pamil** [comment]
And it looks like our `GatewayConfig` ORM mapping cannot find the Payum's ORM mapping to inherit it (`ALTER TABLE sylius_gateway_config DROP config, DROP gateway_name, DROP factory_name` SQL migration generated).

**Comment by pamil** [comment]
So the results are in Sylius/Sylius#9074. It works fine with that [mapping workaround](https://github.com/Sylius/Sylius/pull/9074/files#diff-58727e383b648de843a7a3ce927a77f2) and Payum/PayumBundle#449.

**Comment by pamil** [comment]
@makasim do you have any idea what might cause that mapping issue? If it's fixed, then IMO it's good to tag 1.5.0 and let people use and test it even more.

**Comment by makasim** [comment]
@pamil Sorry I don't have any. I don't use Doctrine and tests do not fail

**Comment by pamil** [comment]
All right, I'll look more into it next week.

**Comment by pamil** [comment]
Found the bug, Payum/PayumBundle#451 fixes it.

**Comment by makasim** [comment]
Payum 1.5.0 has just been released as well as PayumBundle 2.3.0
