### ISSUE TITLE
decode REQUEST_URI in HttpRequestVerifier

### ISSUE THREAD

**Issue by solverat** [Payum/Payum#728]
My PaymentProvider encodes all notify actions urls. So the pingback url they're requesting is `http://xy/payment/notify/%5FSsYp0j9YWCZfC0qpxCK58s0kaSBXVTYVDecuCqo6%5Fw`.

If the notifiyAction gets called this will lead to an error:
"The current url `http:/xy/payment/notify/%5FSsYp0j9YWCZfC0qpxCK58s0kaSBXVTYVDecuCqo6%5Fw` not match target url `http://xy/payment/notify/_SsYp0j9YWCZfC0qpxCK58s0kaSBXVTYVDecuCqo6_w` set in the token [...]"

My question is: Do i miss something?  Should Payum decode `REQUEST_URI` [here](https://github.com/Payum/Payum/blob/ab6723e851b9d7452f65a721e124495e81caafc1/src/Payum/Core/Bridge/PlainPhp/Security/HttpRequestVerifier.php#L54) (and also [here](https://github.com/Payum/Payum/blob/ab6723e851b9d7452f65a721e124495e81caafc1/src/Payum/Core/Bridge/Symfony/Security/HttpRequestVerifier.php#L51))?

Thanks!

**Comment by makasim** [comment]
I've searched Symfony's Request class for REQUEST_URI and urldecode. They don't do it neither should we I suppose. Could you please check http server configs or the sender code for possible extra url encode?

**Comment by solverat** [comment]
Hey @makasim, thanks for your feedback. Actually there is nothing special in my config and i also can't change the PP callback behaviour which is ok since they just encode the URI. In a browser callback the browser will decode URIs by itself so no problem there. So generally there is nothing wrong about encoded urls, but since you're doing a [string comparing](https://github.com/Payum/Payum/blob/ab6723e851b9d7452f65a721e124495e81caafc1/src/Payum/Core/Bridge/PlainPhp/Security/HttpRequestVerifier.php#L54) it needs to be a real encoded url i guess. 

I just tried to trigger the notify url (with a encoded notify token) via curl and the error stays the same. Maybe you could check that against?

It looks like i'm the first (and only) one with this issue which makes me curious... But i don't see a different way. Thanks!

**Comment by makasim** [comment]
I dont think there are many people who use Payum plain php features. Most of the time it is used via sort of extension\bundle\package for a web framework.

I'll look into it.

**Comment by solverat** [comment]
Actually i'm using the payum bundle, the REQUEST_URI does not get decoded by default and symfony also stays [encoded](https://github.com/symfony/symfony/pull/3780).

**Comment by makasim** [comment]
Would `rawulrdecode` be a solution?

**Comment by solverat** [comment]
hey @makasim, i just tried it with rawurldecode and it worked! 👍

**Comment by makasim** [comment]
@solverat Could you send us a PR? That would be great.
