### ISSUE TITLE
[KlarnaCheckout] Update to use most recent klarna/checkout v4 package

### ISSUE THREAD

**Issue by deji** [Payum/Payum#729]
I've not been able to integrate with Klarna Checkout using the payum/klarna-checkout package v1.4.1. Upon further investigation, I see it uses klarna/checkout v2. There is klarna/checkout v4 which does work.

Any possibility of getting payum/klarna-checkout updated to use the latest klarna/checkout v4 package?

**Comment by makasim** [comment]
I don't work with Klarna at the moment.

**Comment by makasim** [comment]
Feel free to send us a PR that fixes the issue.
