### ISSUE TITLE
The child node "security" at path "payum" must be configured.

### ISSUE THREAD

**Issue by DanielInk** [Payum/Payum#741]
Hi, i am trying to integrate payum with symfony 4 by running this command: composer require "payum/payum-bundle" "payum/offline" "php-http/guzzle6-adapter", anyways it throws this error
The child node "security" at path "payum" must be configured. i request some help on it.

**Comment by makasim** [comment]
Have you followed this doc: https://github.com/Payum/Payum/blob/master/docs/symfony/get-it-started.md

**Comment by petarvasilev91** [comment]
@makasim I followed it and still got the error, any ideas? Here is the full error:

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 228:
!!                                                                   
!!    The child node "security" at path "payum" must be configured.  
!!                                                                   
!!  
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.
```

**Comment by HeathSilcox** [comment]
I have the exact same issue.
