### ISSUE TITLE
PayPal express refund authorized payment

### ISSUE THREAD

**Issue by kubaceg** [Payum/Payum#754]
I wand refund authorized payment, here is my code:

```
 try {
            $gateway->execute(new Refund($payment));
            $gateway->execute($status = new GetHumanStatus($payment));
        } catch (ReplyInterface $e) {
            throw new PaymentRefundException($e->getMessage());
        }
```

After make such request I have error `"Request Refund{model: ArrayObject} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker."` Is it really not supported? Or maybe I'm doing it in wrong way?

**Comment by makasim** [comment]
It supported by Paypal but hasn't been implemented on Payum side, There is no Payum Action which can handle the refund request.

**Comment by pheye** [comment]
here's the diff to support `Refund` action for paypal:

https://github.com/papamonkey/PaypalExpressCheckoutNvp/commit/d0e84e6fb05339386e23701429cb75d6266a2a38

I test the code in laravel, it works.
example code:

```
use Payum\Core\Request\Refund;

$payum = app('payum');
$model = [];
$model['TRANSACTIONID'] = '<transactionid>';
$gateway = $payum->getGateway('<your paypal gateway name>');
$gateway->execute($status = new Refund($model));
$model = $status->getFirstModel();
if ($model['ACK'] == 'Success' || $model['L_ERRORCODE0'] == 10009) {
    // refund success or have refunded(10009 errcode)
} else {
    // refund failed
}
```

This is a full refund example. if you want partial refund, check see document.(`REFUNDTYPE` and `AMT` option)
