### ISSUE TITLE
GatewayFactoryBuilder does not work with OmnipayGatewayFactory

### ISSUE THREAD

**Issue by teohhanhui** [Payum/Payum#759]
> Type error: Argument 1 passed to Payum\OmnipayV3Bridge\OmnipayGatewayFactory::__construct() must be an instance of Omnipay\Common\GatewayFactory or null, array given

They have incompatible constructor signatures:

https://github.com/Payum/Payum/blob/1.5.0/src/Payum/Core/Bridge/Symfony/Builder/GatewayFactoryBuilder.php#L31

https://github.com/Payum/OmnipayV3Bridge/blob/1.0.0/src/OmnipayGatewayFactory.php#L30

**Comment by makasim** [comment]
The constructor signature should be adjusted.

**Comment by teohhanhui** [comment]
But it must mean a major version bump in https://github.com/Payum/OmnipayV3Bridge, correct?

**Comment by makasim** [comment]
Or another factory class

**Comment by makasim** [comment]
or ominpay specific factory builder

**Comment by teohhanhui** [comment]
> or ominpay specific factory builder

That would make the DX worse... :disappointed:

**Comment by makasim** [comment]
> That would make the DX worse... 😞

Why?

**Comment by teohhanhui** [comment]
Because the user would have to use a different builder class specially for the Omnipay bridge?

**Comment by makasim** [comment]
How do you use it? The omnipay factory should be available out of the box https://github.com/Payum/Payum/blob/master/src/Payum/Core/PayumBuilder.php#L640

**Comment by teohhanhui** [comment]
Yes, I've just removed the `GatewayFactoryBuilder` service following your suggestion. It works. But I still think the constructor signature should be adjusted.

**Comment by makasim** [comment]
Not sure why, it works out the box, does require anything to be.
