### ISSUE TITLE
HttpRequestVerifier fails when URL is prefixed with locale via JMSI18nRoutingBundle

### ISSUE THREAD

**Issue by TamasSzigeti** [Payum/Payum#760]
https://github.com/Payum/Payum/blob/5df1fbf9ddfb0fa6c1879d4bdeec483c7640cf73/src/Payum/Core/Bridge/Symfony/Security/HttpRequestVerifier.php#L52

This check of comparing current URL to token URL fails when JMSI18nRoutingBundle locale prefixing is in use. I believe `$httpRequest->getUri()` should be replaced with `$httpRequest->getRequestUri()`, but I'm not confident enough that it wouldn't break anything so I'm creating an issue instead of a PR. Please check it out…

Thank you

**Comment by TamasSzigeti** [comment]
Can someone look at this, please?

**Comment by TamasSzigeti** [comment]
This issue has been stale for a while, I would gladly create a PR here as well, if you have no concerns about this change.

**Comment by makasim** [comment]
@TamasSzigeti that would be great!

**Comment by TamasSzigeti** [comment]
I was wrong, the error was caused by something else

**Comment by makasim** [comment]
@TamasSzigeti have you found what caused the error?

**Comment by TamasSzigeti** [comment]
Not yet, but I've put together a sandbox app with JMSI18nRoutingBundle and it works correctly, getUri matches getRequestUri. Will let you know when I figured out anything meaningful
