### ISSUE TITLE
ID field missing from entity PaymentToken

### ISSUE THREAD

**Issue by ThomasLandauer** [Payum/Payum#789]
When following https://github.com/ThomasLandauer/Payum/blob/patch-3/docs/symfony/get-it-started.md I cannot create the entities in the database: When I try to set up a migration (`bin/console make:migration`), I'm getting this error:

> In MappingException.php line 46:
>  No identifier/primary key specified for Entity "App\Entity\PaymentToken" sub class of "Payum\Core\Model\Token". Every Entity must have an identifier/primary key.

I tried to fix this by adding this to the `PaymentToken` entity (see https://github.com/Payum/Payum/pull/788/commits/7cdcb50b03d76553f91e37518dd82a19f1dc68f1 ):

```php
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;
```

... but this leads to:

> An exception occurred while executing 'SELECT t0.id AS id_1 FROM payment_token t0 WHERE t0.id = ?' with params ["iEJnV_zOSUt-aJle301Nn0_x-JtmP4cVqp_vd9BemUE"]:

When looking into https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/Token.php I can't see any mapping information. So where are the columns for the database table defined??

**Comment by makasim** [comment]
The id is up to a user and therefore should not be defined in a basic entity. One might one to use autoincrement where others sequences and other guys UUIDs generated in the client

**Comment by makasim** [comment]
Remove the autogenerated strategy. the id is generated by the app and should be unique 

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Resources/config/doctrine/model/PaymentSecurityToken.orm.xml#L21

**Comment by makasim** [comment]
this should work:

```
/**
     * @ORM\Id()
     * @ORM\Column(type="string")
     */
    protected $id;
```

**Comment by makasim** [comment]
The "get-it-started" doc misses that part.

**Comment by ThomasLandauer** [comment]
No luck, this leads to:
> Entity of type App\Entity\PaymentToken is missing an assigned ID for field 'id'. The identifier generation strategy for this entity requires the ID field to be populated before EntityManager#persist() is called. If you want automatically generated identifiers instead you need to adjust the metadata mapping accordingly.

My table has just this one field (`id`). There's not even a column for the token! This just can't be right...

**Comment by makasim** [comment]
init it in constructor https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Model/PaymentSecurityToken.php#L37

**Comment by ThomasLandauer** [comment]
@makasim Please help!

**Comment by virtualize** [comment]
I had to update the doctrine mapping config to get rid of the MappingException mentioned above.

```php
orm:
    entity_managers:
        default:
            mappings:
                payum:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping'
                    # set this dir instead if you use `payum/payum` library
                    #dir: '%kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Bridge/Doctrine/Resources/mapping'
                    prefix: 'Payum\Core\Model'
```

source: https://stackoverflow.com/questions/24873780/error-with-doctrineschemavalidate-for-payum-token

**Comment by jimiero** [comment]
@ThomasLandauer have you ever found a solution here?

i'm also have this error when running in production ( using doctrineBundle version 2.x )

```
[Doctrine\ORM\Mapping\MappingException]                                                                                                                            
  No identifier/primary key specified for Entity "App\Entity\PaymentToken" sub class of "Payum\Core\Model\Token". Every Entity must have an identifier/primary key.  
```

**Comment by ThomasLandauer** [comment]
No. This library never worked for me.

**Comment by jimiero** [comment]
@ThomasLandauer any other suggestion on what to use?

**Comment by ThomasLandauer** [comment]
I integrated each payment provider "directly" (i.e. using their own library/SDK/WhateverTheyCallIt).

**Comment by daifma** [comment]
When I switch the auto_generate_proxy_classes to false I do not get this error
`    doctrine:
        orm:
            auto_generate_proxy_classes: false
`
