### ISSUE TITLE
Required stripe version

### ISSUE THREAD

**Issue by alexander-schranz** [Payum/Payum#816]
I'm little bit confused about the stripe version as the stripe payum say required `stripe/stripe-php:~2.0|~3.0` but sylius implemented 6.28 in there skeleton https://github.com/Sylius/Sylius-Standard/blob/master/composer.json#L44 so whats the correct supported versions of the stripe library and.

As sylius requires payum/payum and this library seems not to add conflicts for newer stripe versions I'm not sure with which versions payum is compatible.

**Comment by joshbmarshall** [comment]
It works up to stripe version 6. If you want v7 look at #839

**Comment by Prometee** [comment]
@alexander-schranz If you want to use Stripe Checkout Session with SCA support, try using this Sylius plugin : https://packagist.org/packages/prometee/sylius-payum-stripe-checkout-session-plugin

**Comment by alexander-schranz** [comment]
@Prometee   thx currently I did go with an own paypal plus implementation, but on the sylius side its handled like offline payment, as the paypal plus workflow doesn't match the sylius workflow.
