### ISSUE TITLE
Attempted to call an undefined method named "__toArray" of class "Stripe\Charge". Did you mean to call "toArray"?

### ISSUE THREAD

**Issue by ghost** [Payum/Payum#824]
A bug in CreateChargeAction.php (namespace Payum\Stripe\Action\Api) : 

Solved by : In line 70, replace "$charge->__toAttay" by "$charge->toArray"
![image](https://user-images.githubusercontent.com/48434889/68953133-8df5cc00-07c1-11ea-999c-78a548c35110.png)

**Comment by yurguis** [comment]
@obrassart-karudev I'm using Symfony but I'm not getting this error you mention.

**Comment by mrdev023** [comment]
> @obrassart-karudev I'm using Symfony but I'm not getting this error you mention.

I'm getting this error with Sylius

**Comment by Prometee** [comment]
Since v7 of `stripe/stripe-php` the `__toArray` has been renamed to `toArray`, so `payum/payum` have to take care of this change and allow using both of those versions or drop support of older `stripe/stripe-php` (into the furtur v2.0 maybe)

**Comment by pierredup** [comment]
This has been fixed in #827
