### ISSUE TITLE
Field 'afterUrl' doesn't have a default value

### ISSUE THREAD

**Issue by gundamew** [Payum/Payum#826]
Hi,

I am trying to create a custom Payum Laravel package with the [examples](https://github.com/Payum/Payum/blob/master/docs/laravel/get-it-started.md). But I have encountered an issue when I send request to [prepare method of controller](https://github.com/Payum/Payum/blob/master/docs/laravel/get-it-started.md#prepare-payment):

> SQLSTATE[HY000]: General error: 1364 Field 'afterUrl' doesn't have a default value
>
> (SQL: insert into `payum_tokens` (`hash`, `gatewayName`, `details`, `targetUrl`, `updated_at`, `created_at`) values (..., offline, ..., http://example.com/api/payment2019-11-25 09:09:09payum_token=4y1CYNr9UoRQISaOATFsQW5mx8wd24Er7Xnx1WxnbTw, 2019-11-25 09:09:09, ?))

The database schema of token table is [here](https://github.com/Payum/Payum/blob/master/docs/laravel/eloquent-storage.md).

Do I miss something?

---

I noticed the creation of `$afterToken` only have 4 arguments with method `GenericTokenFactory::createToken`.

[Payum\Core\Security\GenericTokenFactory#L50](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Security/GenericTokenFactory.php#L50)

And `GenericTokenFactory::createToken` uses `AbstractTokenFactory::createToken` to generate the token.

But the default value of 5th argument `afterPath` is null. And if it is null, the step of setting `afterUrl` attribute will be skipped:

[Payum\Core\Security\AbstractTokenFactory.php#L62-L69](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Security/AbstractTokenFactory.php#L62-L69)

```php
if ($afterPath && 0 === strpos($afterPath, 'http')) {
    $afterUri = HttpUri::createFromString($afterPath);
    $afterUri = $this->adQueryToUri($afterUri, $afterParameters);

    $token->setAfterUrl((string) $afterUri);
} elseif ($afterPath) {
    $token->setAfterUrl($this->generateUrl($afterPath, $afterParameters));
}
```

**Comment by yurguis** [comment]
@gundamew Your schema definition is not allowing null values to be inserted in the database. I haven't work with Laravel but looking at the schema you have provided and the Laravel documentation available here https://laravel.com/docs/5.0/schema#adding-columns it seems that you need to add -`>nullable() ` or `->default($value)` to `afterUrl` column definition.

**Comment by gundamew** [comment]
Make `afterUrl` column nullable or give it a default value may resolve this issue. But the `afterUrl` assignment still looks incomplete here.

**Comment by gundamew** [comment]
Maybe I have misunderstood the code. I am going to close this issue.
