### ISSUE TITLE
After upgrading to symfony 5 capture controller returns error 'no container set'

### ISSUE THREAD

**Issue by zspine** [Payum/Payum#850]
Symfony Version: **4.4** (worked fine)
Current Version: **5.0** (not working after upgrading to symfony 5)
Payum Version: **2.4.1**
Stripe Gateway: **1.5**
PHP: **7.3.3**

Following error thrown during the [prepareAction](https://github.com/Payum/Payum/blob/master/docs/symfony/get-it-started.md) request

Error: "Payum\Bundle\PayumBundle\Controller\CaptureController" has no container set, did you forget to define it as a service subscriber?

I've found a similar issue at [stackoverflow](https://stackoverflow.com/questions/60454588/payum-integration-in-symfony-5-returns-error-no-container-set) and couldn't find any solutions. Possibly it might be something to do with symfony 5 compatibility.

**Comment by zspine** [comment]
As a temporary fix I have configured the service manually under config/services.yaml and it works....

```
    Payum\Bundle\PayumBundle\Controller\CaptureController:
        calls:
            - [setContainer, ['@service_container']]
```

**Comment by Tetragramat** [comment]
https://github.com/Payum/PayumBundle/issues/507

**Comment by zspine** [comment]
@Tetragramat Thank you! it make sense now...
