### ISSUE TITLE
Payum\Core\Exception\InvalidArgumentException: "Gateway factory "offline" does not exist.

### ISSUE THREAD

**Issue by nikowiegand** [Payum/Payum#869]
Hi there,

I recently tried to update a website using payum via the contao cms.
The update worked except for the payum bundle.
I always get the error:
`Uncaught PHP Exception Payum\Core\Exception\InvalidArgumentException: "Gateway factory "offline" does not exist." at /vendor/payum/core/Payum/Core/Registry/AbstractRegistry.php line 117 {"exception":"[object] (Payum\\Core\\Exception\\InvalidArgumentException(code: 0): Gateway factory \"offline\" does not exist. at vendor/payum/core/Payum/Core/Registry/AbstractRegistry.php:117)"} []`
My config for this looks like:
`gateways:

        core:

          payum.template.layout: OrderBundle::layout.html.twig

        prepayment:

          factory: offline

        invoice:

          factory: offline

        e112:

          factory: offline

        patient:

          factory: offline

        paypal_express:

          factory: paypal_express_checkout

          username: ****

          password: ****

          signature: ****

          sandbox: true

        stripe_js:

          factory: stripe_js

          publishable_key: ****

          secret_key: ****

          payum.template.layout: OrderBundle::stripe.html.twig `

so the gateways should be there!
In composer I require :
"payum/payum-bundle": "2.1",
Even if I am trying to use the stripe or paypal gateway I get  the error with "Gateway factory "offline"..."

Does anybody has an idea where I could find the error? Or even look for it.

Regards
Niko

**Comment by Tetragramat** [comment]
You need to require `payum/offline`. Gateways are not included in `payum/payum-bundle`.

See https://packagist.org/packages/payum/payum-bundle#2.1.2 Requires section.
