### ISSUE TITLE
PSR-4 Compliance Issue

### ISSUE THREAD

**Issue by awadood** [Payum/Payum#878]
The users with composer 2 are unable to use this package because of PSR-4 incompatibility. The following two classes from payum package do not comply with PSR-4.

	Payum\ISO4217\Tests\CurrencyTest
	Payum\ISO4217\Tests\ISO4217Test

Solution:

	Move these two to a new Directory "Tests" inside iso4217

**Comment by pierredup** [comment]
@awadood Those come from the `https://github.com/Payum/iso4217` repository (which was forked from another repo). Do you mind opening the issue on that repo instead, so that it can be addressed there?
Thanks.

**Comment by awadood** [comment]
@pierredup thank you so much for your spontaneous guide. I have created the issue there. The link is https://github.com/alcohol/iso4217/issues/25 

I am now closing this issue here. Thanks!
