### ISSUE TITLE
Tag a new version of payum/core?

### ISSUE THREAD

**Issue by winzou** [Payum/Payum#882]
Hi,

It seems that several nice PR were merged. I was looking specifically to the one making payum compatible with twig/twig 3.0.
I looks like we can just tag a new version for `payum/core`? So that we can all use it in our projects.

Thanks

**Comment by pamil** [comment]
PHP 8 support would be also very welcomed :)

**Comment by makasim** [comment]
https://github.com/Payum/Core/releases/tag/1.6.1

**Comment by pamil** [comment]
Thanks!

**Comment by BlackWiCKED** [comment]
This new version broke some old functionalities: https://github.com/Payum/Payum/issues/883
