### ISSUE TITLE
Request GetHumanStatus{model: ArrayObject} is not supported

### ISSUE THREAD

**Issue by jhfyang** [Payum/Payum#890]
Hello,

I have installed payum-bundle with the gateway paypal_rest. And I am trying to implement the xpress Checkout with the REST API. After configuring the bundle and the gateway, after the prepare action I have been coming with this exception on the
payment/capture/XXXXXX redirection.

I have looked other issues with the same problem but it has not solved my issue

    HTTP 500 Internal Server Error
    Request GetHumanStatus{model: ArrayObject} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.
These are my versions:

     paypal/rest-api-sdk-php                  1.13.0             PayPal's PHP SDK for REST APIs
     payum/core                               1.5.0              One million downloads of Payum already! Payum offers...
     payum/iso4217                            1.0.1              ISO 4217 PHP Library
     payum/paypal-rest                        1.5.0              The Payum extension. It provides Paypal REST payment...
     payum/payum-bundle                       2.3.0              One million downloads of Payum already! Payum offers...

Here is my config.yml

    payum:
        security:
            token_storage:
                UTIP\BackofficeBundle\Entity\UtPaypalPaymentTokens: { doctrine: orm }
        storages:
            UTIP\BackofficeBundle\Entity\UtPaypalPaymentDetails: { doctrine: orm }
            UTIP\BackofficeBundle\Entity\UtPaypalPayments: { doctrine: orm }
            Payum\Paypal\Rest\Model\PaymentDetails:
                filesystem:
                    storage_dir: %kernel.root_dir%/Resources/storage
                    id_property: idStorage
        gateways:
            paypal_rest:
                factory: paypal_rest
                client_id: myid
                client_secret: mysecret
                config_path: '%kernel.root_dir%/config/sdk_config.ini'
                sandbox: true
    
And here is my controller : 

    class PaypalPaymentController extends Controller
    {
	    public function prepareAction()
	    {
		$gatewayName = 'paypal_rest';

		$storage = $this->get('payum')->('UTIP\BackofficeBundle\Entity\UtPaypalPayments');

		$payment = $storage->create();
		$payment->setNumber(uniqid());
		$payment->setCurrencyCode('EUR');
		$payment->setTotalAmount(123); // 1.23 EUR
		$payment->setDescription('A description');
		$payment->setClientId('anId');
		$payment->setClientEmail('thomas-buyer@utip.io');

		$storage->update($payment);

		$captureToken = $this->get('payum')->getTokenFactory()->createCaptureToken(
			$gatewayName,
			$payment,
			'utip_backofficebundle_paypal_done'
		);

		return $this->redirect($captureToken->getTargetUrl());
	}

	public function doneAction(Request $request)
	{
		$token = $this->get('payum')->getHttpRequestVerifier()->verify($request);

		$gateway = $this->get('payum')->getGateway($token->getGatewayName());

		// You can invalidate the token, so that the URL cannot be requested any more:
		// $this->get('payum')->getHttpRequestVerifier()->invalidate($token);

		// Once you have the token, you can get the payment entity from the storage directly.
            	 //$identity = $token->getDetails();
		 //$payment = $this->get('payum')->getStorage($identity->getClass())->find($identity);
		//$status = new GetHumanStatus($token);
		// Or Payum can fetch the entity for you while executing a request (preferred).
		$gateway->execute($status = new GetHumanStatus($token));
		$payment = $status->getFirstModel();
		// Now you have order and payment status
		return new JsonResponse(array(
			'status' => $status->getValue(),
			'payment' => array(
				'total_amount' => $payment->getTotalAmount(),
				'currency_code' => $payment->getCurrencyCode(),
				'details' => $payment->getDetails(),
			),
		));
	}
}

**Comment by pierredup** [comment]
It seems this issue happens when using the default Payment model with the PayPal Rest Gateway.

```php
/** @var Payment $payment * /
$payment = $storage->create();
$payment->setTotalAmount(200);
$payment->setCurrencyCode('EUR');

$captureToken = $payum->getTokenFactory()->createCaptureToken('paypal_rest', $payment, 'done.php');
```


The PayPal Rest gateway works a bit different than the other gateway, where you need to explicitly build the Payment object

```php
$payer = new Payer();
$payer->payment_method = "paypal";

$amount = new Amount();
$amount->currency = "USD";
$amount->total = "1.00";

$transaction = new Transaction();
$transaction->amount = $amount;
$transaction->description = "This is the payment description.";

$captureToken = $payum->getTokenFactory()->createCaptureToken('paypal_rest', $payment, 'done.php');

$redirectUrls = new RedirectUrls();
$redirectUrls->return_url = $captureToken->getTargetUrl();
$redirectUrls->cancel_url = $captureToken->getTargetUrl();

$payment->intent = "sale";
$payment->payer = $payer;
$payment->redirect_urls = $redirectUrls;
$payment->transactions = array($transaction);
```

This is addressed in #891, where both options are now supported.

**Comment by kevinG73** [comment]
I use this model and i get the same error so could you update documentation ?
 the PayPal Rest Gateway support credit card ?

```
 /**
     * @Route("/paypal",name="payment_begin")
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function paypal(Payum $payum)
    {
        $gatewayName = 'paypalRest';
        $storage = $payum->getStorage('App\Entity\Payment');

        $payment = $storage->create();
        $storage->update($payment);

        $address = new Address();
        $address->line1 = "3909 Witmer Road";
        $address->line2 = "Niagara Falls";
        $address->city = "Niagara Falls";
        $address->state = "NY";
        $address->postal_code = "14305";
        $address->country_code = "US";
        $address->phone = "716-298-1822";

        $card = new CreditCard();
        $card->type = "visa";
        $card->number = "4417119669820331";
        $card->expire_month = "11";
        $card->expire_year = "2019";
        $card->cvv2 = "012";
        $card->first_name = "Joe";
        $card->last_name = "Shopper";
        $card->billing_address = $address;

        $fi = new FundingInstrument();
        $fi->setCreditCard($card);

        $payer = new Payer();
        $payer->setPaymentMethod("credit_card");
        $payer->setFundingInstruments(array($fi));

        $amount = new Amount();
        $amount->currency = "USD";
        $amount->total = "1.00";

        $transaction = new Transaction();
        $transaction->amount = $amount;
        $transaction->description = "This is the payment description.";

        $captureToken = $payum->getTokenFactory()->createCaptureToken($gatewayName, $payment, 'payment_done'
        );

        $redirectUrls = new RedirectUrls();
        $redirectUrls->return_url = $captureToken->getTargetUrl();
        $redirectUrls->cancel_url = $captureToken->getTargetUrl();

        $payment->intent = "sale";
        $payment->payer = $payer;
        $payment->transactions = array($transaction);

        return $this->redirect($captureToken->getTargetUrl());
    }

    /**
     * @Route("/ddoner", name="payment_done")
     */
    public function doneAction(Request $request, Payum $payum): JsonResponse
    {
        $token = $payum->getHttpRequestVerifier()->verify($request);
        $gateway = $payum->getGateway($token->getGatewayName());

        // Or Payum can fetch the entity for you while executing a request (preferred).
        $gateway->execute($status = new GetHumanStatus($token));
        $model = $status->getFirstModel();
        // Now you have order and payment status
        $details = $model->getDetails();

        if ($status->isCaptured() || $status->isAuthorized()) {
            switch ($details['RESPMSG']) {
                case "Approved":
                    dd($details);
                    break;
                default:
                    dd($details);
                    break;
            }
        }

    }
```

**Comment by pierredup** [comment]
@kevinG73 Your example is missing a last call to `$storage->update` to save the payment details. Without this call, the details you set won't be saved which would then cause issues when trying to complete the payment

```php

public function paypal(Payum $payum)
{
    $gatewayName = 'paypalRest';
    $storage = $payum->getStorage('App\Entity\Payment');

    // ....

    $payment->transactions = array($transaction);

    $storage->update($payment); // <--- Add this

    return $this->redirect($captureToken->getTargetUrl());
}
```

**Comment by kevinG73** [comment]
@pierredup after to add , I get this error : 
`The identifier id is missing for a query of App\Entity\Payment`

**Comment by pierredup** [comment]
@kevinG73 Can you please try with the latest changes in master? If you still experience any errors, please open a new issue with all the details.
