### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by jzecca** [Payum/Payum#892]
Hi everyone,

Could it be possible to tag a new version please?

1.6.1 requires an old version of alcohol/iso4217, making it incompatible with PHP 8:

```
$ composer req payum/core   
Using version ^1.6 for payum/core

    - payum/core 1.6.0 requires php ^7.0 -> your php version (8.0.3) does not satisfy that requirement.
    - payum/core 1.6.1 requires alcohol/iso4217 ^3.1 -> found alcohol/iso4217[3.1.0, ..., 3.1.5] but the package is fixed to 4.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires payum/core ^1.6 -> satisfiable by payum/core[1.6.0, 1.6.1]
```

This has been fixed recently by #888, but hasn't been released yet.

Thanks in advance, and keep up the good work! 👍 

----

PS: `composer req payum/core:dev-master` / `composer req payum/core:1.6.x-dev` doesn't work either (not sure why though).

**Comment by toooni** [comment]
@jzecca Until then you can use `composer require payum/core --ignore-platform-req=php`. Just be sure that you do not have other dependencies which are really not compatible with PHP 8.

**Comment by pierredup** [comment]
Once the next [milestone](https://github.com/Payum/Payum/milestone/3) has been closed, then the next version will be tagged

**Comment by jzecca** [comment]
I'll close the issue then, thanks for your feedback!
