### ISSUE TITLE
Supporting Payum

### ISSUE THREAD

**Issue by Tetragramat** [Payum/Payum#913]
Since @makasim does not have any time to maintain Payum and Patreon is disabled, then the Supporting Payum section in readme  https://github.com/Payum/Payum#supporting-payum is outdated and should be removed.

**Comment by pierredup** [comment]
The sponsor section in the README has been updated in https://github.com/Payum/Payum/commit/334ef039b980ef564454c1d01a71e4ad1d5321b1
