### ISSUE TITLE
[doctrine/dbal:^2] Unknown column type "json_array" requested

### ISSUE THREAD

**Issue by Prometee** [Payum/Payum#922]
With `doctrine/dbal:^2.7` an error occured while using the command `doctrine:schema:update` :

```
Unknown column type "json_array" requested. Any Doctrine type that you use   
  has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get  
   a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(  
  ). If this error occurs during database introspection then you might have f  
  orgotten to register all database types for a Doctrine Type. Use AbstractPl  
  atform#registerDoctrineTypeMapping() or have your custom types implement Ty  
  pe#getMappedDatabaseTypes(). If the type name is empty you might have a pro  
  blem with the cache or forgot some mapping information.
```
[GitHub Action triggerring this error >>](https://github.com/Sylius/Sylius/runs/4192723890?check_suite_focus=true#step:9:16)

I could be wrong but there is no way to change a doctrine mapping field type outside of this package, right ?

So is it still a BC break according the comment found here : https://github.com/Payum/Payum/pull/920#discussion_r729777976 ?
 I can't see any migration path because those types `json` and `json_array` are exactly the same types from a database perpective.

**Comment by pierredup** [comment]
@Prometee Currently we can't migrate easily from `json_array` to `json` for the Doctrine mappings due to the BC break.
In #920 we've limited the DBAL version to version 2 for the dev dependencies, but this doesn't prevent you from using DBAL 3 in your project. I'm not sure what the best migration path would be, or the best option to support both DBAL 2 and 3, but I will think about it a bit and try and work on a solution.

**Comment by Prometee** [comment]
@pierredup I'm not sure if the difference between `json_array` and `json`. I compare those two types :

- https://github.com/doctrine/dbal/blob/2.13.x/lib/Doctrine/DBAL/Types/JsonArrayType.php
- https://github.com/doctrine/dbal/blob/2.13.x/lib/Doctrine/DBAL/Types/JsonType.php

appart from the `null` value there is no difference between those two types and Payum is not using `null` value as a default value :

- `Payum\Core\Model\ArrayObject` default value of `details` field is `[]`: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/ArrayObject.php#L9
- `Payum\Core\Model\GatewayConfig` default value of `details` field is `[]` : https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/GatewayConfig.php#L33
- `Payum\Core\Model\Payout` default value of `details` field is `[]` : https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/Payout.php#L41
- `Payum\Core\Model\Payment` default value of `details` field is `[]` : https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/Payment.php#L53

From your point of view, what is causing the BC break ?

**Comment by pierredup** [comment]
@Prometee Thanks for pointing that out. The BC break is if there are any `null` values stored in the DB, but based on your assessment, that shouldn't be the case, unless someone extends one of the classes and overwrited the default value.

The other break is on https://github.com/doctrine/dbal/blob/7d00842301622a6890fd574676ddbbf7ee5f074d/lib/Doctrine/DBAL/Types/JsonType.php#L62-L64 where a `ConversionException` is thrown if the value can't be decoded. Previously, you would just get a `null` returned, and now will get an exception. But this shouldn't be the case unless someone purposefully saves wrong data or overwrites the classes, which we can't cover in any BC promise.

I've created #924 to address this, and will see if there are any feedback or concerns about the change
