### ISSUE TITLE
Update Guzzle deprecation to reference PSR-18 instead of Httplug

### ISSUE THREAD

**Issue by rimas-kudelis** [Payum/Payum#954]
Payum still references Httplug as its planned HTTP client implementation successor for Guzzle for version 2.0. This seems to have been decided back in 2016 in #491.

I'd like to suggest updating these notices to reference PSR-18 instead. Additionally, it would be nice if a proper client bridge were created in 1.x to make future migration easier.

Also, I think it would make sense to mark `Payum\Core\HttpClientInterface` as deprecated the same way all its concrete implementations (and the Guzzle factory) are marked already. I'm guessing that the lack of a deprecation docblock above it is an oversight and not intentional?

**Comment by Tetragramat** [comment]
I don't like that I'm forced to use http client that Payum provides. It should be made so gateway implementation is not blocked by Payum to use whatever it needs as dependency. For example in some gateways I need to use soap, but I'm still forced to use httplug client. In some other gatways I use library that implements communication with gateway api, but it uses it's own client (guzzle or psr interface).

**Comment by rimas-kudelis** [comment]
I don't think you're actually required to use Payum's client, you can use yours if you want.

**Comment by pierredup** [comment]
I think it makes sense to remove any HTTP client integration in Payum core, since I don't think it's needed or used anywhere inside core, and let each gateway do it's own HTTP client integration.

For the gateways provided by this repository, we can prefer Guzzle 7 where needed.

**Comment by rimas-kudelis** [comment]
@pierredup I fully agree about removing it, but so long as it's there and Sylius is trying to provide it, I'd rather see Sylius providing the Symfony client than Guzzle.

**Comment by pierredup** [comment]
@rimas-kudelis Well there won't be anything to provide from external apps. E.G in the `payum/paypal-express-checkout-nvp` package, we would just require Guzzle 7 and use the Guzzle client inside that package, the same with every other gateway provided in this repo. If Sylius has it's own integration with other gateways, then they will be able to use the Symfony client for those gateways

**Comment by rimas-kudelis** [comment]
Oh, sorry, I assumed this was a different feature request which I made on the Sylius repo. :)

Either way, the deprecation comments currently say that Httplug is the designated successor. If the plan has changed, these comments should probably be updated and perhaps even more classes should be deprecated.

Although on the other hand, if you plan for Payum gateways to keep throwing objects that look like HTTP messages, perhaps having a default client does make some sense still. :shrug: 

Regarding Guzzle, I'd say all gateways should be updated to use PSR (or at least Httplug) abstractions, so that the end user doesn't end up being forced to install specific implementation (or even worse – multiple implementations) of PSR-18 (or other PSRs) just to satisfy different preferences of different gateway authors. I believe the choice between Guzzle vs something else should be left to your downstream users.

**Comment by rimas-kudelis** [comment]
> When someone installs `payum/core` and `payum/paypal-express-checkout-nvp`, everything should just work out of the box without getting error messages and having to install something else to get everything working.

I don't fully agree with this. If the user is already reading some README and installing two packages instead of one, adding a third one to the list doesn't really hurt, in my opinion. In the README it can also be worded as an example/suggestion instead of a hard dependency. On the other hand, if you require specific implementaion directly in composer, the user is forced to use it even if they know that they already have a different and fully compatible HTTP client.

Ideally, you would just depend on an `-implementation` metapackage, however, Composer does neither suggest, nor allow interactively choosing a concrete implementation of metapackages when installing their dependents, which means the user still has to choose one explicitly. On the other hand, without a concrete implementation already installed or selected for installation, Composer would at least refuse to install its dependent.

> This might not always be up to us to decide which HTTP client an integration uses.

Sure, you may not have much of a choice when an official SDK is involved, but I'm talking about those cases where you do. 

Anyways, let's not bury my initial report with too much discussion. I suppose you would agree with this part:

> Either way, the deprecation comments currently say that Httplug is the designated successor. If the plan has changed, these comments should probably be updated and perhaps even more classes should be deprecated.

?

**Comment by mbabker** [comment]
Based on https://github.com/php-http/httplug/releases/tag/2.4.0 (or more specifically, https://github.com/php-http/httplug/pull/171), the deprecation/upgrade path will need to be revisited.

**Comment by pierredup** [comment]
This has been done in #975, using a PSR-18 Http client using `php-http` client discovery, so you are free to use any implementation you want.  And based on https://github.com/php-http/discovery/pull/208, a default implementation will be installed when you don't have one installed by default, which means users only need to install `payum/core`, and everything will work since everything will be provided by default, or they can choose to install a specific http-client implementation package
