### ISSUE TITLE
[Paypal express-checkout-nvp] Inconsistency in Transaction Status Key Naming

### ISSUE THREAD

**Issue by ViniTou** [Payum/Payum#988]
Greetings,

I've outlined the logic flow below and would appreciate corrections if any discrepancies are identified:

1. **Incoming Notify Action:** Initiates the `\Payum\Paypal\ExpressCheckout\Nvp\Action\PaymentDetailsSyncAction`.

2. Within the `PaymentDetailsSyncAction`, transactions are fetched for each transaction in a loop:

    ```php
    foreach (range(0, 9) as $index) {
        if ($model['PAYMENTREQUEST_'.$index.'_TRANSACTIONID']) {
            $this->gateway->execute(new GetTransactionDetails($model, $index));
        }
    ```
3. The response for these transactions is stored in the model through the `GetTransactionDetailsAction`:

    ```php
    $result = $this->api->getTransactionDetails(array('TRANSACTIONID' => $model[$transactionIndex]));
    foreach ($result as $name => $value) {
        if (in_array($name, $this->getPaymentRequestNFields())) {
            $model['PAYMENTREQUEST_'.$request->getPaymentRequestN().'_'.$name] = $value;
        }
    }
    ```

    Note: Each value is stored under a key with the `PAYMENTREQUEST_` prefix.

4. The complete model is intended to be used with `GetHumanStatus`. However, there appears to be an issue with the checks for transaction status, as they reference values under the wrong key in `PaymentDetailsStatusAction.php`:

    ```php
    src/Payum/Paypal/ExpressCheckout/Nvp/Action/PaymentDetailsStatusAction.php:95
    foreach (range(0, 9) as $index) {
        if (null === $paymentStatus = $model['PAYMENTINFO_'.$index.'_PAYMENTSTATUS']) {
            continue;
        }
    ```
    Question: Is there a reason why this setup might not be working, or is it a case of misnamed keys? If the latter, should the key in `PaymentDetailsStatusAction` be updated?

Your insights on this matter would be highly valuable. Thank you.

**Comment by pierredup** [comment]
If there are any other issues, please feel free to re-open the issue and add additional detail

**Comment by ViniTou** [comment]
Thing is I was not talking about capturing payment, as that works fine, but `Notify` action flow.
